import { v } from "convex/values";
import type { Id } from "./_generated/dataModel";
import { mutation, query, type MutationCtx } from "./_generated/server";
import { mapConvexCampaignRecordToCampaign } from "../lib/campaign-mapper";
import {
  convexRowToApprovalSnapshot,
  destinationModeForHeartbeatRoute,
  mapHeartbeatRiskToTaskPriority,
  resolveCheckDate,
  runHeartbeatEvaluation,
  stableTaskIdFromDedupe,
  type HeartbeatTaskSpec,
} from "../lib/campaign-heartbeat";
import { sanitizeTodayTaskForConvex } from "./todayTasks";

const checkTypeValidator = v.union(
  v.literal("daily"),
  v.literal("friday_readiness"),
  v.literal("manual"),
  v.literal("campaign_detail_check"),
);

function stripTaskRecord(record: Record<string, unknown>) {
  const rest = { ...record };
  delete rest._id;
  delete rest._creationTime;
  return rest;
}

async function upsertHeartbeatTask(
  ctx: MutationCtx,
  args: {
    spec: HeartbeatTaskSpec;
    checkId: string;
    checkDate: string;
    campaignPublicId?: string;
    now: number;
    baseSortOrder: number;
    index: number;
  },
): Promise<{ outcome: "created" | "updated" | "skipped"; taskId: string }> {
  const { spec, checkId, checkDate, campaignPublicId, now, baseSortOrder, index } = args;
  const dedupeKey = spec.dedupeKey;
  const taskId = stableTaskIdFromDedupe(dedupeKey);

  const matches = await ctx.db
    .query("todayTasks")
    .withIndex("by_dedupe_key", (q) => q.eq("dedupeKey", dedupeKey))
    .collect();

  const current = matches.find((t) => t.status === "current");
  const completed = matches.filter((t) => t.status === "completed");

  const destinationMode = destinationModeForHeartbeatRoute(spec.destinationRoute);
  const priority = mapHeartbeatRiskToTaskPriority(spec.hbRisk);

  const payload: Record<string, unknown> = {
    taskId,
    title: spec.title,
    context: spec.context,
    category: spec.category,
    priority,
    sourceRoute: spec.destinationRoute,
    sourceLabel: "Campaign Heartbeat",
    destinationMode,
    status: "current",
    updatedAt: now,
    dedupeKey,
    sourceType: "heartbeat",
    campaignId: campaignPublicId,
    heartbeatCheckId: checkId,
    ownerLabel: spec.ownerLabel,
    ownerType: spec.ownerType,
    dueDate: checkDate,
    taskRiskLevel: spec.hbRisk,
    externalDependency: spec.externalDependency,
    destinationRoute: spec.destinationRoute,
    autoGenerated: true,
    generatedBy: spec.generatedBy,
    taskCategory: spec.taskCategory,
  };

  if (current?._id) {
    const merged = sanitizeTodayTaskForConvex({
      ...stripTaskRecord(current as unknown as Record<string, unknown>),
      ...payload,
      createdAt: (current as { createdAt: number }).createdAt,
      sortOrder: (current as { sortOrder: number }).sortOrder,
      completedAt: undefined,
      status: "current",
    });
    await ctx.db.replace(current._id, merged as never);
    return { outcome: "updated", taskId };
  }

  if (completed.length > 0) {
    return { outcome: "skipped", taskId };
  }

  const inserted = sanitizeTodayTaskForConvex({
    ...payload,
    createdAt: now,
    completedAt: undefined,
    sortOrder: baseSortOrder + index + 1,
  });
  await ctx.db.insert("todayTasks", inserted as never);
  return { outcome: "created", taskId };
}

export const listHeartbeatChecks = query({
  args: {
    campaignId: v.optional(v.string()),
    limit: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const limit = Math.min(Math.max(args.limit ?? 25, 1), 100);
    let rows = await ctx.db.query("heartbeatChecks").collect();
    if (args.campaignId) {
      rows = rows.filter((r) => r.campaignId === args.campaignId);
    }
    rows.sort((a, b) => b.createdAt - a.createdAt);
    return rows.slice(0, limit);
  },
});

export const getLatestHeartbeatCheck = query({
  args: { campaignId: v.optional(v.string()) },
  handler: async (ctx, args) => {
    const rows = await ctx.db.query("heartbeatChecks").collect();
    const filtered = args.campaignId ? rows.filter((r) => r.campaignId === args.campaignId) : rows;
    if (!filtered.length) return null;
    return filtered.sort((a, b) => b.createdAt - a.createdAt)[0] ?? null;
  },
});

export const runCampaignHeartbeat = mutation({
  args: {
    campaignId: v.optional(v.string()),
    checkType: v.optional(checkTypeValidator),
    source: v.optional(v.string()),
    currentDate: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const now = Date.now();
    const checkDate = resolveCheckDate(now, args.currentDate);
    const checkType = args.checkType ?? "manual";
    const source = args.source ?? "home_button";

    const [campaignRows, assetRows, approvalRows] = await Promise.all([
      ctx.db.query("campaigns").collect(),
      ctx.db.query("productionAssets").collect(),
      ctx.db.query("approvalItems").collect(),
    ]);
    const campaigns = campaignRows.map((row) => mapConvexCampaignRecordToCampaign(row as never));
    const productionAssets = assetRows.map((r) => ({
      productionAssetId: r.productionAssetId,
      assetType: r.assetType,
      status: r.status,
      readinessStatus: r.readinessStatus,
      transcriptStatus: r.transcriptStatus,
      thumbnailStatus: r.thumbnailStatus,
      shortsCount: r.shortsCount,
      readyShortsCount: r.readyShortsCount,
      lastSyncedAt: r.lastSyncedAt,
    }));

    const approvals = approvalRows.map((row) =>
      convexRowToApprovalSnapshot({
        linkedCampaignId: row.linkedCampaignId,
        owner: row.owner,
        status: row.status,
        type: row.type,
      }),
    );

    const evaluation = runHeartbeatEvaluation({
      campaigns,
      approvals,
      productionAssets,
      checkType,
      explicitCampaignId: args.campaignId,
      checkDate,
      nowMs: now,
    });

    const allTasks = await ctx.db.query("todayTasks").collect();
    const maxSort = allTasks.reduce((m, t) => Math.max(m, t.sortOrder), 0);

    const createdTaskIds: string[] = [];
    const updatedTaskIds: string[] = [];
    const skippedTaskKeys: string[] = [];

    let idx = 0;
    for (const spec of evaluation.taskSpecs) {
      const res = await upsertHeartbeatTask(ctx, {
        spec,
        checkId: evaluation.checkId,
        checkDate: evaluation.checkDate,
        campaignPublicId: evaluation.campaignId ?? undefined,
        now,
        baseSortOrder: maxSort,
        index: idx,
      });
      idx += 1;
      if (res.outcome === "created") createdTaskIds.push(res.taskId);
      else if (res.outcome === "updated") updatedTaskIds.push(res.taskId);
      else skippedTaskKeys.push(spec.dedupeKey);
    }

    let campaignConvexId: Id<"campaigns"> | undefined;
    if (evaluation.campaignId) {
      const doc = await ctx.db
        .query("campaigns")
        .withIndex("by_campaign_id", (q) => q.eq("campaignId", evaluation.campaignId as string))
        .unique();
      if (doc) campaignConvexId = doc._id;
    }

    const checkDoc = {
      checkId: evaluation.checkId,
      campaignId: evaluation.campaignId ?? undefined,
      campaignConvexId,
      campaignName: evaluation.campaignName,
      checkDate: evaluation.checkDate,
      weekday: evaluation.weekday,
      checkType: evaluation.checkType,
      status: evaluation.status,
      summary: evaluation.summary,
      currentCheckpoint: evaluation.currentCheckpoint,
      missingItems: evaluation.missingItems,
      riskItems: evaluation.riskItems,
      blockerItems: evaluation.blockerItems,
      completedItems: evaluation.completedItems,
      recommendedActions: evaluation.recommendedActions,
      createdTaskIds,
      updatedTaskIds,
      skippedTaskKeys,
      readinessStatusBefore: evaluation.readinessStatusBefore,
      readinessStatusAfter: evaluation.readinessStatusAfter ?? undefined,
      source,
      createdAt: now,
      updatedAt: now,
    };
    await ctx.db.insert("heartbeatChecks", checkDoc as never);

    if (evaluation.campaignId && campaignConvexId) {
      const row = await ctx.db
        .query("campaigns")
        .withIndex("by_campaign_id", (q) => q.eq("campaignId", evaluation.campaignId as string))
        .unique();
      if (row?._id) {
        const patch: Record<string, unknown> = {
          heartbeatLastCheckedAt: now,
          heartbeatSummary: evaluation.summary,
          heartbeatStatus: evaluation.campaignHeartbeatStatus,
          readinessLastCheckedAt: now,
          updatedAt: now,
        };
        if (evaluation.readinessStatusAfter) {
          patch.readinessStatus = evaluation.readinessStatusAfter;
          patch.readinessReasons = evaluation.readinessReasons;
        }
        await ctx.db.patch(row._id, patch as never);
      }
    }

    return {
      checkId: evaluation.checkId,
      campaignId: evaluation.campaignId,
      campaignName: evaluation.campaignName,
      checkDate: evaluation.checkDate,
      weekday: evaluation.weekday,
      checkType: evaluation.checkType,
      status: evaluation.status,
      currentCheckpoint: evaluation.currentCheckpoint,
      summary: evaluation.summary,
      completedItems: evaluation.completedItems,
      missingItems: evaluation.missingItems,
      riskItems: evaluation.riskItems,
      blockerItems: evaluation.blockerItems,
      recommendedActions: evaluation.recommendedActions,
      createdTaskIds,
      updatedTaskIds,
      skippedTaskKeys,
      readinessStatusBefore: evaluation.readinessStatusBefore,
      readinessStatusAfter: evaluation.readinessStatusAfter,
      additionalLaunchPacketsNote: evaluation.additionalLaunchPacketsNote,
    };
  },
});
