import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const riskLevel = v.union(v.literal("green"), v.literal("yellow"), v.literal("red"));
const approvalOwner = v.union(v.literal("bari"), v.literal("blue"), v.literal("internal"), v.literal("none"));
const approvalStatus = v.union(v.literal("pending"), v.literal("approved"), v.literal("approved_with_changes"), v.literal("changes_requested"), v.literal("rejected"), v.literal("blocked"));
const reviewQueue = v.union(v.literal("bari"), v.literal("blue"), v.literal("internal"));
const runtimeStatus = v.union(
  v.literal("idle"),
  v.literal("ready"),
  v.literal("running"),
  v.literal("human_pause"),
  v.literal("pending"),
  v.literal("blocked"),
  v.literal("complete"),
  v.literal("error"),
);
const campaignStatus = v.union(
  v.literal("intake_draft"),
  v.literal("agent_drafting"),
  v.literal("needs_internal_review"),
  v.literal("needs_bari_review"),
  v.literal("needs_blue_review"),
  v.literal("blocked"),
  v.literal("approved"),
  v.literal("ready_for_keap"),
  v.literal("scheduled"),
  v.literal("sent"),
  v.literal("reporting"),
  v.literal("learning_complete"),
  v.literal("archived"),
);
const todayTaskPriority = v.union(v.literal("green"), v.literal("amber"), v.literal("red"), v.literal("blue"), v.literal("gray"));
const todayTaskStatus = v.union(v.literal("current"), v.literal("completed"));
const todayTaskDestinationMode = v.union(
  v.literal("campaign"),
  v.literal("review"),
  v.literal("library"),
  v.literal("intelligence"),
  v.literal("operations"),
);

export default defineSchema({
  users: defineTable({
    clerkUserId: v.optional(v.string()),
    name: v.string(),
    email: v.string(),
    roles: v.array(v.string()),
    avatarInitials: v.string(),
  }).index("by_email", ["email"]).index("by_clerk_user_id", ["clerkUserId"]),

  campaigns: defineTable({
    campaignId: v.string(),
    name: v.string(),
    type: v.string(),
    goal: v.string(),
    channels: v.array(v.string()),
    audience: v.string(),
    audienceId: v.optional(v.string()),
    offer: v.string(),
    offerId: v.optional(v.string()),
    primaryCta: v.optional(v.string()),
    sendWindow: v.optional(v.string()),
    successMetric: v.optional(v.string()),
    allowedClaims: v.array(v.string()),
    knownExclusions: v.array(v.string()),
    sourceMapping: v.optional(v.string()),
    keapTagMapping: v.optional(v.string()),
    ownerId: v.optional(v.string()),
    ownerName: v.string(),
    stage: v.string(),
    status: campaignStatus,
    riskLevel,
    pendingApprovals: v.array(approvalOwner),
    bariApprovalRequired: v.boolean(),
    blueApprovalRequired: v.boolean(),
    internalApprovalRequired: v.boolean(),
    bariApprovalStatus: v.optional(approvalStatus),
    blueApprovalStatus: v.optional(approvalStatus),
    internalApprovalStatus: v.optional(approvalStatus),
    copyStatus: v.optional(v.string()),
    keapPrepStatus: v.optional(v.string()),
    responseStatus: v.optional(v.string()),
    learningStatus: v.optional(v.string()),
    nextAction: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
    lastActivityAt: v.optional(v.number()),
    sortOrder: v.number(),
    archived: v.optional(v.boolean()),
    notes: v.optional(v.string()),
  }).index("by_status", ["status"]).index("by_campaign_id", ["campaignId"]).index("by_sort_order", ["sortOrder"]),

  todayTasks: defineTable({
    taskId: v.string(),
    title: v.string(),
    context: v.string(),
    category: v.string(),
    priority: todayTaskPriority,
    sourceRoute: v.string(),
    sourceLabel: v.string(),
    destinationMode: todayTaskDestinationMode,
    status: todayTaskStatus,
    createdAt: v.number(),
    completedAt: v.optional(v.number()),
    sortOrder: v.number(),
    updatedAt: v.number(),
  }).index("by_task_id", ["taskId"]).index("by_status", ["status"]).index("by_sort_order", ["sortOrder"]),

  approvalItems: defineTable({
    approvalId: v.string(),
    type: v.string(),
    owner: reviewQueue,
    queue: reviewQueue,
    linkedCampaignId: v.optional(v.string()),
    linkedCampaignName: v.string(),
    title: v.string(),
    description: v.string(),
    context: v.optional(v.string()),
    actionNeeded: v.string(),
    status: approvalStatus,
    riskLevel,
    recommendedDecision: v.string(),
    selectedSignoff: v.optional(v.string()),
    subjectLine: v.optional(v.string()),
    previewText: v.optional(v.string()),
    bodyText: v.optional(v.string()),
    editedSubjectLine: v.optional(v.string()),
    editedPreviewText: v.optional(v.string()),
    editedBodyText: v.optional(v.string()),
    notes: v.optional(v.string()),
    decisionNotes: v.optional(v.string()),
    requestedChanges: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
    decidedAt: v.optional(v.number()),
    decidedBy: v.optional(v.string()),
    sortOrder: v.number(),
  }).index("by_owner_status", ["owner", "status"]).index("by_approval_id", ["approvalId"]).index("by_queue_status", ["queue", "status"]).index("by_sort_order", ["sortOrder"]),

  approvalEvents: defineTable({
    eventId: v.string(),
    approvalId: v.string(),
    decision: v.union(v.literal("approved"), v.literal("approved_with_changes"), v.literal("changes_requested"), v.literal("rejected")),
    note: v.optional(v.string()),
    actor: v.string(),
    createdAt: v.number(),
    snapshotJson: v.optional(v.string()),
  }).index("by_approval_id", ["approvalId"]).index("by_event_id", ["eventId"]),

  libraryItems: defineTable({
    recordId: v.string(),
    type: v.union(v.literal("offer"), v.literal("lead_magnet"), v.literal("email"), v.literal("voice_rule"), v.literal("signoff"), v.literal("audience"), v.literal("compliance_rule"), v.literal("learning")),
    name: v.string(),
    status: v.string(),
    summary: v.string(),
    tags: v.array(v.string()),
    riskLevel: v.optional(riskLevel),
    payload: v.optional(v.any()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_type", ["type"]).index("by_record_id", ["recordId"]),

  agentConfigs: defineTable({
    agentId: v.string(),
    displayName: v.string(),
    shortDescription: v.string(),
    workflowOrder: v.number(),
    category: v.string(),
    enabled: v.boolean(),
    systemPrompt: v.string(),
    taskPromptTemplate: v.string(),
    styleGuidance: v.optional(v.string()),
    requiredContextSources: v.array(v.string()),
    exampleReferences: v.optional(v.array(v.string())),
    preferredProvider: v.union(v.literal("openai"), v.literal("anthropic"), v.literal("manual"), v.literal("demo")),
    preferredModel: v.string(),
    temperature: v.number(),
    maxTokens: v.number(),
    structuredOutputRequired: v.boolean(),
    inputSchemaJson: v.string(),
    outputSchemaJson: v.string(),
    requiredInputs: v.array(v.string()),
    optionalInputs: v.array(v.string()),
    requiredOutputs: v.array(v.string()),
    escalationMarkers: v.array(v.string()),
    confidenceField: v.optional(v.string()),
    riskField: v.optional(v.string()),
    activeRules: v.array(v.string()),
    blockingRules: v.array(v.string()),
    warningRules: v.array(v.string()),
    allowedActions: v.array(v.string()),
    disallowedActions: v.array(v.string()),
    humanApprovalRequired: v.boolean(),
    canCreateApprovalItems: v.boolean(),
    canModifyCopy: v.boolean(),
    canReadLibraries: v.boolean(),
    canTriggerIntegrations: v.boolean(),
    nextAgentIds: v.array(v.string()),
    fallbackAgentId: v.optional(v.string()),
    blockedRoute: v.optional(v.string()),
    humanPauseRoute: v.optional(v.string()),
    handoffConditions: v.array(v.string()),
    retryPolicy: v.optional(v.string()),
    maxRetries: v.number(),
    configVersion: v.number(),
    lastEditedBy: v.optional(v.string()),
    lastEditedAt: v.number(),
    notes: v.optional(v.string()),
    updatedAt: v.number(),
    updatedBy: v.optional(v.string()),
  }).index("by_agent_id", ["agentId"]).index("by_workflow_order", ["workflowOrder"]),

  agentRuntimeStates: defineTable({
    agentId: v.string(),
    status: runtimeStatus,
    isRunning: v.boolean(),
    currentTaskLabel: v.optional(v.string()),
    currentTaskDetail: v.optional(v.string()),
    lastStartedAt: v.optional(v.number()),
    lastFinishedAt: v.optional(v.number()),
    lastRunId: v.optional(v.string()),
    lastError: v.optional(v.string()),
    lastOutputSummary: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_agent_id", ["agentId"]),

  agentRuns: defineTable({
    runId: v.string(),
    campaignId: v.optional(v.string()),
    agentId: v.string(),
    status: runtimeStatus,
    inputSnapshot: v.optional(v.string()),
    outputSummary: v.optional(v.string()),
    outputJson: v.optional(v.string()),
    startedAt: v.number(),
    finishedAt: v.optional(v.number()),
    error: v.optional(v.string()),
  }).index("by_campaign", ["campaignId"]).index("by_agent_id", ["agentId"]).index("by_run_id", ["runId"]),

  agentRunSteps: defineTable({
    runId: v.id("agentRuns"),
    agentName: v.string(),
    status: v.string(),
    riskLevel,
    confidence: v.number(),
    summary: v.string(),
    approvalRequired: v.boolean(),
    approvalOwner,
    structuredOutputs: v.any(),
  }).index("by_run", ["runId"]),

  langGraphNodes: defineTable({
    runId: v.optional(v.id("agentRuns")),
    label: v.string(),
    status: v.union(v.literal("complete"), v.literal("pending"), v.literal("blocked"), v.literal("human_pause")),
    next: v.array(v.string()),
    inputSnapshot: v.optional(v.any()),
    outputSnapshot: v.optional(v.any()),
  }).index("by_run", ["runId"]),

  integrationConnections: defineTable({
    integrationId: v.string(),
    name: v.string(),
    provider: v.string(),
    category: v.string(),
    purpose: v.string(),
    description: v.string(),
    status: v.union(v.literal("connected"), v.literal("disconnected"), v.literal("missing_credentials"), v.literal("manual_mode"), v.literal("error"), v.literal("demo_fallback"), v.literal("not_configured")),
    statusLabel: v.string(),
    envKeys: v.array(v.string()),
    configuredEnvVars: v.optional(v.array(v.string())),
    missingEnvVars: v.optional(v.array(v.string())),
    fallback: v.string(),
    lastCheckAt: v.optional(v.number()),
    lastCheckResult: v.optional(v.string()),
    setupNotes: v.optional(v.string()),
    setupInstructions: v.optional(v.string()),
    healthSummary: v.optional(v.string()),
    enabled: v.boolean(),
    sortOrder: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
    lastSync: v.optional(v.number()),
    notes: v.optional(v.string()),
  }).index("by_status", ["status"]).index("by_integration_id", ["integrationId"]).index("by_sort_order", ["sortOrder"]),

  keapSyncJobs: defineTable({
    jobId: v.string(),
    campaignId: v.optional(v.string()),
    campaignName: v.string(),
    status: v.union(
      v.literal("draft"),
      v.literal("ready_for_manual_export"),
      v.literal("exported_manually"),
      v.literal("error"),
    ),
    action: v.string(),
    payloadSummary: v.string(),
    payloadJson: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
    completedAt: v.optional(v.number()),
    error: v.optional(v.string()),
  }).index("by_job_id", ["jobId"]).index("by_campaign_id", ["campaignId"]).index("by_status", ["status"]),

  responseClassifications: defineTable({
    responseId: v.string(),
    title: v.string(),
    classification: v.string(),
    status: v.string(),
    sentiment: v.union(v.literal("positive"), v.literal("neutral"), v.literal("negative")),
    urgency: v.union(v.literal("low"), v.literal("medium"), v.literal("high")),
    summary: v.string(),
    originalMessage: v.optional(v.string()),
    senderName: v.optional(v.string()),
    senderEmail: v.optional(v.string()),
    receivedAt: v.number(),
    campaignId: v.optional(v.string()),
    campaignName: v.optional(v.string()),
    matchConfidence: v.optional(v.number()),
    recommendedAction: v.string(),
    suggestedReply: v.optional(v.string()),
    suggestedReplyStatus: v.optional(v.string()),
    noAutoSend: v.boolean(),
    assignedTo: v.optional(v.string()),
    source: v.optional(v.string()),
    sourceMessageId: v.optional(v.string()),
    helpdeskThreadId: v.optional(v.string()),
    tags: v.array(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
    resolvedAt: v.optional(v.number()),
    resolvedBy: v.optional(v.string()),
    notes: v.optional(v.string()),
    sortOrder: v.number(),
  }).index("by_campaign", ["campaignId"]).index("by_response_id", ["responseId"]).index("by_sort_order", ["sortOrder"]),

  performanceSnapshots: defineTable({
    campaignId: v.id("campaigns"),
    sent: v.number(),
    delivered: v.number(),
    openRate: v.number(),
    clickRate: v.number(),
    replies: v.number(),
    conversions: v.number(),
    summary: v.string(),
  }).index("by_campaign", ["campaignId"]),

  learningInsights: defineTable({
    recordId: v.string(),
    source: v.string(),
    status: v.union(v.literal("candidate"), v.literal("approved"), v.literal("rejected"), v.literal("archived")),
    title: v.string(),
    summary: v.string(),
    confidence: v.number(),
    payload: v.optional(v.any()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_status", ["status"]).index("by_record_id", ["recordId"]),

  auditLogs: defineTable({
    actor: v.string(),
    action: v.string(),
    target: v.string(),
    createdAt: v.number(),
  }).index("by_created_at", ["createdAt"]),
});
