import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const riskLevel = v.union(v.literal("green"), v.literal("yellow"), v.literal("red"));
const approvalOwner = v.union(v.literal("bari"), v.literal("blue"), v.literal("internal"), v.literal("none"));
const approvalStatus = v.union(v.literal("pending"), v.literal("approved"), v.literal("approved_with_changes"), v.literal("changes_requested"), v.literal("rejected"), v.literal("blocked"));
const reviewQueue = v.union(v.literal("bari"), v.literal("blue"), v.literal("internal"));
const runtimeStatus = v.union(
  v.literal("idle"),
  v.literal("ready"),
  v.literal("running"),
  v.literal("human_pause"),
  v.literal("pending"),
  v.literal("blocked"),
  v.literal("complete"),
  v.literal("error"),
);
const campaignStatus = v.union(
  v.literal("intake_draft"),
  v.literal("agent_drafting"),
  v.literal("needs_internal_review"),
  v.literal("needs_bari_review"),
  v.literal("needs_blue_review"),
  v.literal("blocked"),
  v.literal("approved"),
  v.literal("ready_for_keap"),
  v.literal("scheduled"),
  v.literal("sent"),
  v.literal("reporting"),
  v.literal("learning_complete"),
  v.literal("archived"),
);
const todayTaskPriority = v.union(v.literal("green"), v.literal("amber"), v.literal("red"), v.literal("blue"), v.literal("gray"));
const todayTaskStatus = v.union(v.literal("current"), v.literal("completed"));
const todayTaskDestinationMode = v.union(
  v.literal("campaign"),
  v.literal("review"),
  v.literal("library"),
  v.literal("intelligence"),
  v.literal("operations"),
);

export default defineSchema({
  users: defineTable({
    clerkUserId: v.optional(v.string()),
    name: v.string(),
    email: v.string(),
    roles: v.array(v.string()),
    avatarInitials: v.string(),
  }).index("by_email", ["email"]).index("by_clerk_user_id", ["clerkUserId"]),

  campaigns: defineTable({
    campaignId: v.string(),
    name: v.string(),
    type: v.string(),
    goal: v.string(),
    channels: v.array(v.string()),
    audience: v.string(),
    audienceId: v.optional(v.string()),
    offer: v.string(),
    offerId: v.optional(v.string()),
    primaryCta: v.optional(v.string()),
    sendWindow: v.optional(v.string()),
    successMetric: v.optional(v.string()),
    allowedClaims: v.array(v.string()),
    knownExclusions: v.array(v.string()),
    sourceMapping: v.optional(v.string()),
    keapTagMapping: v.optional(v.string()),
    ownerId: v.optional(v.string()),
    ownerName: v.string(),
    stage: v.string(),
    status: campaignStatus,
    riskLevel,
    pendingApprovals: v.array(approvalOwner),
    bariApprovalRequired: v.boolean(),
    blueApprovalRequired: v.boolean(),
    internalApprovalRequired: v.boolean(),
    bariApprovalStatus: v.optional(approvalStatus),
    blueApprovalStatus: v.optional(approvalStatus),
    internalApprovalStatus: v.optional(approvalStatus),
    copyStatus: v.optional(v.string()),
    keapPrepStatus: v.optional(v.string()),
    responseStatus: v.optional(v.string()),
    learningStatus: v.optional(v.string()),
    nextAction: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
    lastActivityAt: v.optional(v.number()),
    sortOrder: v.number(),
    archived: v.optional(v.boolean()),
    notes: v.optional(v.string()),

    /** Weekly Launch Packet (Section 2) — all optional for backward compatibility */
    campaignKind: v.optional(v.string()),
    launchType: v.optional(v.string()),
    publishDate: v.optional(v.string()),
    prepWeekStart: v.optional(v.string()),
    readinessStatus: v.optional(v.string()),
    sourceProductionAssetId: v.optional(v.string()),
    sourceProductionAssetTitle: v.optional(v.string()),
    sourceProductionAssetUrl: v.optional(v.string()),
    frameIoUrl: v.optional(v.string()),
    muxPlaybackId: v.optional(v.string()),
    transcriptStatus: v.optional(v.string()),
    thumbnailStatus: v.optional(v.string()),
    assetReadinessStatus: v.optional(v.string()),
    relatedShortsNotes: v.optional(v.string()),
    productionNotes: v.optional(v.string()),
    campaignAngle: v.optional(v.string()),
    primaryAudience: v.optional(v.string()),
    youtubeTitle: v.optional(v.string()),
    youtubeDescription: v.optional(v.string()),
    youtubePinnedComment: v.optional(v.string()),
    youtubeScheduledUrl: v.optional(v.string()),
    youtubeScheduledAt: v.optional(v.string()),
    youtubeStatus: v.optional(v.string()),
    youtubeNotes: v.optional(v.string()),
    emailBriefStatus: v.optional(v.string()),
    emailBriefBody: v.optional(v.string()),
    emailBriefSentAt: v.optional(v.string()),
    emailBriefConfirmedAt: v.optional(v.string()),
    emailCtaLink: v.optional(v.string()),
    emailSequenceNotes: v.optional(v.string()),
    emailSubjectIdeas: v.optional(v.string()),
    emailHandoffNotes: v.optional(v.string()),
    creativeOwner: v.optional(v.string()),
    creativeBriefStatus: v.optional(v.string()),
    creativeBriefBody: v.optional(v.string()),
    creativeBriefSentAt: v.optional(v.string()),
    creativeBriefConfirmedAt: v.optional(v.string()),
    shortsStatus: v.optional(v.string()),
    shortFormDeliverablesRequested: v.optional(v.string()),
    shortFormDeliverablesReceived: v.optional(v.string()),
    creativeNotes: v.optional(v.string()),
    socialCopyStatus: v.optional(v.string()),
    rolloutCadenceStatus: v.optional(v.string()),
    metaCaption: v.optional(v.string()),
    metaStatus: v.optional(v.string()),
    facebookCaption: v.optional(v.string()),
    facebookStatus: v.optional(v.string()),
    metaAdsNotes: v.optional(v.string()),
    metaPerformanceNotes: v.optional(v.string()),
    instagramCaption: v.optional(v.string()),
    instagramStatus: v.optional(v.string()),
    tiktokCaption: v.optional(v.string()),
    tiktokStatus: v.optional(v.string()),
    xPost: v.optional(v.string()),
    xStatus: v.optional(v.string()),
    pinterestTitle: v.optional(v.string()),
    pinterestDescription: v.optional(v.string()),
    pinterestStatus: v.optional(v.string()),
    youtubeShortsCaption: v.optional(v.string()),
    youtubeShortsStatus: v.optional(v.string()),
    memeEngagementIdeas: v.optional(v.string()),
    rolloutNotes: v.optional(v.string()),
    heartbeatStatus: v.optional(v.string()),
    heartbeatLastCheckedAt: v.optional(v.number()),
    heartbeatSummary: v.optional(v.string()),
    blockers: v.optional(v.array(v.string())),
    internalNotes: v.optional(v.string()),
    riskNotes: v.optional(v.string()),
    performanceStatus: v.optional(v.string()),
    performanceNotes: v.optional(v.string()),
    learningNotes: v.optional(v.string()),
    bestHook: v.optional(v.string()),
    bestPlatform: v.optional(v.string()),
    registrationImpactNotes: v.optional(v.string()),
    readinessLastCheckedAt: v.optional(v.number()),
    readinessReasons: v.optional(v.array(v.string())),
    lastCopyRunId: v.optional(v.string()),
    lastCopyRunAt: v.optional(v.number()),
    copyIntelligenceStatus: v.optional(v.string()),
    /** Trend Intelligence (Section 7) — optional links from packet to trend signals */
    linkedTrendIds: v.optional(v.array(v.string())),
    trendNotes: v.optional(v.string()),
    trendAdaptationStatus: v.optional(v.string()),

    /** Performance Intelligence (Section 8) — optional denormalized rollups */
    performanceSummary: v.optional(v.string()),
    lastPerformanceReviewId: v.optional(v.string()),
    lastPerformanceSnapshotAt: v.optional(v.number()),
  }).index("by_status", ["status"]).index("by_campaign_id", ["campaignId"]).index("by_sort_order", ["sortOrder"]),

  todayTasks: defineTable({
    taskId: v.string(),
    title: v.string(),
    context: v.string(),
    category: v.string(),
    priority: todayTaskPriority,
    sourceRoute: v.string(),
    sourceLabel: v.string(),
    destinationMode: todayTaskDestinationMode,
    status: todayTaskStatus,
    createdAt: v.number(),
    completedAt: v.optional(v.number()),
    sortOrder: v.number(),
    updatedAt: v.number(),
    /** Campaign Heartbeat (Section 3) — optional for legacy rows */
    dedupeKey: v.optional(v.string()),
    sourceType: v.optional(v.string()),
    campaignId: v.optional(v.string()),
    heartbeatCheckId: v.optional(v.string()),
    ownerLabel: v.optional(v.string()),
    ownerType: v.optional(v.string()),
    dueDate: v.optional(v.string()),
    dueDay: v.optional(v.string()),
    taskRiskLevel: v.optional(v.string()),
    externalDependency: v.optional(v.string()),
    destinationRoute: v.optional(v.string()),
    autoGenerated: v.optional(v.boolean()),
    generatedBy: v.optional(v.string()),
    taskCategory: v.optional(v.string()),
  })
    .index("by_task_id", ["taskId"])
    .index("by_status", ["status"])
    .index("by_sort_order", ["sortOrder"])
    .index("by_dedupe_key", ["dedupeKey"]),

  heartbeatChecks: defineTable({
    checkId: v.string(),
    campaignId: v.optional(v.string()),
    campaignConvexId: v.optional(v.id("campaigns")),
    campaignName: v.string(),
    checkDate: v.string(),
    weekday: v.string(),
    checkType: v.string(),
    status: v.string(),
    summary: v.string(),
    currentCheckpoint: v.string(),
    missingItems: v.array(v.string()),
    riskItems: v.array(v.string()),
    blockerItems: v.array(v.string()),
    completedItems: v.array(v.string()),
    recommendedActions: v.array(v.string()),
    createdTaskIds: v.array(v.string()),
    updatedTaskIds: v.array(v.string()),
    skippedTaskKeys: v.array(v.string()),
    readinessStatusBefore: v.optional(v.string()),
    readinessStatusAfter: v.optional(v.string()),
    source: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_check_id", ["checkId"])
    .index("by_campaign_id", ["campaignId"])
    .index("by_created_at", ["createdAt"]),

  approvalItems: defineTable({
    approvalId: v.string(),
    type: v.string(),
    owner: reviewQueue,
    queue: reviewQueue,
    linkedCampaignId: v.optional(v.string()),
    linkedCampaignName: v.string(),
    title: v.string(),
    description: v.string(),
    context: v.optional(v.string()),
    actionNeeded: v.string(),
    status: approvalStatus,
    riskLevel,
    recommendedDecision: v.string(),
    selectedSignoff: v.optional(v.string()),
    subjectLine: v.optional(v.string()),
    previewText: v.optional(v.string()),
    bodyText: v.optional(v.string()),
    editedSubjectLine: v.optional(v.string()),
    editedPreviewText: v.optional(v.string()),
    editedBodyText: v.optional(v.string()),
    notes: v.optional(v.string()),
    decisionNotes: v.optional(v.string()),
    requestedChanges: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
    decidedAt: v.optional(v.number()),
    decidedBy: v.optional(v.string()),
    sortOrder: v.number(),
  }).index("by_owner_status", ["owner", "status"]).index("by_approval_id", ["approvalId"]).index("by_queue_status", ["queue", "status"]).index("by_sort_order", ["sortOrder"]),

  approvalEvents: defineTable({
    eventId: v.string(),
    approvalId: v.string(),
    decision: v.union(v.literal("approved"), v.literal("approved_with_changes"), v.literal("changes_requested"), v.literal("rejected")),
    note: v.optional(v.string()),
    actor: v.string(),
    createdAt: v.number(),
    snapshotJson: v.optional(v.string()),
  }).index("by_approval_id", ["approvalId"]).index("by_event_id", ["eventId"]),

  libraryItems: defineTable({
    recordId: v.string(),
    /** Legacy union values plus extended copy/knowledge types (stored as string). */
    type: v.string(),
    name: v.string(),
    status: v.string(),
    summary: v.string(),
    tags: v.array(v.string()),
    riskLevel: v.optional(riskLevel),
    payload: v.optional(v.any()),
    createdAt: v.number(),
    updatedAt: v.number(),
    bucket: v.optional(v.string()),
    title: v.optional(v.string()),
    sourceSystem: v.optional(v.string()),
    sourceUri: v.optional(v.string()),
    sourceFileId: v.optional(v.string()),
    sourceFolderId: v.optional(v.string()),
    sourceLabel: v.optional(v.string()),
    contentHash: v.optional(v.string()),
    linkedCampaignIds: v.optional(v.array(v.string())),
    linkedAssetIds: v.optional(v.array(v.string())),
    usageRights: v.optional(v.string()),
    confidence: v.optional(v.number()),
    priority: v.optional(v.string()),
    reviewOwner: v.optional(v.string()),
    approvedBy: v.optional(v.string()),
    approvedAt: v.optional(v.number()),
    archivedAt: v.optional(v.number()),
    driveFileId: v.optional(v.string()),
    driveFolderId: v.optional(v.string()),
    driveFileName: v.optional(v.string()),
    driveMimeType: v.optional(v.string()),
    driveWebUrl: v.optional(v.string()),
    drivePath: v.optional(v.string()),
    driveLastModifiedAt: v.optional(v.number()),
    driveLastSyncedAt: v.optional(v.number()),
    driveSyncStatus: v.optional(v.string()),
    driveSyncNotes: v.optional(v.string()),
    obsidianPath: v.optional(v.string()),
    obsidianNoteTitle: v.optional(v.string()),
    obsidianSyncStatus: v.optional(v.string()),
    obsidianLastSyncedAt: v.optional(v.number()),
    obsidianLastExportedAt: v.optional(v.number()),
    obsidianLastPreviewedAt: v.optional(v.number()),
    obsidianFrontmatterJson: v.optional(v.string()),
    obsidianBacklinks: v.optional(v.array(v.string())),
    obsidianTags: v.optional(v.array(v.string())),
    obsidianSyncNotes: v.optional(v.string()),
    lastIndexedAt: v.optional(v.number()),
    lastExportedAt: v.optional(v.number()),
    syncStatus: v.optional(v.string()),
    syncNotes: v.optional(v.string()),
  })
    .index("by_type", ["type"])
    .index("by_record_id", ["recordId"])
    .index("by_bucket", ["bucket"]),

  librarySyncJobs: defineTable({
    syncJobId: v.string(),
    sourceSystem: v.string(),
    targetSystem: v.optional(v.string()),
    direction: v.string(),
    mode: v.optional(v.string()),
    status: v.string(),
    jobType: v.optional(v.string()),
    sourcePath: v.optional(v.string()),
    targetPath: v.optional(v.string()),
    targetBucket: v.optional(v.string()),
    recordsScanned: v.optional(v.number()),
    recordsCreated: v.optional(v.number()),
    recordsUpdated: v.optional(v.number()),
    recordsSkipped: v.optional(v.number()),
    recordsExported: v.optional(v.number()),
    recordsErrored: v.optional(v.number()),
    errorMessage: v.optional(v.string()),
    summary: v.optional(v.string()),
    startedAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
    createdBy: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
    rawJson: v.optional(v.string()),
    libraryRecordId: v.optional(v.string()),
  })
    .index("by_sync_job_id", ["syncJobId"])
    .index("by_created_at", ["createdAt"])
    .index("by_library_record_id", ["libraryRecordId"]),

  /** Obsidian-ready Markdown previews — no vault writes in v1 */
  obsidianExportRecords: defineTable({
    exportId: v.string(),
    libraryRecordId: v.string(),
    sourceRecordTitle: v.optional(v.string()),
    obsidianPath: v.string(),
    obsidianNoteTitle: v.optional(v.string()),
    markdownBody: v.string(),
    frontmatterJson: v.optional(v.string()),
    status: v.string(),
    exportMode: v.optional(v.string()),
    contentHash: v.optional(v.string()),
    generatedAt: v.optional(v.number()),
    exportedAt: v.optional(v.number()),
    createdBy: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
    errorMessage: v.optional(v.string()),
  })
    .index("by_export_id", ["exportId"])
    .index("by_library_record_id", ["libraryRecordId"])
    .index("by_updated_at", ["updatedAt"]),

  /** Planned folder/bucket mappings — metadata only */
  knowledgeSourceMappings: defineTable({
    mappingId: v.string(),
    name: v.string(),
    sourceSystem: v.string(),
    sourcePath: v.optional(v.string()),
    sourceFolderId: v.optional(v.string()),
    targetSystem: v.string(),
    targetBucket: v.optional(v.string()),
    targetPath: v.optional(v.string()),
    status: v.string(),
    mode: v.string(),
    rulesJson: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_mapping_id", ["mappingId"])
    .index("by_updated_at", ["updatedAt"]),

  agentConfigs: defineTable({
    agentId: v.string(),
    displayName: v.string(),
    shortDescription: v.string(),
    workflowOrder: v.number(),
    category: v.string(),
    enabled: v.boolean(),
    systemPrompt: v.string(),
    taskPromptTemplate: v.string(),
    styleGuidance: v.optional(v.string()),
    requiredContextSources: v.array(v.string()),
    exampleReferences: v.optional(v.array(v.string())),
    preferredProvider: v.union(v.literal("openai"), v.literal("anthropic"), v.literal("manual"), v.literal("demo")),
    preferredModel: v.string(),
    temperature: v.number(),
    maxTokens: v.number(),
    structuredOutputRequired: v.boolean(),
    inputSchemaJson: v.string(),
    outputSchemaJson: v.string(),
    requiredInputs: v.array(v.string()),
    optionalInputs: v.array(v.string()),
    requiredOutputs: v.array(v.string()),
    escalationMarkers: v.array(v.string()),
    confidenceField: v.optional(v.string()),
    riskField: v.optional(v.string()),
    activeRules: v.array(v.string()),
    blockingRules: v.array(v.string()),
    warningRules: v.array(v.string()),
    allowedActions: v.array(v.string()),
    disallowedActions: v.array(v.string()),
    humanApprovalRequired: v.boolean(),
    canCreateApprovalItems: v.boolean(),
    canModifyCopy: v.boolean(),
    canReadLibraries: v.boolean(),
    canTriggerIntegrations: v.boolean(),
    nextAgentIds: v.array(v.string()),
    fallbackAgentId: v.optional(v.string()),
    blockedRoute: v.optional(v.string()),
    humanPauseRoute: v.optional(v.string()),
    handoffConditions: v.array(v.string()),
    retryPolicy: v.optional(v.string()),
    maxRetries: v.number(),
    configVersion: v.number(),
    lastEditedBy: v.optional(v.string()),
    lastEditedAt: v.number(),
    notes: v.optional(v.string()),
    updatedAt: v.number(),
    updatedBy: v.optional(v.string()),
    /** Copy Intelligence / grouping (Section 6) */
    groupId: v.optional(v.string()),
    agentRole: v.optional(v.string()),
    inputSources: v.optional(v.array(v.string())),
    outputTargets: v.optional(v.array(v.string())),
    safetyMode: v.optional(v.string()),
    isCore: v.optional(v.boolean()),
  }).index("by_agent_id", ["agentId"]).index("by_workflow_order", ["workflowOrder"]).index("by_group_id", ["groupId"]),

  agentRuntimeStates: defineTable({
    agentId: v.string(),
    status: runtimeStatus,
    isRunning: v.boolean(),
    currentTaskLabel: v.optional(v.string()),
    currentTaskDetail: v.optional(v.string()),
    lastStartedAt: v.optional(v.number()),
    lastFinishedAt: v.optional(v.number()),
    lastRunId: v.optional(v.string()),
    lastError: v.optional(v.string()),
    lastOutputSummary: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_agent_id", ["agentId"]),

  agentRuns: defineTable({
    runId: v.string(),
    campaignId: v.optional(v.string()),
    agentId: v.string(),
    status: runtimeStatus,
    inputSnapshot: v.optional(v.string()),
    outputSummary: v.optional(v.string()),
    outputJson: v.optional(v.string()),
    startedAt: v.number(),
    finishedAt: v.optional(v.number()),
    error: v.optional(v.string()),
    groupId: v.optional(v.string()),
    runType: v.optional(v.string()),
    outputTarget: v.optional(v.string()),
    safetyMode: v.optional(v.string()),
    appliedToCampaign: v.optional(v.boolean()),
    appliedAt: v.optional(v.number()),
    reviewRequired: v.optional(v.boolean()),
    createdBy: v.optional(v.string()),
  }).index("by_campaign", ["campaignId"]).index("by_agent_id", ["agentId"]).index("by_run_id", ["runId"]).index("by_group_id", ["groupId"]),

  agentRunSteps: defineTable({
    runId: v.id("agentRuns"),
    agentName: v.string(),
    status: v.string(),
    riskLevel,
    confidence: v.number(),
    summary: v.string(),
    approvalRequired: v.boolean(),
    approvalOwner,
    structuredOutputs: v.any(),
  }).index("by_run", ["runId"]),

  langGraphNodes: defineTable({
    runId: v.optional(v.id("agentRuns")),
    label: v.string(),
    status: v.union(v.literal("complete"), v.literal("pending"), v.literal("blocked"), v.literal("human_pause")),
    next: v.array(v.string()),
    inputSnapshot: v.optional(v.any()),
    outputSnapshot: v.optional(v.any()),
  }).index("by_run", ["runId"]),

  integrationConnections: defineTable({
    integrationId: v.string(),
    name: v.string(),
    provider: v.string(),
    category: v.string(),
    purpose: v.string(),
    description: v.string(),
    status: v.union(v.literal("connected"), v.literal("disconnected"), v.literal("missing_credentials"), v.literal("manual_mode"), v.literal("error"), v.literal("demo_fallback"), v.literal("not_configured")),
    statusLabel: v.string(),
    envKeys: v.array(v.string()),
    configuredEnvVars: v.optional(v.array(v.string())),
    missingEnvVars: v.optional(v.array(v.string())),
    fallback: v.string(),
    lastCheckAt: v.optional(v.number()),
    lastCheckResult: v.optional(v.string()),
    setupNotes: v.optional(v.string()),
    setupInstructions: v.optional(v.string()),
    healthSummary: v.optional(v.string()),
    enabled: v.boolean(),
    sortOrder: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
    lastSync: v.optional(v.number()),
    notes: v.optional(v.string()),
    connectorMode: v.optional(v.string()),
    safetyLevel: v.optional(v.string()),
    plannedCapabilities: v.optional(v.array(v.string())),
    disabledCapabilities: v.optional(v.array(v.string())),
    relatedWorkflows: v.optional(v.string()),
    requiredScopes: v.optional(v.string()),
    configuredScopes: v.optional(v.string()),
    errorMessage: v.optional(v.string()),
  }).index("by_status", ["status"]).index("by_integration_id", ["integrationId"]).index("by_sort_order", ["sortOrder"]),

  keapSyncJobs: defineTable({
    jobId: v.string(),
    campaignId: v.optional(v.string()),
    campaignName: v.string(),
    status: v.union(
      v.literal("draft"),
      v.literal("ready_for_manual_export"),
      v.literal("exported_manually"),
      v.literal("error"),
    ),
    action: v.string(),
    payloadSummary: v.string(),
    payloadJson: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
    completedAt: v.optional(v.number()),
    error: v.optional(v.string()),
  }).index("by_job_id", ["jobId"]).index("by_campaign_id", ["campaignId"]).index("by_status", ["status"]),

  responseClassifications: defineTable({
    responseId: v.string(),
    title: v.string(),
    classification: v.string(),
    status: v.string(),
    sentiment: v.union(v.literal("positive"), v.literal("neutral"), v.literal("negative")),
    urgency: v.union(v.literal("low"), v.literal("medium"), v.literal("high")),
    summary: v.string(),
    originalMessage: v.optional(v.string()),
    senderName: v.optional(v.string()),
    senderEmail: v.optional(v.string()),
    receivedAt: v.number(),
    campaignId: v.optional(v.string()),
    campaignName: v.optional(v.string()),
    matchConfidence: v.optional(v.number()),
    recommendedAction: v.string(),
    suggestedReply: v.optional(v.string()),
    suggestedReplyStatus: v.optional(v.string()),
    noAutoSend: v.boolean(),
    assignedTo: v.optional(v.string()),
    source: v.optional(v.string()),
    sourceMessageId: v.optional(v.string()),
    helpdeskThreadId: v.optional(v.string()),
    tags: v.array(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
    resolvedAt: v.optional(v.number()),
    resolvedBy: v.optional(v.string()),
    notes: v.optional(v.string()),
    sortOrder: v.number(),
  }).index("by_campaign", ["campaignId"]).index("by_response_id", ["responseId"]).index("by_sort_order", ["sortOrder"]),

  /**
   * Performance Intelligence — structured metrics (manual, demo, import, or future read-only sync).
   * Required: snapshotId, platform, metricDate, sourceSystem, createdAt, updatedAt.
   */
  performanceSnapshots: defineTable({
    snapshotId: v.string(),
    campaignId: v.optional(v.string()),
    campaignName: v.optional(v.string()),
    productionAssetId: v.optional(v.string()),
    trendId: v.optional(v.string()),
    libraryRecordId: v.optional(v.string()),
    platform: v.string(),
    contentType: v.optional(v.string()),
    contentTitle: v.optional(v.string()),
    contentUrl: v.optional(v.string()),
    metricDate: v.string(),
    dateRangeStart: v.optional(v.string()),
    dateRangeEnd: v.optional(v.string()),
    sourceSystem: v.string(),
    sourceMode: v.optional(v.string()),
    metricStatus: v.optional(v.string()),
    impressions: v.optional(v.number()),
    reach: v.optional(v.number()),
    views: v.optional(v.number()),
    uniqueViews: v.optional(v.number()),
    watchTimeSeconds: v.optional(v.number()),
    averageViewDurationSeconds: v.optional(v.number()),
    completionRate: v.optional(v.number()),
    clicks: v.optional(v.number()),
    clickThroughRate: v.optional(v.number()),
    registrations: v.optional(v.number()),
    registrationRate: v.optional(v.number()),
    leads: v.optional(v.number()),
    replies: v.optional(v.number()),
    opens: v.optional(v.number()),
    openRate: v.optional(v.number()),
    emailClicks: v.optional(v.number()),
    emailClickRate: v.optional(v.number()),
    likes: v.optional(v.number()),
    comments: v.optional(v.number()),
    shares: v.optional(v.number()),
    saves: v.optional(v.number()),
    engagement: v.optional(v.number()),
    engagementRate: v.optional(v.number()),
    followersGained: v.optional(v.number()),
    spend: v.optional(v.number()),
    costPerClick: v.optional(v.number()),
    costPerRegistration: v.optional(v.number()),
    revenue: v.optional(v.number()),
    conversionValue: v.optional(v.number()),
    hookLabel: v.optional(v.string()),
    topicLabel: v.optional(v.string()),
    ctaLabel: v.optional(v.string()),
    audienceLabel: v.optional(v.string()),
    copyVariantLabel: v.optional(v.string()),
    creativeVariantLabel: v.optional(v.string()),
    campaignLabel: v.optional(v.string()),
    adSetLabel: v.optional(v.string()),
    adLabel: v.optional(v.string()),
    placementLabel: v.optional(v.string()),
    objectiveLabel: v.optional(v.string()),
    notes: v.optional(v.string()),
    insights: v.optional(v.string()),
    rawJson: v.optional(v.string()),
    importedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_snapshot_id", ["snapshotId"])
    .index("by_campaign_id", ["campaignId"])
    .index("by_metric_date", ["metricDate"])
    .index("by_updated_at", ["updatedAt"]),

  /** Human or agent-dry-run interpretation layered on top of snapshots */
  performanceReviews: defineTable({
    reviewId: v.string(),
    campaignId: v.optional(v.string()),
    campaignName: v.optional(v.string()),
    reviewType: v.string(),
    status: v.string(),
    dateRangeStart: v.optional(v.string()),
    dateRangeEnd: v.optional(v.string()),
    summary: v.optional(v.string()),
    wins: v.optional(v.array(v.string())),
    misses: v.optional(v.array(v.string())),
    patterns: v.optional(v.array(v.string())),
    recommendations: v.optional(v.array(v.string())),
    questionsToInvestigate: v.optional(v.array(v.string())),
    suggestedLearningCandidates: v.optional(v.array(v.string())),
    learningCandidateIds: v.optional(v.array(v.string())),
    relatedSnapshotIds: v.optional(v.array(v.string())),
    dryRunOutputJson: v.optional(v.string()),
    sourceMode: v.optional(v.string()),
    reviewedBy: v.optional(v.string()),
    reviewedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_review_id", ["reviewId"])
    .index("by_campaign_id", ["campaignId"])
    .index("by_updated_at", ["updatedAt"]),

  /** Section 10 — Platform / Meta insights: observations and patterns (not raw metric warehouse). */
  platformInsights: defineTable({
    insightId: v.string(),
    platform: v.string(),
    sourceSystem: v.string(),
    sourceMode: v.string(),
    insightType: v.string(),
    title: v.string(),
    summary: v.string(),
    evidence: v.optional(v.string()),
    dateRangeStart: v.optional(v.string()),
    dateRangeEnd: v.optional(v.string()),
    relatedCampaignIds: v.optional(v.array(v.string())),
    relatedSnapshotIds: v.optional(v.array(v.string())),
    relatedTrendIds: v.optional(v.array(v.string())),
    relatedLibraryItemIds: v.optional(v.array(v.string())),
    confidence: v.optional(v.number()),
    status: v.string(),
    riskLevel: v.optional(v.string()),
    recommendedActions: v.optional(v.string()),
    createdBy: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
    rawJson: v.optional(v.string()),
  })
    .index("by_insight_id", ["insightId"])
    .index("by_platform", ["platform"])
    .index("by_updated_at", ["updatedAt"]),

  learningInsights: defineTable({
    recordId: v.string(),
    source: v.string(),
    status: v.union(v.literal("candidate"), v.literal("approved"), v.literal("rejected"), v.literal("archived")),
    title: v.string(),
    summary: v.string(),
    confidence: v.number(),
    payload: v.optional(v.any()),
    createdAt: v.number(),
    updatedAt: v.number(),
    approvedAt: v.optional(v.number()),
    approvedBy: v.optional(v.string()),
    rejectedAt: v.optional(v.number()),
    rejectedBy: v.optional(v.string()),
    archivedAt: v.optional(v.number()),
    archivedBy: v.optional(v.string()),
  }).index("by_status", ["status"]).index("by_record_id", ["recordId"]),

  /** Marketing-facing Production Bridge cache — not the production source of truth. */
  productionAssets: defineTable({
    productionAssetId: v.string(),
    externalAssetId: v.optional(v.string()),
    title: v.string(),
    workingTitle: v.optional(v.string()),
    assetType: v.string(),
    status: v.string(),
    readinessStatus: v.optional(v.string()),
    productionStage: v.optional(v.string()),
    publishingStage: v.optional(v.string()),
    sourceSystem: v.string(),
    sourceUrl: v.optional(v.string()),
    productionHubUrl: v.optional(v.string()),
    frameIoUrl: v.optional(v.string()),
    frameIoProjectId: v.optional(v.string()),
    frameIoFolderId: v.optional(v.string()),
    frameIoAssetId: v.optional(v.string()),
    muxPlaybackId: v.optional(v.string()),
    muxAssetId: v.optional(v.string()),
    muxStatus: v.optional(v.string()),
    transcriptStatus: v.optional(v.string()),
    transcriptText: v.optional(v.string()),
    transcriptSummary: v.optional(v.string()),
    thumbnailStatus: v.optional(v.string()),
    thumbnailUrl: v.optional(v.string()),
    relatedAssetIds: v.optional(v.array(v.string())),
    relatedShortIds: v.optional(v.array(v.string())),
    relatedFullVideoId: v.optional(v.string()),
    shortsCount: v.optional(v.number()),
    readyShortsCount: v.optional(v.number()),
    owner: v.optional(v.string()),
    creativeOwner: v.optional(v.string()),
    notes: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
    linkedCampaignIds: v.optional(v.array(v.string())),
    rawJson: v.optional(v.string()),
    lastSyncedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_production_asset_id", ["productionAssetId"])
    .index("by_updated_at", ["updatedAt"]),

  /** Manual import / future read-only sync job log (placeholders OK). */
  productionBridgeSyncJobs: defineTable({
    syncJobId: v.string(),
    sourceSystem: v.string(),
    direction: v.string(),
    status: v.string(),
    mode: v.string(),
    recordsScanned: v.optional(v.number()),
    recordsCreated: v.optional(v.number()),
    recordsUpdated: v.optional(v.number()),
    recordsSkipped: v.optional(v.number()),
    errorMessage: v.optional(v.string()),
    startedAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_sync_job_id", ["syncJobId"]),

  /** Section 7 — Trend Intelligence: manual / future-connector trend observations (human-controlled). */
  trendSignals: defineTable({
    trendId: v.string(),
    title: v.string(),
    platform: v.string(),
    status: v.string(),
    sourceSystem: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
    summary: v.optional(v.string()),
    trendType: v.optional(v.string()),
    sourceUrl: v.optional(v.string()),
    sourceLabel: v.optional(v.string()),
    observedAt: v.optional(v.number()),
    expiresAt: v.optional(v.number()),
    timeliness: v.optional(v.string()),
    relevanceScore: v.optional(v.number()),
    brandFitScore: v.optional(v.number()),
    audienceFitScore: v.optional(v.number()),
    riskScore: v.optional(v.number()),
    effortLevel: v.optional(v.string()),
    confidence: v.optional(v.number()),
    tags: v.optional(v.array(v.string())),
    relatedCampaignIds: v.optional(v.array(v.string())),
    relatedLibraryItemIds: v.optional(v.array(v.string())),
    relatedProductionAssetIds: v.optional(v.array(v.string())),
    suggestedUses: v.optional(v.array(v.string())),
    adaptationIdeas: v.optional(v.array(v.string())),
    hookIdeas: v.optional(v.array(v.string())),
    captionIdeas: v.optional(v.array(v.string())),
    memeIdeas: v.optional(v.array(v.string())),
    creativeBriefNotes: v.optional(v.string()),
    platformNotes: v.optional(v.string()),
    riskNotes: v.optional(v.string()),
    approvalNotes: v.optional(v.string()),
    reviewedBy: v.optional(v.string()),
    reviewedAt: v.optional(v.number()),
    usedAt: v.optional(v.number()),
    archivedAt: v.optional(v.number()),
    performanceNotes: v.optional(v.string()),
    rawJson: v.optional(v.string()),
  })
    .index("by_trend_id", ["trendId"])
    .index("by_platform", ["platform"])
    .index("by_status", ["status"])
    .index("by_updated_at", ["updatedAt"]),

  /** Section 7 — research session log (manual / dry-run / future platform sync). */
  trendResearchRuns: defineTable({
    runId: v.string(),
    runType: v.string(),
    status: v.string(),
    sourceSystem: v.string(),
    startedAt: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
    platforms: v.optional(v.array(v.string())),
    query: v.optional(v.string()),
    summary: v.optional(v.string()),
    trendsFound: v.optional(v.number()),
    trendIdsCreated: v.optional(v.array(v.string())),
    completedAt: v.optional(v.number()),
    errorMessage: v.optional(v.string()),
    createdBy: v.optional(v.string()),
    rawJson: v.optional(v.string()),
  }).index("by_run_id", ["runId"]).index("by_started_at", ["startedAt"]),

  auditLogs: defineTable({
    actor: v.string(),
    action: v.string(),
    target: v.string(),
    createdAt: v.number(),
  }).index("by_created_at", ["createdAt"]),
});
