import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const riskLevel = v.union(v.literal("green"), v.literal("yellow"), v.literal("red"));
const approvalOwner = v.union(v.literal("bari"), v.literal("blue"), v.literal("internal"), v.literal("none"));
const approvalStatus = v.union(v.literal("pending"), v.literal("approved"), v.literal("approved_with_changes"), v.literal("changes_requested"), v.literal("rejected"), v.literal("blocked"));
const runtimeStatus = v.union(
  v.literal("idle"),
  v.literal("ready"),
  v.literal("running"),
  v.literal("human_pause"),
  v.literal("pending"),
  v.literal("blocked"),
  v.literal("complete"),
  v.literal("error"),
);
const campaignStatus = v.union(
  v.literal("intake_draft"),
  v.literal("agent_drafting"),
  v.literal("needs_internal_review"),
  v.literal("needs_bari_review"),
  v.literal("needs_blue_review"),
  v.literal("blocked"),
  v.literal("approved"),
  v.literal("ready_for_keap"),
  v.literal("scheduled"),
  v.literal("sent"),
  v.literal("reporting"),
  v.literal("learning_complete"),
  v.literal("archived"),
);

export default defineSchema({
  users: defineTable({
    clerkUserId: v.optional(v.string()),
    name: v.string(),
    email: v.string(),
    roles: v.array(v.string()),
    avatarInitials: v.string(),
  }).index("by_email", ["email"]),

  campaigns: defineTable({
    name: v.string(),
    goal: v.string(),
    channels: v.array(v.string()),
    audience: v.string(),
    offerId: v.optional(v.id("libraryItems")),
    ownerId: v.optional(v.id("users")),
    status: campaignStatus,
    riskLevel,
    pendingApprovals: v.array(approvalOwner),
    nextAction: v.string(),
    updatedAt: v.number(),
  }).index("by_status", ["status"]),

  approvalItems: defineTable({
    campaignId: v.id("campaigns"),
    owner: approvalOwner,
    title: v.string(),
    reason: v.string(),
    status: approvalStatus,
    riskLevel,
    recommendedDecision: v.string(),
    notes: v.optional(v.string()),
  }).index("by_owner_status", ["owner", "status"]),

  libraryItems: defineTable({
    type: v.union(v.literal("offer"), v.literal("lead_magnet"), v.literal("email"), v.literal("voice_rule"), v.literal("signoff"), v.literal("audience"), v.literal("compliance_rule"), v.literal("learning")),
    name: v.string(),
    status: v.string(),
    summary: v.string(),
    tags: v.array(v.string()),
    riskLevel: v.optional(riskLevel),
    payload: v.optional(v.any()),
  }).index("by_type", ["type"]),

  agentConfigs: defineTable({
    agentId: v.string(),
    displayName: v.string(),
    shortDescription: v.string(),
    workflowOrder: v.number(),
    category: v.string(),
    enabled: v.boolean(),
    systemPrompt: v.string(),
    taskPromptTemplate: v.string(),
    styleGuidance: v.optional(v.string()),
    requiredContextSources: v.array(v.string()),
    exampleReferences: v.optional(v.array(v.string())),
    preferredProvider: v.union(v.literal("openai"), v.literal("anthropic"), v.literal("manual"), v.literal("demo")),
    preferredModel: v.string(),
    temperature: v.number(),
    maxTokens: v.number(),
    structuredOutputRequired: v.boolean(),
    inputSchemaJson: v.string(),
    outputSchemaJson: v.string(),
    requiredInputs: v.array(v.string()),
    optionalInputs: v.array(v.string()),
    requiredOutputs: v.array(v.string()),
    escalationMarkers: v.array(v.string()),
    confidenceField: v.optional(v.string()),
    riskField: v.optional(v.string()),
    activeRules: v.array(v.string()),
    blockingRules: v.array(v.string()),
    warningRules: v.array(v.string()),
    allowedActions: v.array(v.string()),
    disallowedActions: v.array(v.string()),
    humanApprovalRequired: v.boolean(),
    canCreateApprovalItems: v.boolean(),
    canModifyCopy: v.boolean(),
    canReadLibraries: v.boolean(),
    canTriggerIntegrations: v.boolean(),
    nextAgentIds: v.array(v.string()),
    fallbackAgentId: v.optional(v.string()),
    blockedRoute: v.optional(v.string()),
    humanPauseRoute: v.optional(v.string()),
    handoffConditions: v.array(v.string()),
    retryPolicy: v.optional(v.string()),
    maxRetries: v.number(),
    configVersion: v.number(),
    lastEditedBy: v.optional(v.string()),
    lastEditedAt: v.number(),
    notes: v.optional(v.string()),
    updatedAt: v.number(),
    updatedBy: v.optional(v.string()),
  }).index("by_agent_id", ["agentId"]).index("by_workflow_order", ["workflowOrder"]),

  agentRuntimeStates: defineTable({
    agentId: v.string(),
    status: runtimeStatus,
    isRunning: v.boolean(),
    currentTaskLabel: v.optional(v.string()),
    currentTaskDetail: v.optional(v.string()),
    lastStartedAt: v.optional(v.number()),
    lastFinishedAt: v.optional(v.number()),
    lastRunId: v.optional(v.string()),
    lastError: v.optional(v.string()),
    lastOutputSummary: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_agent_id", ["agentId"]),

  agentRuns: defineTable({
    runId: v.string(),
    campaignId: v.optional(v.string()),
    agentId: v.string(),
    status: runtimeStatus,
    inputSnapshot: v.optional(v.string()),
    outputSummary: v.optional(v.string()),
    outputJson: v.optional(v.string()),
    startedAt: v.number(),
    finishedAt: v.optional(v.number()),
    error: v.optional(v.string()),
  }).index("by_campaign", ["campaignId"]).index("by_agent_id", ["agentId"]).index("by_run_id", ["runId"]),

  agentRunSteps: defineTable({
    runId: v.id("agentRuns"),
    agentName: v.string(),
    status: v.string(),
    riskLevel,
    confidence: v.number(),
    summary: v.string(),
    approvalRequired: v.boolean(),
    approvalOwner,
    structuredOutputs: v.any(),
  }).index("by_run", ["runId"]),

  langGraphNodes: defineTable({
    runId: v.optional(v.id("agentRuns")),
    label: v.string(),
    status: v.union(v.literal("complete"), v.literal("pending"), v.literal("blocked"), v.literal("human_pause")),
    next: v.array(v.string()),
    inputSnapshot: v.optional(v.any()),
    outputSnapshot: v.optional(v.any()),
  }).index("by_run", ["runId"]),

  integrationConnections: defineTable({
    name: v.string(),
    purpose: v.string(),
    status: v.union(v.literal("connected"), v.literal("disconnected"), v.literal("missing_credentials"), v.literal("manual_mode"), v.literal("error")),
    envKeys: v.array(v.string()),
    fallback: v.string(),
    lastSync: v.optional(v.number()),
  }).index("by_status", ["status"]),

  responseClassifications: defineTable({
    campaignId: v.optional(v.id("campaigns")),
    classification: v.string(),
    intent: v.string(),
    sentiment: v.union(v.literal("positive"), v.literal("neutral"), v.literal("negative")),
    urgency: v.union(v.literal("low"), v.literal("medium"), v.literal("high")),
    summary: v.string(),
    matchConfidence: v.number(),
  }).index("by_campaign", ["campaignId"]),

  performanceSnapshots: defineTable({
    campaignId: v.id("campaigns"),
    sent: v.number(),
    delivered: v.number(),
    openRate: v.number(),
    clickRate: v.number(),
    replies: v.number(),
    conversions: v.number(),
    summary: v.string(),
  }).index("by_campaign", ["campaignId"]),

  learningInsights: defineTable({
    source: v.string(),
    status: v.union(v.literal("candidate"), v.literal("approved"), v.literal("rejected"), v.literal("archived")),
    title: v.string(),
    summary: v.string(),
    confidence: v.number(),
  }).index("by_status", ["status"]),

  auditLogs: defineTable({
    actor: v.string(),
    action: v.string(),
    target: v.string(),
    createdAt: v.number(),
  }).index("by_created_at", ["createdAt"]),
});
