import type { AgentConfigRecord, AgentRunRecord, AgentRuntimeStateRecord } from "@/lib/domain";

const now = Date.parse("2026-04-30T16:30:00.000Z");

function prettyJson(value: unknown) {
  return JSON.stringify(value, null, 2);
}

type AgentSeed = Omit<
  AgentConfigRecord,
  "inputSchemaJson" | "outputSchemaJson" | "lastEditedAt"
> & {
  inputSchema: unknown;
  outputSchema: unknown;
};

const agentSeeds: AgentSeed[] = [
  {
    agentId: "campaign_intake",
    displayName: "Campaign Intake",
    shortDescription: "Captures the operator brief, constraints, and success definition before automated work begins.",
    workflowOrder: 1,
    category: "orchestration",
    enabled: true,
    systemPrompt: "Normalize incoming campaign requests into a stable structured brief without inventing missing facts.",
    taskPromptTemplate: "Read the submitted campaign request and produce a normalized intake package for downstream agents.",
    styleGuidance: "Be precise, operator-readable, and preserve any human-entered constraints verbatim.",
    requiredContextSources: ["campaign intake form", "operator notes"],
    exampleReferences: ["demo/intake/brief-template"],
    preferredProvider: "demo",
    preferredModel: "demo-intake-normalizer",
    temperature: 0.1,
    maxTokens: 1200,
    structuredOutputRequired: true,
    inputSchema: { campaignName: "string", goal: "string", audience: "string", offer: "string?" },
    outputSchema: { normalizedBrief: "object", missingFields: ["string"], warnings: ["string"] },
    requiredInputs: ["campaignName", "goal", "audience"],
    optionalInputs: ["offer", "sendWindow", "notes"],
    requiredOutputs: ["normalizedBrief", "missingFields"],
    escalationMarkers: ["missing critical brief fields", "conflicting goals"],
    confidenceField: "intakeConfidence",
    riskField: "briefRisk",
    activeRules: ["Preserve user-entered claims verbatim", "Do not infer approvals"],
    blockingRules: ["Cannot proceed without campaign goal", "Cannot proceed without audience"],
    warningRules: ["Missing send window", "Missing success metric"],
    allowedActions: ["normalize input", "request missing fields"],
    disallowedActions: ["draft copy", "trigger integrations"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: false,
    canTriggerIntegrations: false,
    nextAgentIds: ["strategist"],
    fallbackAgentId: "human_approval",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["brief normalized", "required inputs present"],
    retryPolicy: "retry on missing optional metadata once",
    maxRetries: 1,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Entry node for the LangGraph workflow.",
  },
  {
    agentId: "strategist",
    displayName: "Strategist",
    shortDescription: "Defines campaign angle, objective, and success criteria.",
    workflowOrder: 2,
    category: "strategy",
    enabled: true,
    systemPrompt: "Turn campaign intake into a sharp marketing strategy with objective, audience angle, and success signal.",
    taskPromptTemplate: "Given the intake brief, propose the strategic angle, objective, success metric, and risks.",
    styleGuidance: "Use concise operator language and surface strategic risk early.",
    requiredContextSources: ["campaign intake", "offer library", "audience library", "learning library"],
    exampleReferences: ["strategy/reactivation-angle", "strategy/webinar-positioning"],
    preferredProvider: "openai",
    preferredModel: "gpt-4.1",
    temperature: 0.4,
    maxTokens: 1800,
    structuredOutputRequired: true,
    inputSchema: { normalizedBrief: "object", activeOffers: ["object"], audiences: ["object"] },
    outputSchema: { objective: "string", strategicAngle: "string", successMetric: "string", risks: ["string"] },
    requiredInputs: ["normalizedBrief", "activeOffers"],
    optionalInputs: ["learningInsights", "historicalPerformance"],
    requiredOutputs: ["objective", "strategicAngle", "successMetric"],
    escalationMarkers: ["unsupported offer claim", "audience-offer mismatch"],
    confidenceField: "confidence",
    riskField: "riskLevel",
    activeRules: ["Keep strategy tied to approved offers", "State success metric explicitly"],
    blockingRules: ["No unsupported guarantees", "No missing objective"],
    warningRules: ["Weak CTA signal", "Audience too broad"],
    allowedActions: ["define objective", "flag strategic risk"],
    disallowedActions: ["approve campaign", "send exports"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["audience_agent"],
    fallbackAgentId: "human_approval",
    blockedRoute: "approval_router",
    humanPauseRoute: "human_approval",
    handoffConditions: ["objective defined", "strategic angle produced"],
    retryPolicy: "retry once with narrowed audience context",
    maxRetries: 1,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Primary strategy node for campaign framing.",
  },
  {
    agentId: "audience_agent",
    displayName: "Audience",
    shortDescription: "Chooses or validates audience segment and exclusions.",
    workflowOrder: 3,
    category: "audience",
    enabled: true,
    systemPrompt: "Recommend the most suitable audience and exclusions for the campaign objective using library and Keap mapping context.",
    taskPromptTemplate: "Validate the requested audience or propose a safer segment with exclusions and fit score.",
    styleGuidance: "Bias toward clarity and exclusion safety over over-broad targeting.",
    requiredContextSources: ["audience library", "Keap mapping", "campaign goal"],
    exampleReferences: ["audience/reactivation", "audience/webinar"],
    preferredProvider: "openai",
    preferredModel: "gpt-4.1-mini",
    temperature: 0.2,
    maxTokens: 1400,
    structuredOutputRequired: true,
    inputSchema: { objective: "string", requestedAudience: "string?", audienceLibrary: ["object"] },
    outputSchema: { audienceRecommendation: "string", exclusions: ["string"], fitScore: "number" },
    requiredInputs: ["objective", "audienceLibrary"],
    optionalInputs: ["requestedAudience", "performanceNotes"],
    requiredOutputs: ["audienceRecommendation", "exclusions", "fitScore"],
    escalationMarkers: ["audience unavailable", "mapping conflict"],
    confidenceField: "fitScore",
    riskField: "audienceRisk",
    activeRules: ["Return explicit exclusions", "Keep mapping human-readable"],
    blockingRules: ["No campaign without audience route"],
    warningRules: ["Audience too broad", "Exclusions unclear"],
    allowedActions: ["recommend audience", "flag mismatch"],
    disallowedActions: ["modify offer", "send to CRM"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["offer_agent"],
    fallbackAgentId: "strategist",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["audience recommendation returned"],
    retryPolicy: "retry with operator-selected audience if confidence < 0.5",
    maxRetries: 2,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Audience validation and exclusion control layer.",
  },
  {
    agentId: "offer_agent",
    displayName: "Offer",
    shortDescription: "Selects or validates the approved offer/lead magnet.",
    workflowOrder: 4,
    category: "offer",
    enabled: true,
    systemPrompt: "Match campaign intent to the safest approved offer and return allowed claims plus approval implications.",
    taskPromptTemplate: "Choose an approved offer or lead magnet, list allowed claims, and signal Blue approval requirements.",
    styleGuidance: "Prefer approved inventory over speculative ideas.",
    requiredContextSources: ["offers & lead magnets", "approval status", "campaign goal"],
    exampleReferences: ["offer/sage-call", "offer/webinar"],
    preferredProvider: "openai",
    preferredModel: "gpt-4.1",
    temperature: 0.2,
    maxTokens: 1500,
    structuredOutputRequired: true,
    inputSchema: { objective: "string", approvedOffers: ["object"], audienceRecommendation: "string" },
    outputSchema: { selectedOffer: "string", allowedClaims: ["string"], requiresBlueApproval: "boolean" },
    requiredInputs: ["objective", "approvedOffers"],
    optionalInputs: ["audienceRecommendation"],
    requiredOutputs: ["selectedOffer", "allowedClaims", "requiresBlueApproval"],
    escalationMarkers: ["offer not approved", "offer-audience mismatch"],
    confidenceField: "offerConfidence",
    riskField: "offerRisk",
    activeRules: ["Use approved offer inventory", "Expose claim restrictions"],
    blockingRules: ["No silent offer invention"],
    warningRules: ["Lead magnet needs Blue review"],
    allowedActions: ["select offer", "flag approval"],
    disallowedActions: ["send webhook", "approve claim"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["copywriter"],
    fallbackAgentId: "strategist",
    blockedRoute: "approval_router",
    humanPauseRoute: "human_approval",
    handoffConditions: ["offer selected", "approval requirement emitted"],
    retryPolicy: "retry once with alternate approved offer",
    maxRetries: 1,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Offer and claim suitability selector.",
  },
  {
    agentId: "copywriter",
    displayName: "Copywriter",
    shortDescription: "Writes first-pass email/ad copy from brief, audience, offer, and rules.",
    workflowOrder: 5,
    category: "copy",
    enabled: true,
    systemPrompt: "Write clear first-pass campaign copy grounded in the brief, audience, offer, and CTA.",
    taskPromptTemplate: "Generate subject, preview, body, CTA, and sign-off recommendation from the campaign brief.",
    styleGuidance: "Use concise, direct, non-corporate marketing language with obvious CTA scaffolding.",
    requiredContextSources: ["campaign brief", "offer rules", "audience recommendation"],
    exampleReferences: ["copy/email-seed", "copy/reactivation-template"],
    preferredProvider: "anthropic",
    preferredModel: "claude-sonnet",
    temperature: 0.7,
    maxTokens: 2600,
    structuredOutputRequired: true,
    inputSchema: { campaignBrief: "object", audienceRecommendation: "string", selectedOffer: "string", cta: "string?" },
    outputSchema: { subject: "string", preview: "string", body: "string", cta: "string", signoffRecommendation: "string" },
    requiredInputs: ["campaignBrief", "audienceRecommendation", "selectedOffer"],
    optionalInputs: ["cta", "voiceHints"],
    requiredOutputs: ["subject", "preview", "body", "cta"],
    escalationMarkers: ["missing CTA", "unsupported claim in draft"],
    confidenceField: "draftConfidence",
    riskField: "copyRisk",
    activeRules: ["Honor selected offer restrictions", "Return explicit CTA"],
    blockingRules: ["No fabricated testimonial", "No unapproved guarantees"],
    warningRules: ["Generic copy phrasing", "Weak CTA"],
    allowedActions: ["draft copy", "recommend sign-off"],
    disallowedActions: ["final approval", "trigger integrations"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: true,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["bari_voice_agent"],
    fallbackAgentId: "skeptic",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["first-pass copy generated"],
    retryPolicy: "retry once with strategist constraints if critique fails",
    maxRetries: 1,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Primary first-pass copy generator.",
  },
  {
    agentId: "bari_voice_agent",
    displayName: "Bari Voice",
    shortDescription: "Rewrites or validates copy against Bari-approved voice examples and rules.",
    workflowOrder: 6,
    category: "voice",
    enabled: true,
    systemPrompt: "Rewrite copy in Bari’s approved voice using source examples, voice rules, and sign-off inventory.",
    taskPromptTemplate: "Return revised copy, source references, voice confidence, and learning references for Bari review.",
    styleGuidance: "Favor grounded encouragement, short paragraphs, and direct confidence.",
    requiredContextSources: ["email library", "Bari voice rules", "sign-off library", "previous Bari edits"],
    exampleReferences: ["email_gold_001", "signoff_you_can"],
    preferredProvider: "anthropic",
    preferredModel: "claude-sonnet",
    temperature: 0.5,
    maxTokens: 2200,
    structuredOutputRequired: true,
    inputSchema: { draftCopy: "object", voiceRules: ["object"], sourceEmails: ["object"] },
    outputSchema: { revisedCopy: "object", sourceExamplesUsed: ["string"], voiceConfidence: "number", learningReferences: ["string"] },
    requiredInputs: ["draftCopy", "voiceRules", "sourceEmails"],
    optionalInputs: ["previousBariEdits"],
    requiredOutputs: ["revisedCopy", "voiceConfidence"],
    escalationMarkers: ["voice confidence below threshold", "blocking terminology violation"],
    confidenceField: "voiceConfidence",
    riskField: "voiceRisk",
    activeRules: ["Use Bari-approved sign-offs only", "Preserve SAGE capitalization"],
    blockingRules: ["Never write Sage", "Do not add unsupported founder claims"],
    warningRules: ["Corporate phrasing", "Weak encouragement"],
    allowedActions: ["rewrite copy", "reference approved examples"],
    disallowedActions: ["final send", "trigger integrations"],
    humanApprovalRequired: true,
    canCreateApprovalItems: true,
    canModifyCopy: true,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["brand_rules_checker"],
    fallbackAgentId: "human_approval",
    blockedRoute: "approval_router",
    humanPauseRoute: "human_approval",
    handoffConditions: ["voice rewrite completed", "human pause emitted if needed"],
    retryPolicy: "retry with stricter source weighting once",
    maxRetries: 1,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Founder voice transformation and review preparation.",
  },
  {
    agentId: "brand_rules_checker",
    displayName: "Brand Rules Checker",
    shortDescription: "Enforces terminology, formatting, sign-offs, and blocking rules like SAGE capitalization.",
    workflowOrder: 7,
    category: "rules",
    enabled: true,
    systemPrompt: "Check campaign copy against brand rules and return pass/fail results plus any blocking issues.",
    taskPromptTemplate: "Scan the draft for terminology, formatting, sign-off, and brand consistency issues.",
    styleGuidance: "Be exact, terse, and explicit about blocking issues.",
    requiredContextSources: ["Bari voice rules", "sign-off library", "brand terminology list"],
    exampleReferences: ["rule_sage_caps"],
    preferredProvider: "openai",
    preferredModel: "gpt-4.1-mini",
    temperature: 0.1,
    maxTokens: 1200,
    structuredOutputRequired: true,
    inputSchema: { revisedCopy: "object", brandRules: ["object"] },
    outputSchema: { pass: "boolean", violations: ["string"], requiredFixes: ["string"] },
    requiredInputs: ["revisedCopy", "brandRules"],
    optionalInputs: ["selectedSignoff"],
    requiredOutputs: ["pass", "violations"],
    escalationMarkers: ["blocking rule failure"],
    confidenceField: "brandCheckConfidence",
    riskField: "brandCheckRisk",
    activeRules: ["Preserve approved terminology", "Validate sign-off"],
    blockingRules: ["Always capitalize SAGE"],
    warningRules: ["Weak sign-off context"],
    allowedActions: ["flag violations", "recommend fixes"],
    disallowedActions: ["approve send", "change audience"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["compliance_guard"],
    fallbackAgentId: "human_approval",
    blockedRoute: "approval_router",
    humanPauseRoute: "human_approval",
    handoffConditions: ["brand rule pass or explicit failure emitted"],
    retryPolicy: "no automatic retry",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Terminology and formatting enforcement layer.",
  },
  {
    agentId: "compliance_guard",
    displayName: "Compliance Guard",
    shortDescription: "Flags risky claims, overpromises, and sensitive language.",
    workflowOrder: 8,
    category: "compliance",
    enabled: true,
    systemPrompt: "Evaluate copy for risky claims, unsupported guarantees, and compliance-sensitive language.",
    taskPromptTemplate: "Return risk level, flags, severity, suggested fixes, and approval needs.",
    styleGuidance: "Be explicit, conservative, and explain why language is risky.",
    requiredContextSources: ["compliance rules", "selected offer", "copy draft"],
    exampleReferences: ["comp_no_guarantee"],
    preferredProvider: "openai",
    preferredModel: "gpt-4.1",
    temperature: 0.1,
    maxTokens: 1800,
    structuredOutputRequired: true,
    inputSchema: { copyDraft: "object", complianceRules: ["object"], offerContext: "object" },
    outputSchema: { riskLevel: "string", flags: ["string"], severity: ["string"], suggestedFixes: ["string"], approvalNeeds: ["string"] },
    requiredInputs: ["copyDraft", "complianceRules"],
    optionalInputs: ["offerContext"],
    requiredOutputs: ["riskLevel", "flags", "suggestedFixes"],
    escalationMarkers: ["high-risk transformation claim", "guarantee language"],
    confidenceField: "complianceConfidence",
    riskField: "riskLevel",
    activeRules: ["Flag unsupported guarantees", "Flag regulated language"],
    blockingRules: ["No guaranteed transformation", "No unsupported medical/legal claims"],
    warningRules: ["Urgency language too strong"],
    allowedActions: ["flag risk", "recommend safer wording"],
    disallowedActions: ["final approval", "trigger send"],
    humanApprovalRequired: true,
    canCreateApprovalItems: true,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["skeptic"],
    fallbackAgentId: "human_approval",
    blockedRoute: "approval_router",
    humanPauseRoute: "human_approval",
    handoffConditions: ["compliance report emitted"],
    retryPolicy: "retry after copy revision",
    maxRetries: 2,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Compliance and risk scoring stage.",
  },
  {
    agentId: "skeptic",
    displayName: "Skeptic",
    shortDescription: "Finds weak logic, generic copy, unclear CTA, or unsupported assumptions.",
    workflowOrder: 9,
    category: "critique",
    enabled: true,
    systemPrompt: "Critique the campaign draft like a skeptical strategist focused on weak logic and generic copy.",
    taskPromptTemplate: "Return weaknesses, unsupported assumptions, and recommended changes.",
    styleGuidance: "Use direct critique and point to exact weak spots.",
    requiredContextSources: ["campaign brief", "copy draft", "compliance report"],
    exampleReferences: ["skeptic/generic-copy"],
    preferredProvider: "openai",
    preferredModel: "gpt-4.1-mini",
    temperature: 0.3,
    maxTokens: 1400,
    structuredOutputRequired: true,
    inputSchema: { campaignBrief: "object", copyDraft: "object", complianceReport: "object?" },
    outputSchema: { critique: ["string"], weaknesses: ["string"], recommendedChanges: ["string"] },
    requiredInputs: ["campaignBrief", "copyDraft"],
    optionalInputs: ["complianceReport"],
    requiredOutputs: ["critique", "recommendedChanges"],
    escalationMarkers: ["CTA unclear", "logic unsupported"],
    confidenceField: "critiqueConfidence",
    riskField: "critiqueRisk",
    activeRules: ["Critique must be specific", "Flag unsupported assumptions"],
    blockingRules: [],
    warningRules: ["Generic phrasing", "Weak CTA"],
    allowedActions: ["critique draft", "recommend fixes"],
    disallowedActions: ["approve send", "route approvals"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["performance_agent"],
    fallbackAgentId: "copywriter",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["critique emitted"],
    retryPolicy: "retry once after copy revision",
    maxRetries: 1,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Critical reasoning pass before approval routing.",
  },
  {
    agentId: "performance_agent",
    displayName: "Performance",
    shortDescription: "Predicts tests and likely performance signals before send.",
    workflowOrder: 10,
    category: "performance",
    enabled: true,
    systemPrompt: "Predict likely performance outcomes, propose tests, and identify metrics to watch.",
    taskPromptTemplate: "Return a concise test plan, hypotheses, and metrics to monitor before send.",
    styleGuidance: "Be compact and operational.",
    requiredContextSources: ["campaign brief", "copy draft", "historical performance"],
    exampleReferences: ["performance/subject-test"],
    preferredProvider: "demo",
    preferredModel: "demo-performance-heuristics",
    temperature: 0.2,
    maxTokens: 1200,
    structuredOutputRequired: true,
    inputSchema: { campaignBrief: "object", copyDraft: "object", performanceHistory: ["object"] },
    outputSchema: { testPlan: ["string"], hypotheses: ["string"], metricsToWatch: ["string"] },
    requiredInputs: ["campaignBrief", "copyDraft"],
    optionalInputs: ["performanceHistory"],
    requiredOutputs: ["testPlan", "hypotheses", "metricsToWatch"],
    escalationMarkers: ["no clear metric", "untestable hypothesis"],
    confidenceField: "predictionConfidence",
    riskField: "performanceRisk",
    activeRules: ["Tie every prediction to a metric"],
    blockingRules: [],
    warningRules: ["No clear test plan"],
    allowedActions: ["recommend tests", "summarize metrics"],
    disallowedActions: ["trigger send"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["approval_router"],
    fallbackAgentId: "strategist",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["test plan emitted"],
    retryPolicy: "no automatic retry",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Pre-send testing and telemetry planning node.",
  },
  {
    agentId: "approval_router",
    displayName: "Approval Router",
    shortDescription: "Determines Bari, Blue, internal, or blocked approval path.",
    workflowOrder: 11,
    category: "routing",
    enabled: true,
    systemPrompt: "Determine the human approval path based on voice, risk, compliance, and operational readiness signals.",
    taskPromptTemplate: "Return approval path, owners, reasons, risk level, and any blocking issues.",
    styleGuidance: "Be decisive and explicit about why a human is required.",
    requiredContextSources: ["voice output", "compliance report", "performance plan", "campaign status"],
    exampleReferences: ["approval/bari-route", "approval/blue-route"],
    preferredProvider: "openai",
    preferredModel: "gpt-4.1",
    temperature: 0.1,
    maxTokens: 1500,
    structuredOutputRequired: true,
    inputSchema: { voiceOutput: "object", complianceReport: "object", campaignState: "object" },
    outputSchema: { approvalPath: ["string"], owners: ["string"], reasons: ["string"], riskLevel: "string", blockingIssues: ["string"] },
    requiredInputs: ["voiceOutput", "campaignState"],
    optionalInputs: ["complianceReport", "performancePlan"],
    requiredOutputs: ["approvalPath", "owners", "reasons"],
    escalationMarkers: ["blocked route", "multiple approval owners"],
    confidenceField: "routingConfidence",
    riskField: "riskLevel",
    activeRules: ["Emit explicit owners", "Honor compliance blocks"],
    blockingRules: ["Do not bypass human approval"],
    warningRules: ["Ambiguous route"],
    allowedActions: ["create approval items", "route handoff"],
    disallowedActions: ["final send", "modify copy"],
    humanApprovalRequired: true,
    canCreateApprovalItems: true,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["human_approval"],
    fallbackAgentId: "human_approval",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["approval route emitted"],
    retryPolicy: "no automatic retry",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Primary human approval router.",
  },
  {
    agentId: "human_approval",
    displayName: "Human Approval",
    shortDescription: "Represents the human review pause and authoritative approval gate.",
    workflowOrder: 12,
    category: "human",
    enabled: true,
    systemPrompt: "Represent human review status and route the workflow only after human approval decisions are recorded.",
    taskPromptTemplate: "Hold workflow state until Bari, Blue, or internal review completes.",
    styleGuidance: "Purely operational; do not generate copy.",
    requiredContextSources: ["approval queue", "campaign state"],
    exampleReferences: ["review/bari", "review/blue"],
    preferredProvider: "manual",
    preferredModel: "human-approval",
    temperature: 0,
    maxTokens: 0,
    structuredOutputRequired: true,
    inputSchema: { approvalItems: ["object"], campaignState: "object" },
    outputSchema: { decisionStatus: "string", handoffRoute: "string", notes: ["string"] },
    requiredInputs: ["approvalItems", "campaignState"],
    optionalInputs: ["reviewNotes"],
    requiredOutputs: ["decisionStatus", "handoffRoute"],
    escalationMarkers: ["approval rejected", "approval blocked"],
    confidenceField: "decisionConfidence",
    riskField: "decisionRisk",
    activeRules: ["Human authority is final"],
    blockingRules: ["No automation past this point without approval"],
    warningRules: [],
    allowedActions: ["hold state", "route to next node"],
    disallowedActions: ["draft copy", "trigger integration"],
    humanApprovalRequired: true,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: false,
    canTriggerIntegrations: false,
    nextAgentIds: ["keap_zapier_prep"],
    fallbackAgentId: "approval_router",
    blockedRoute: "approval_router",
    humanPauseRoute: "human_approval",
    handoffConditions: ["all approvals complete"],
    retryPolicy: "not applicable",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Represents the human gate in the workflow.",
  },
  {
    agentId: "keap_zapier_prep",
    displayName: "Keap/Zapier Prep",
    shortDescription: "Prepares manual/API handoff for Keap and Zapier.",
    workflowOrder: 13,
    category: "handoff",
    enabled: true,
    systemPrompt: "Prepare the final export package, tag mapping, and handoff status for Keap or Zapier.",
    taskPromptTemplate: "Return the export package, tag mapping, and readiness state for downstream execution.",
    styleGuidance: "Operator-facing and checklist-like.",
    requiredContextSources: ["approved campaign", "audience mapping", "integration status"],
    exampleReferences: ["handoff/manual-export"],
    preferredProvider: "demo",
    preferredModel: "demo-handoff-shell",
    temperature: 0.1,
    maxTokens: 1200,
    structuredOutputRequired: true,
    inputSchema: { approvedCampaign: "object", integrationStatus: "object" },
    outputSchema: { exportPackage: "object", tagMapping: ["string"], handoffStatus: "string" },
    requiredInputs: ["approvedCampaign", "integrationStatus"],
    optionalInputs: ["audienceMapping"],
    requiredOutputs: ["exportPackage", "handoffStatus"],
    escalationMarkers: ["missing integration mapping"],
    confidenceField: "handoffConfidence",
    riskField: "handoffRisk",
    activeRules: ["Never send without approved route", "Surface manual fallback clearly"],
    blockingRules: ["No send if approvals incomplete"],
    warningRules: ["Integration manual mode active"],
    allowedActions: ["prepare export package", "summarize handoff"],
    disallowedActions: ["trigger real send in demo mode"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: true,
    nextAgentIds: ["response_classifier"],
    fallbackAgentId: "human_approval",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["handoff package ready"],
    retryPolicy: "retry after integration settings update",
    maxRetries: 1,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Pre-send CRM/webhook preparation layer.",
  },
  {
    agentId: "response_classifier",
    displayName: "Response Classifier",
    shortDescription: "Classifies HelpDesk replies and matches them to campaigns.",
    workflowOrder: 14,
    category: "responses",
    enabled: true,
    systemPrompt: "Classify inbound replies, match them to campaigns, and recommend a safe manual action.",
    taskPromptTemplate: "Return intent, urgency, sentiment, matched campaign, and recommended action.",
    styleGuidance: "Be concise and prioritize operator triage.",
    requiredContextSources: ["HelpDesk replies", "campaign records", "learning library"],
    exampleReferences: ["responses/interested-question"],
    preferredProvider: "openai",
    preferredModel: "gpt-4.1-mini",
    temperature: 0.2,
    maxTokens: 1300,
    structuredOutputRequired: true,
    inputSchema: { inboundReply: "object", activeCampaigns: ["object"] },
    outputSchema: { intent: "string", urgency: "string", sentiment: "string", matchedCampaign: "string", recommendedAction: "string" },
    requiredInputs: ["inboundReply", "activeCampaigns"],
    optionalInputs: ["learningInsights"],
    requiredOutputs: ["intent", "urgency", "sentiment", "matchedCampaign"],
    escalationMarkers: ["high urgency reply", "complaint", "unmatched lead"],
    confidenceField: "matchConfidence",
    riskField: "responseRisk",
    activeRules: ["Never auto-send reply", "Always emit confidence"],
    blockingRules: [],
    warningRules: ["Low match confidence"],
    allowedActions: ["classify reply", "recommend manual action"],
    disallowedActions: ["send reply", "modify CRM"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["performance_reporter"],
    fallbackAgentId: "learning_agent",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["reply classification emitted"],
    retryPolicy: "retry once with additional campaign context",
    maxRetries: 1,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Reply-intelligence classification stage.",
  },
  {
    agentId: "performance_reporter",
    displayName: "Performance Reporter",
    shortDescription: "Summarizes post-send metrics and outcomes.",
    workflowOrder: 15,
    category: "reporting",
    enabled: true,
    systemPrompt: "Summarize campaign outcomes, winners, losers, and reply insights after send.",
    taskPromptTemplate: "Return a performance summary, key metrics, and notable outcomes.",
    styleGuidance: "Use operator-friendly telemetry language.",
    requiredContextSources: ["performance snapshots", "reply classifications", "campaign metadata"],
    exampleReferences: ["performance/summary-demo"],
    preferredProvider: "demo",
    preferredModel: "demo-performance-reporter",
    temperature: 0.1,
    maxTokens: 1200,
    structuredOutputRequired: true,
    inputSchema: { performanceSnapshot: "object", responses: ["object"], campaign: "object" },
    outputSchema: { summary: "string", winners: ["string"], losers: ["string"], replyInsights: ["string"] },
    requiredInputs: ["performanceSnapshot", "campaign"],
    optionalInputs: ["responses"],
    requiredOutputs: ["summary", "winners", "losers"],
    escalationMarkers: ["metric anomaly", "performance regression"],
    confidenceField: "reportConfidence",
    riskField: "reportRisk",
    activeRules: ["Tie observations to data", "Keep language concise"],
    blockingRules: [],
    warningRules: ["Insufficient sample size"],
    allowedActions: ["summarize performance", "flag anomalies"],
    disallowedActions: ["change campaign state"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["learning_agent"],
    fallbackAgentId: "learning_agent",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["report emitted"],
    retryPolicy: "retry after metric refresh",
    maxRetries: 1,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Post-send reporting stage.",
  },
  {
    agentId: "learning_agent",
    displayName: "Learning",
    shortDescription: "Turns edits, replies, and campaign results into reusable learning.",
    workflowOrder: 16,
    category: "learning",
    enabled: true,
    systemPrompt: "Convert review edits, replies, and campaign outcomes into reusable learning candidates.",
    taskPromptTemplate: "Return candidate insights, suggested approvals, and future rule recommendations.",
    styleGuidance: "Keep insights actionable and concise.",
    requiredContextSources: ["Bari edits", "Blue decisions", "performance reports", "reply intelligence"],
    exampleReferences: ["learning/warm-direct"],
    preferredProvider: "openai",
    preferredModel: "gpt-4.1-mini",
    temperature: 0.3,
    maxTokens: 1600,
    structuredOutputRequired: true,
    inputSchema: { performanceReport: "object", reviewNotes: ["object"], replySignals: ["object"] },
    outputSchema: { learningCandidates: ["string"], suggestedRules: ["string"], futureGuidance: ["string"] },
    requiredInputs: ["performanceReport"],
    optionalInputs: ["reviewNotes", "replySignals"],
    requiredOutputs: ["learningCandidates"],
    escalationMarkers: ["conflicting guidance", "low confidence learning"],
    confidenceField: "learningConfidence",
    riskField: "learningRisk",
    activeRules: ["Only produce candidate learnings", "Keep humans in approval loop"],
    blockingRules: [],
    warningRules: ["Low confidence learning"],
    allowedActions: ["propose learnings", "suggest future rules"],
    disallowedActions: ["auto-approve learning"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: [],
    fallbackAgentId: "performance_reporter",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["candidate insights emitted"],
    retryPolicy: "no automatic retry",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Terminal learning synthesis node.",
  },
];

export const defaultAgentConfigs: AgentConfigRecord[] = agentSeeds.map((seed) => ({
  ...seed,
  inputSchemaJson: prettyJson(seed.inputSchema),
  outputSchemaJson: prettyJson(seed.outputSchema),
  lastEditedAt: now,
}));

export const defaultAgentRuntimeStates: AgentRuntimeStateRecord[] = [
  { agentId: "campaign_intake", status: "complete", isRunning: false, lastStartedAt: now - 1000 * 60 * 45, lastFinishedAt: now - 1000 * 60 * 44, lastRunId: "run-campaign-intake-001", lastOutputSummary: "Normalized campaign brief captured for downstream agents.", updatedAt: now - 1000 * 60 * 44 },
  { agentId: "strategist", status: "ready", isRunning: false, lastStartedAt: now - 1000 * 60 * 40, lastFinishedAt: now - 1000 * 60 * 39, lastRunId: "run-strategist-001", lastOutputSummary: "Strategic angle and success metric prepared.", updatedAt: now - 1000 * 60 * 39 },
  { agentId: "audience_agent", status: "running", isRunning: true, currentTaskLabel: "Validating segment fit", currentTaskDetail: "Comparing dormant warm leads against campaign goal and exclusions.", lastStartedAt: now - 1000 * 60 * 3, lastRunId: "run-audience-002", lastOutputSummary: "Previous segment fit score: 0.88", updatedAt: now - 1000 * 45 },
  { agentId: "offer_agent", status: "ready", isRunning: false, lastStartedAt: now - 1000 * 60 * 37, lastFinishedAt: now - 1000 * 60 * 36, lastRunId: "run-offer-001", lastOutputSummary: "Free SAGE Strategy Call remains the approved offer.", updatedAt: now - 1000 * 60 * 36 },
  { agentId: "copywriter", status: "running", isRunning: true, currentTaskLabel: "Writing first copy", currentTaskDetail: "Generating subject, preview, and body variants from the strategist brief.", lastStartedAt: now - 1000 * 90, lastRunId: "run-copywriter-003", lastOutputSummary: "Two subject directions generated.", updatedAt: now - 1000 * 30 },
  { agentId: "bari_voice_agent", status: "human_pause", isRunning: false, currentTaskLabel: "Waiting on Bari review", currentTaskDetail: "Founder voice rewrite is paused for Bari approval and notes.", lastStartedAt: now - 1000 * 60 * 30, lastFinishedAt: now - 1000 * 60 * 28, lastRunId: "run-bari-voice-001", lastOutputSummary: "Voice confidence 74%; review requested.", updatedAt: now - 1000 * 60 * 28 },
  { agentId: "brand_rules_checker", status: "pending", isRunning: false, currentTaskLabel: "Queued after Bari voice", currentTaskDetail: "Will enforce SAGE capitalization and sign-off rules after voice approval.", updatedAt: now - 1000 * 60 * 10 },
  { agentId: "compliance_guard", status: "blocked", isRunning: false, currentTaskLabel: "Awaiting safer wording", currentTaskDetail: "High-risk guarantee language blocks automatic progression.", lastError: "Transformation claim flagged for Blue review.", lastRunId: "run-compliance-002", updatedAt: now - 1000 * 60 * 8 },
  { agentId: "skeptic", status: "ready", isRunning: false, lastOutputSummary: "No recent critique yet.", updatedAt: now - 1000 * 60 * 7 },
  { agentId: "performance_agent", status: "idle", isRunning: false, updatedAt: now - 1000 * 60 * 6 },
  { agentId: "approval_router", status: "ready", isRunning: false, lastOutputSummary: "Bari and Blue routes prepared from prior checks.", updatedAt: now - 1000 * 60 * 5 },
  { agentId: "human_approval", status: "pending", isRunning: false, currentTaskLabel: "Awaiting approval items", currentTaskDetail: "Waiting for Approval Router to emit authoritative human gates.", updatedAt: now - 1000 * 60 * 4 },
  { agentId: "keap_zapier_prep", status: "idle", isRunning: false, updatedAt: now - 1000 * 60 * 3 },
  { agentId: "response_classifier", status: "ready", isRunning: false, lastOutputSummary: "Latest reply matched to reactivation campaign.", updatedAt: now - 1000 * 60 * 2 },
  { agentId: "performance_reporter", status: "idle", isRunning: false, updatedAt: now - 1000 * 60 },
  { agentId: "learning_agent", status: "ready", isRunning: false, lastOutputSummary: "Warm direct phrasing remains a candidate learning.", updatedAt: now },
];

export const defaultAgentRuns: AgentRunRecord[] = [
  {
    runId: "run-copywriter-003",
    campaignId: "camp_reactivation_may",
    agentId: "copywriter",
    status: "running",
    inputSnapshot: "Campaign brief + dormant warm leads + Free SAGE Strategy Call",
    outputSummary: "Generating subject and body variants.",
    outputJson: prettyJson({ stage: "drafting", variants: 2 }),
    startedAt: now - 1000 * 90,
  },
  {
    runId: "run-bari-voice-001",
    campaignId: "camp_reactivation_may",
    agentId: "bari_voice_agent",
    status: "human_pause",
    inputSnapshot: "Initial copywriter draft",
    outputSummary: "Voice confidence 74%, awaiting Bari review.",
    outputJson: prettyJson({ signoff: "You can do this — Bari", confidence: 0.74 }),
    startedAt: now - 1000 * 60 * 30,
    finishedAt: now - 1000 * 60 * 28,
  },
  {
    runId: "run-compliance-002",
    campaignId: "camp_webinar_june",
    agentId: "compliance_guard",
    status: "blocked",
    inputSnapshot: "Webinar invitation claim language",
    outputSummary: "Blocked on guarantee-style wording.",
    outputJson: prettyJson({ flags: ["transformation claim"], riskLevel: "red" }),
    startedAt: now - 1000 * 60 * 11,
    finishedAt: now - 1000 * 60 * 8,
    error: "High-risk claim requires Blue review.",
  },
  {
    runId: "run-response-classifier-001",
    campaignId: "camp_reactivation_may",
    agentId: "response_classifier",
    status: "complete",
    inputSnapshot: "Lead reply asking if SAGE is beginner-friendly",
    outputSummary: "Interested with question; medium urgency.",
    outputJson: prettyJson({ intent: "interested_with_question", urgency: "medium", sentiment: "positive" }),
    startedAt: now - 1000 * 60 * 20,
    finishedAt: now - 1000 * 60 * 19,
  },
];

export function getDefaultAgentConfig(agentId: string) {
  return defaultAgentConfigs.find((config) => config.agentId === agentId);
}

export function getDefaultAgentRuntimeState(agentId: string) {
  return defaultAgentRuntimeStates.find((state) => state.agentId === agentId);
}

export function getAgentExecutionConfig(agentId: string) {
  return getDefaultAgentConfig(agentId);
}

export function buildAgentRuntimeContext(agentId: string) {
  return {
    config: getDefaultAgentConfig(agentId),
    runtime: getDefaultAgentRuntimeState(agentId),
    recentRuns: defaultAgentRuns.filter((run) => run.agentId === agentId),
  };
}

export function updateAgentRuntimeStatus(
  agentId: string,
  patch: Partial<AgentRuntimeStateRecord>,
) {
  const base = getDefaultAgentRuntimeState(agentId);
  if (!base) return null;
  return {
    ...base,
    ...patch,
    agentId,
    updatedAt: Date.now(),
  };
}
