import type { AgentConfigRecord, AgentRunRecord, AgentRuntimeStateRecord } from "@/lib/domain";
import { buildCopyPipelineDryRunOutput } from "./copy-intelligence-dry-run";
import { copyIntelligenceAgentSeeds } from "./copy-intelligence-agent-seeds";
import { performanceIntelligenceAgentSeeds } from "./performance-intelligence-agent-seeds";
import { trendIntelligenceAgentSeeds } from "./trend-intelligence-agent-seeds";
import { platformConnectorIntelligenceAgentSeeds } from "./platform-connector-intelligence-agent-seeds";

const now = Date.parse("2026-04-30T16:30:00.000Z");

function prettyJson(value: unknown) {
  return JSON.stringify(value, null, 2);
}

export type AgentConfigSeed = Omit<
  AgentConfigRecord,
  "inputSchemaJson" | "outputSchemaJson" | "lastEditedAt"
> & {
  inputSchema: unknown;
  outputSchema: unknown;
};

const agentSeeds: AgentConfigSeed[] = [
  {
    agentId: "campaign_intake",
    displayName: "Copy Intake Agent",
    shortDescription: "Normalizes the weekly launch brief: angle, CTA, channels, and constraints before downstream copy agents run (dry-run).",
    workflowOrder: 1,
    category: "copy_intelligence",
    enabled: true,
    systemPrompt: "Normalize incoming campaign requests into a stable structured brief without inventing missing facts.",
    taskPromptTemplate: "Read the submitted campaign request and produce a normalized intake package for downstream agents.",
    styleGuidance: "Be precise, operator-readable, and preserve any human-entered constraints verbatim.",
    requiredContextSources: ["campaign intake form", "operator notes"],
    exampleReferences: ["demo/intake/weekly-launch-brief"],
    preferredProvider: "demo",
    preferredModel: "demo-intake-normalizer",
    temperature: 0.1,
    maxTokens: 1200,
    structuredOutputRequired: true,
    inputSchema: { campaignName: "string", goal: "string", audience: "string", offer: "string?" },
    outputSchema: { normalizedBrief: "object", missingFields: ["string"], warnings: ["string"] },
    requiredInputs: ["campaignName", "goal", "audience"],
    optionalInputs: ["offer", "sendWindow", "notes"],
    requiredOutputs: ["normalizedBrief", "missingFields"],
    escalationMarkers: ["missing critical brief fields", "conflicting goals"],
    confidenceField: "intakeConfidence",
    riskField: "briefRisk",
    activeRules: ["Preserve user-entered claims verbatim", "Do not infer approvals"],
    blockingRules: ["Cannot proceed without campaign goal", "Cannot proceed without audience"],
    warningRules: ["Missing send window", "Missing success metric"],
    allowedActions: ["normalize input", "request missing fields"],
    disallowedActions: ["draft copy", "trigger integrations"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: false,
    canTriggerIntegrations: false,
    nextAgentIds: ["strategist"],
    fallbackAgentId: "human_approval",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["brief normalized", "required inputs present"],
    retryPolicy: "retry on missing optional metadata once",
    maxRetries: 1,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Copy Intelligence — entry intake for LangGraph (no external sends).",
  },
  {
    agentId: "strategist",
    displayName: "Campaign Heartbeat Agent",
    shortDescription: "Locks campaign angle, weekly launch objective, and readiness signals for the packet (human checkpoints preserved).",
    workflowOrder: 2,
    category: "campaign_heartbeat",
    enabled: true,
    systemPrompt: "Turn campaign intake into a sharp marketing strategy with objective, audience angle, and success signal.",
    taskPromptTemplate: "Given the intake brief, propose the strategic angle, objective, success metric, and risks.",
    styleGuidance: "Use concise operator language and surface strategic risk early.",
    requiredContextSources: ["campaign intake", "offer library", "audience library", "learning library"],
    exampleReferences: ["strategy/weekly-launch-angle", "strategy/virtual-event-cost-story"],
    preferredProvider: "openai",
    preferredModel: "gpt-4.1",
    temperature: 0.4,
    maxTokens: 1800,
    structuredOutputRequired: true,
    inputSchema: { normalizedBrief: "object", activeOffers: ["object"], audiences: ["object"] },
    outputSchema: { objective: "string", strategicAngle: "string", successMetric: "string", risks: ["string"] },
    requiredInputs: ["normalizedBrief", "activeOffers"],
    optionalInputs: ["learningInsights", "historicalPerformance"],
    requiredOutputs: ["objective", "strategicAngle", "successMetric"],
    escalationMarkers: ["unsupported offer claim", "audience-offer mismatch"],
    confidenceField: "confidence",
    riskField: "riskLevel",
    activeRules: ["Keep strategy tied to approved offers", "State success metric explicitly"],
    blockingRules: ["No unsupported guarantees", "No missing objective"],
    warningRules: ["Weak CTA signal", "Audience too broad"],
    allowedActions: ["define objective", "flag strategic risk"],
    disallowedActions: ["approve campaign", "send exports"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["audience_agent"],
    fallbackAgentId: "human_approval",
    blockedRoute: "approval_router",
    humanPauseRoute: "human_approval",
    handoffConditions: ["objective defined", "strategic angle produced"],
    retryPolicy: "retry once with narrowed audience context",
    maxRetries: 1,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Campaign Heartbeat — strategy angle without auto-approvals. Hermes by Nous (planned office Mac mini runtime) may later coordinate approved heartbeat checks when Operations connects HERMES_RUNTIME_URL.",
  },
  {
    agentId: "audience_agent",
    displayName: "Trend Scout Agent",
    shortDescription: "Surfaces segment fit, short-form angles, and exclusions from library + mapping context (demo heuristics, not live trend scraping).",
    workflowOrder: 3,
    category: "trend_intelligence",
    enabled: true,
    systemPrompt: "Recommend the most suitable audience and exclusions for the campaign objective using library and Keap mapping context.",
    taskPromptTemplate: "Validate the requested audience or propose a safer segment with exclusions and fit score.",
    styleGuidance: "Bias toward clarity and exclusion safety over over-broad targeting.",
    requiredContextSources: ["audience library", "Keap mapping", "campaign goal"],
    exampleReferences: ["audience/weekly-launch-segment", "audience/social-rollout-exclusions"],
    preferredProvider: "openai",
    preferredModel: "gpt-4.1-mini",
    temperature: 0.2,
    maxTokens: 1400,
    structuredOutputRequired: true,
    inputSchema: { objective: "string", requestedAudience: "string?", audienceLibrary: ["object"] },
    outputSchema: { audienceRecommendation: "string", exclusions: ["string"], fitScore: "number" },
    requiredInputs: ["objective", "audienceLibrary"],
    optionalInputs: ["requestedAudience", "performanceNotes"],
    requiredOutputs: ["audienceRecommendation", "exclusions", "fitScore"],
    escalationMarkers: ["audience unavailable", "mapping conflict"],
    confidenceField: "fitScore",
    riskField: "audienceRisk",
    activeRules: ["Return explicit exclusions", "Keep mapping human-readable"],
    blockingRules: ["No campaign without audience route"],
    warningRules: ["Audience too broad", "Exclusions unclear"],
    allowedActions: ["recommend audience", "flag mismatch"],
    disallowedActions: ["modify offer", "send to CRM"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["offer_agent"],
    fallbackAgentId: "strategist",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["audience recommendation returned"],
    retryPolicy: "retry with operator-selected audience if confidence < 0.5",
    maxRetries: 2,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Trend Intelligence — segment and hook-context scout (dry-run).",
  },
  {
    agentId: "offer_agent",
    displayName: "Offer / CTA Agent",
    shortDescription: "Selects or validates the approved offer/lead magnet and primary CTA for the launch packet.",
    workflowOrder: 4,
    category: "copy_intelligence",
    enabled: true,
    systemPrompt: "Match campaign intent to the safest approved offer and return allowed claims plus approval implications.",
    taskPromptTemplate: "Choose an approved offer or lead magnet, list allowed claims, and signal Blue approval requirements.",
    styleGuidance: "Prefer approved inventory over speculative ideas.",
    requiredContextSources: ["offers & lead magnets", "approval status", "campaign goal"],
    exampleReferences: ["offer/sage-call", "offer/weekly-launch-cta"],
    preferredProvider: "openai",
    preferredModel: "gpt-4.1",
    temperature: 0.2,
    maxTokens: 1500,
    structuredOutputRequired: true,
    inputSchema: { objective: "string", approvedOffers: ["object"], audienceRecommendation: "string" },
    outputSchema: { selectedOffer: "string", allowedClaims: ["string"], requiresBlueApproval: "boolean" },
    requiredInputs: ["objective", "approvedOffers"],
    optionalInputs: ["audienceRecommendation"],
    requiredOutputs: ["selectedOffer", "allowedClaims", "requiresBlueApproval"],
    escalationMarkers: ["offer not approved", "offer-audience mismatch"],
    confidenceField: "offerConfidence",
    riskField: "offerRisk",
    activeRules: ["Use approved offer inventory", "Expose claim restrictions"],
    blockingRules: ["No silent offer invention"],
    warningRules: ["Lead magnet needs Blue review"],
    allowedActions: ["select offer", "flag approval"],
    disallowedActions: ["send webhook", "approve claim"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["copywriter"],
    fallbackAgentId: "strategist",
    blockedRoute: "approval_router",
    humanPauseRoute: "human_approval",
    handoffConditions: ["offer selected", "approval requirement emitted"],
    retryPolicy: "retry once with alternate approved offer",
    maxRetries: 1,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Copy Intelligence — offer and CTA suitability.",
  },
  {
    agentId: "copywriter",
    displayName: "Hook Agent",
    shortDescription: "Drafts first-pass hooks, subject lines, preview, and body scaffolding from the weekly launch brief (human approval before send).",
    workflowOrder: 5,
    category: "copy_intelligence",
    enabled: true,
    systemPrompt: "Write clear first-pass campaign copy grounded in the brief, audience, offer, and CTA.",
    taskPromptTemplate: "Generate subject, preview, body, CTA, and sign-off recommendation from the campaign brief.",
    styleGuidance: "Use concise, direct, non-corporate marketing language with obvious CTA scaffolding.",
    requiredContextSources: ["campaign brief", "offer rules", "audience recommendation"],
    exampleReferences: ["copy/email-seed", "copy/weekly-launch-packet"],
    preferredProvider: "anthropic",
    preferredModel: "claude-sonnet",
    temperature: 0.7,
    maxTokens: 2600,
    structuredOutputRequired: true,
    inputSchema: { campaignBrief: "object", audienceRecommendation: "string", selectedOffer: "string", cta: "string?" },
    outputSchema: { subject: "string", preview: "string", body: "string", cta: "string", signoffRecommendation: "string" },
    requiredInputs: ["campaignBrief", "audienceRecommendation", "selectedOffer"],
    optionalInputs: ["cta", "voiceHints"],
    requiredOutputs: ["subject", "preview", "body", "cta"],
    escalationMarkers: ["missing CTA", "unsupported claim in draft"],
    confidenceField: "draftConfidence",
    riskField: "copyRisk",
    activeRules: ["Honor selected offer restrictions", "Return explicit CTA"],
    blockingRules: ["No fabricated testimonial", "No unapproved guarantees"],
    warningRules: ["Generic copy phrasing", "Weak CTA"],
    allowedActions: ["draft copy", "recommend sign-off"],
    disallowedActions: ["final approval", "trigger integrations"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: true,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["bari_voice_agent"],
    fallbackAgentId: "skeptic",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["first-pass copy generated"],
    retryPolicy: "retry once with strategist constraints if critique fails",
    maxRetries: 1,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Copy Intelligence — hook and body draft node.",
  },
  {
    agentId: "bari_voice_agent",
    displayName: "Voice Matching Agent",
    shortDescription: "Aligns drafts to Bari-approved voice examples and rules before human founder-voice review.",
    workflowOrder: 6,
    category: "copy_intelligence",
    enabled: true,
    systemPrompt: "Rewrite copy in Bari’s approved voice using source examples, voice rules, and sign-off inventory.",
    taskPromptTemplate: "Return revised copy, source references, voice confidence, and learning references for Bari review.",
    styleGuidance: "Favor grounded encouragement, short paragraphs, and direct confidence.",
    requiredContextSources: ["email library", "Bari voice rules", "sign-off library", "previous Bari edits"],
    exampleReferences: ["email_gold_001", "signoff_you_can"],
    preferredProvider: "anthropic",
    preferredModel: "claude-sonnet",
    temperature: 0.5,
    maxTokens: 2200,
    structuredOutputRequired: true,
    inputSchema: { draftCopy: "object", voiceRules: ["object"], sourceEmails: ["object"] },
    outputSchema: { revisedCopy: "object", sourceExamplesUsed: ["string"], voiceConfidence: "number", learningReferences: ["string"] },
    requiredInputs: ["draftCopy", "voiceRules", "sourceEmails"],
    optionalInputs: ["previousBariEdits"],
    requiredOutputs: ["revisedCopy", "voiceConfidence"],
    escalationMarkers: ["voice confidence below threshold", "blocking terminology violation"],
    confidenceField: "voiceConfidence",
    riskField: "voiceRisk",
    activeRules: ["Use Bari-approved sign-offs only", "Preserve SAGE capitalization"],
    blockingRules: ["Never write Sage", "Do not add unsupported founder claims"],
    warningRules: ["Corporate phrasing", "Weak encouragement"],
    allowedActions: ["rewrite copy", "reference approved examples"],
    disallowedActions: ["final send", "trigger integrations"],
    humanApprovalRequired: true,
    canCreateApprovalItems: true,
    canModifyCopy: true,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["brand_rules_checker"],
    fallbackAgentId: "human_approval",
    blockedRoute: "approval_router",
    humanPauseRoute: "human_approval",
    handoffConditions: ["voice rewrite completed", "human pause emitted if needed"],
    retryPolicy: "retry with stricter source weighting once",
    maxRetries: 1,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Copy Intelligence — founder voice alignment before human gate.",
  },
  {
    agentId: "brand_rules_checker",
    displayName: "Brand Rules Checker",
    shortDescription: "Enforces terminology, formatting, sign-offs, and blocking rules like SAGE capitalization.",
    workflowOrder: 7,
    category: "copy_intelligence",
    enabled: true,
    systemPrompt: "Check campaign copy against brand rules and return pass/fail results plus any blocking issues.",
    taskPromptTemplate: "Scan the draft for terminology, formatting, sign-off, and brand consistency issues.",
    styleGuidance: "Be exact, terse, and explicit about blocking issues.",
    requiredContextSources: ["Bari voice rules", "sign-off library", "brand terminology list"],
    exampleReferences: ["rule_sage_caps"],
    preferredProvider: "openai",
    preferredModel: "gpt-4.1-mini",
    temperature: 0.1,
    maxTokens: 1200,
    structuredOutputRequired: true,
    inputSchema: { revisedCopy: "object", brandRules: ["object"] },
    outputSchema: { pass: "boolean", violations: ["string"], requiredFixes: ["string"] },
    requiredInputs: ["revisedCopy", "brandRules"],
    optionalInputs: ["selectedSignoff"],
    requiredOutputs: ["pass", "violations"],
    escalationMarkers: ["blocking rule failure"],
    confidenceField: "brandCheckConfidence",
    riskField: "brandCheckRisk",
    activeRules: ["Preserve approved terminology", "Validate sign-off"],
    blockingRules: ["Always capitalize SAGE"],
    warningRules: ["Weak sign-off context"],
    allowedActions: ["flag violations", "recommend fixes"],
    disallowedActions: ["approve send", "change audience"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["compliance_guard"],
    fallbackAgentId: "human_approval",
    blockedRoute: "approval_router",
    humanPauseRoute: "human_approval",
    handoffConditions: ["brand rule pass or explicit failure emitted"],
    retryPolicy: "no automatic retry",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Copy Intelligence — brand rule enforcement.",
  },
  {
    agentId: "compliance_guard",
    displayName: "Compliance Guard",
    shortDescription: "Flags risky claims, overpromises, and sensitive language.",
    workflowOrder: 8,
    category: "copy_intelligence",
    enabled: true,
    systemPrompt: "Evaluate copy for risky claims, unsupported guarantees, and compliance-sensitive language.",
    taskPromptTemplate: "Return risk level, flags, severity, suggested fixes, and approval needs.",
    styleGuidance: "Be explicit, conservative, and explain why language is risky.",
    requiredContextSources: ["compliance rules", "selected offer", "copy draft"],
    exampleReferences: ["comp_no_guarantee"],
    preferredProvider: "openai",
    preferredModel: "gpt-4.1",
    temperature: 0.1,
    maxTokens: 1800,
    structuredOutputRequired: true,
    inputSchema: { copyDraft: "object", complianceRules: ["object"], offerContext: "object" },
    outputSchema: { riskLevel: "string", flags: ["string"], severity: ["string"], suggestedFixes: ["string"], approvalNeeds: ["string"] },
    requiredInputs: ["copyDraft", "complianceRules"],
    optionalInputs: ["offerContext"],
    requiredOutputs: ["riskLevel", "flags", "suggestedFixes"],
    escalationMarkers: ["high-risk transformation claim", "guarantee language"],
    confidenceField: "complianceConfidence",
    riskField: "riskLevel",
    activeRules: ["Flag unsupported guarantees", "Flag regulated language"],
    blockingRules: ["No guaranteed transformation", "No unsupported medical/legal claims"],
    warningRules: ["Urgency language too strong"],
    allowedActions: ["flag risk", "recommend safer wording"],
    disallowedActions: ["final approval", "trigger send"],
    humanApprovalRequired: true,
    canCreateApprovalItems: true,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["skeptic"],
    fallbackAgentId: "human_approval",
    blockedRoute: "approval_router",
    humanPauseRoute: "human_approval",
    handoffConditions: ["compliance report emitted"],
    retryPolicy: "retry after copy revision",
    maxRetries: 2,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Copy Intelligence — compliance and risk scoring.",
  },
  {
    agentId: "skeptic",
    displayName: "Skeptic",
    shortDescription: "Finds weak logic, generic copy, unclear CTA, or unsupported assumptions.",
    workflowOrder: 9,
    category: "copy_intelligence",
    enabled: true,
    systemPrompt: "Critique the campaign draft like a skeptical strategist focused on weak logic and generic copy.",
    taskPromptTemplate: "Return weaknesses, unsupported assumptions, and recommended changes.",
    styleGuidance: "Use direct critique and point to exact weak spots.",
    requiredContextSources: ["campaign brief", "copy draft", "compliance report"],
    exampleReferences: ["skeptic/generic-copy"],
    preferredProvider: "openai",
    preferredModel: "gpt-4.1-mini",
    temperature: 0.3,
    maxTokens: 1400,
    structuredOutputRequired: true,
    inputSchema: { campaignBrief: "object", copyDraft: "object", complianceReport: "object?" },
    outputSchema: { critique: ["string"], weaknesses: ["string"], recommendedChanges: ["string"] },
    requiredInputs: ["campaignBrief", "copyDraft"],
    optionalInputs: ["complianceReport"],
    requiredOutputs: ["critique", "recommendedChanges"],
    escalationMarkers: ["CTA unclear", "logic unsupported"],
    confidenceField: "critiqueConfidence",
    riskField: "critiqueRisk",
    activeRules: ["Critique must be specific", "Flag unsupported assumptions"],
    blockingRules: [],
    warningRules: ["Generic phrasing", "Weak CTA"],
    allowedActions: ["critique draft", "recommend fixes"],
    disallowedActions: ["approve send", "route approvals"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["performance_agent"],
    fallbackAgentId: "copywriter",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["critique emitted"],
    retryPolicy: "retry once after copy revision",
    maxRetries: 1,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Copy Intelligence — critique pass before approvals.",
  },
  {
    agentId: "performance_agent",
    displayName: "Performance Learning Agent",
    shortDescription: "Proposes tests, hypotheses, and demo-safe metrics to watch for the weekly launch (not live analytics).",
    workflowOrder: 10,
    category: "performance_intelligence",
    groupId: "performance_intelligence",
    enabled: true,
    systemPrompt: "Predict likely performance outcomes, propose tests, and identify metrics to watch.",
    taskPromptTemplate: "Return a concise test plan, hypotheses, and metrics to monitor before send.",
    styleGuidance: "Be compact and operational.",
    requiredContextSources: ["campaign brief", "copy draft", "historical performance"],
    exampleReferences: ["performance/weekly-launch-test-plan"],
    preferredProvider: "demo",
    preferredModel: "demo-performance-heuristics",
    temperature: 0.2,
    maxTokens: 1200,
    structuredOutputRequired: true,
    inputSchema: { campaignBrief: "object", copyDraft: "object", performanceHistory: ["object"] },
    outputSchema: { testPlan: ["string"], hypotheses: ["string"], metricsToWatch: ["string"] },
    requiredInputs: ["campaignBrief", "copyDraft"],
    optionalInputs: ["performanceHistory"],
    requiredOutputs: ["testPlan", "hypotheses", "metricsToWatch"],
    escalationMarkers: ["no clear metric", "untestable hypothesis"],
    confidenceField: "predictionConfidence",
    riskField: "performanceRisk",
    activeRules: ["Tie every prediction to a metric"],
    blockingRules: [],
    warningRules: ["No clear test plan"],
    allowedActions: ["recommend tests", "summarize metrics"],
    disallowedActions: ["trigger send"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["approval_router"],
    fallbackAgentId: "strategist",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["test plan emitted"],
    retryPolicy: "no automatic retry",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Performance Intelligence — pre-send test planning (dry-run).",
  },
  {
    agentId: "approval_router",
    displayName: "Approval Router",
    shortDescription: "Determines Bari, Blue, internal, or blocked approval path for the launch packet.",
    workflowOrder: 11,
    category: "copy_intelligence",
    enabled: true,
    systemPrompt: "Determine the human approval path based on voice, risk, compliance, and operational readiness signals.",
    taskPromptTemplate: "Return approval path, owners, reasons, risk level, and any blocking issues.",
    styleGuidance: "Be decisive and explicit about why a human is required.",
    requiredContextSources: ["voice output", "compliance report", "performance plan", "campaign status"],
    exampleReferences: ["approval/bari-route", "approval/blue-route"],
    preferredProvider: "openai",
    preferredModel: "gpt-4.1",
    temperature: 0.1,
    maxTokens: 1500,
    structuredOutputRequired: true,
    inputSchema: { voiceOutput: "object", complianceReport: "object", campaignState: "object" },
    outputSchema: { approvalPath: ["string"], owners: ["string"], reasons: ["string"], riskLevel: "string", blockingIssues: ["string"] },
    requiredInputs: ["voiceOutput", "campaignState"],
    optionalInputs: ["complianceReport", "performancePlan"],
    requiredOutputs: ["approvalPath", "owners", "reasons"],
    escalationMarkers: ["blocked route", "multiple approval owners"],
    confidenceField: "routingConfidence",
    riskField: "riskLevel",
    activeRules: ["Emit explicit owners", "Honor compliance blocks"],
    blockingRules: ["Do not bypass human approval"],
    warningRules: ["Ambiguous route"],
    allowedActions: ["create approval items", "route handoff"],
    disallowedActions: ["final send", "modify copy"],
    humanApprovalRequired: true,
    canCreateApprovalItems: true,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["human_approval"],
    fallbackAgentId: "human_approval",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["approval route emitted"],
    retryPolicy: "no automatic retry",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Copy Intelligence — routes human gates (Bari/Blue/internal).",
  },
  {
    agentId: "human_approval",
    displayName: "Human Approval",
    shortDescription: "Represents the human review pause and authoritative approval gate.",
    workflowOrder: 12,
    category: "copy_intelligence",
    enabled: true,
    systemPrompt: "Represent human review status and route the workflow only after human approval decisions are recorded.",
    taskPromptTemplate: "Hold workflow state until Bari, Blue, or internal review completes.",
    styleGuidance: "Purely operational; do not generate copy.",
    requiredContextSources: ["approval queue", "campaign state"],
    exampleReferences: ["review/bari", "review/blue"],
    preferredProvider: "manual",
    preferredModel: "human-approval",
    temperature: 0,
    maxTokens: 0,
    structuredOutputRequired: true,
    inputSchema: { approvalItems: ["object"], campaignState: "object" },
    outputSchema: { decisionStatus: "string", handoffRoute: "string", notes: ["string"] },
    requiredInputs: ["approvalItems", "campaignState"],
    optionalInputs: ["reviewNotes"],
    requiredOutputs: ["decisionStatus", "handoffRoute"],
    escalationMarkers: ["approval rejected", "approval blocked"],
    confidenceField: "decisionConfidence",
    riskField: "decisionRisk",
    activeRules: ["Human authority is final"],
    blockingRules: ["No automation past this point without approval"],
    warningRules: [],
    allowedActions: ["hold state", "route to next node"],
    disallowedActions: ["draft copy", "trigger integration"],
    humanApprovalRequired: true,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: false,
    canTriggerIntegrations: false,
    nextAgentIds: ["keap_zapier_prep"],
    fallbackAgentId: "approval_router",
    blockedRoute: "approval_router",
    humanPauseRoute: "human_approval",
    handoffConditions: ["all approvals complete"],
    retryPolicy: "not applicable",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Human gate — no automation past approvals.",
  },
  {
    agentId: "keap_zapier_prep",
    displayName: "Keap / Zapier Prep Agent",
    shortDescription: "Prepares manual CRM/export handoff for Keap and Zapier after approvals (no live send in demo).",
    workflowOrder: 13,
    category: "production_bridge",
    enabled: true,
    systemPrompt: "Prepare the final export package, tag mapping, and handoff status for Keap or Zapier.",
    taskPromptTemplate: "Return the export package, tag mapping, and readiness state for downstream execution.",
    styleGuidance: "Operator-facing and checklist-like.",
    requiredContextSources: ["approved campaign", "audience mapping", "integration status"],
    exampleReferences: ["handoff/manual-export"],
    preferredProvider: "demo",
    preferredModel: "demo-handoff-shell",
    temperature: 0.1,
    maxTokens: 1200,
    structuredOutputRequired: true,
    inputSchema: { approvedCampaign: "object", integrationStatus: "object" },
    outputSchema: { exportPackage: "object", tagMapping: ["string"], handoffStatus: "string" },
    requiredInputs: ["approvedCampaign", "integrationStatus"],
    optionalInputs: ["audienceMapping"],
    requiredOutputs: ["exportPackage", "handoffStatus"],
    escalationMarkers: ["missing integration mapping"],
    confidenceField: "handoffConfidence",
    riskField: "handoffRisk",
    activeRules: ["Never send without approved route", "Surface manual fallback clearly"],
    blockingRules: ["No send if approvals incomplete"],
    warningRules: ["Integration manual mode active"],
    allowedActions: ["prepare export package", "summarize handoff"],
    disallowedActions: ["trigger real send in demo mode"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: true,
    nextAgentIds: ["response_classifier"],
    fallbackAgentId: "human_approval",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["handoff package ready"],
    retryPolicy: "retry after integration settings update",
    maxRetries: 1,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Keap / Zapier handoff — export package assembly only.",
  },
  {
    agentId: "production_asset_intake",
    displayName: "Production Asset Intake Agent",
    shortDescription: "Normalizes Production Bridge references into campaign-safe snapshots (read-only, dry-run).",
    workflowOrder: 17,
    category: "production_bridge",
    enabled: false,
    systemPrompt: "Summarize linked production assets for marketing operators without mutating Production Hub, Frame.io, or Mux.",
    taskPromptTemplate: "Return a concise snapshot: title, readiness, transcript/thumbnail status, shorts counts, and safe links.",
    styleGuidance: "Reference-only; flag stale cache and missing fields.",
    requiredContextSources: ["production bridge cache", "campaign launch packet"],
    exampleReferences: ["production-bridge/manual-cache"],
    preferredProvider: "demo",
    preferredModel: "demo-production-bridge",
    temperature: 0,
    maxTokens: 800,
    structuredOutputRequired: true,
    inputSchema: { productionAsset: "object", campaign: "object" },
    outputSchema: { snapshotSummary: "string", risks: ["string"] },
    requiredInputs: ["productionAsset"],
    optionalInputs: ["campaign"],
    requiredOutputs: ["snapshotSummary"],
    escalationMarkers: ["stale cache", "blocked asset"],
    confidenceField: "snapshotConfidence",
    riskField: "snapshotRisk",
    activeRules: ["Read-only", "No external writes"],
    blockingRules: [],
    warningRules: ["Cache may be stale"],
    allowedActions: ["summarize cached asset"],
    disallowedActions: ["modify production hub", "upload", "publish"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: false,
    canTriggerIntegrations: false,
    nextAgentIds: [],
    fallbackAgentId: "human_approval",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["snapshot emitted"],
    retryPolicy: "not applicable",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Production Bridge — planned intake layer.",
  },
  {
    agentId: "asset_readiness_checker",
    displayName: "Asset Readiness Checker",
    shortDescription: "Checks transcript, thumbnail, shorts, and blocked states from cached production assets (dry-run).",
    workflowOrder: 18,
    category: "production_bridge",
    enabled: false,
    systemPrompt: "Evaluate readiness flags for weekly launch risk summaries only.",
    taskPromptTemplate: "Return checklist results and human-readable risks.",
    styleGuidance: "Short operator bullets.",
    requiredContextSources: ["production bridge cache"],
    exampleReferences: ["heartbeat/production-bridge"],
    preferredProvider: "demo",
    preferredModel: "demo-readiness",
    temperature: 0,
    maxTokens: 600,
    structuredOutputRequired: true,
    inputSchema: { productionAsset: "object" },
    outputSchema: { risks: ["string"], blockers: ["string"] },
    requiredInputs: ["productionAsset"],
    optionalInputs: [],
    requiredOutputs: ["risks"],
    escalationMarkers: ["blocked"],
    confidenceField: "readinessConfidence",
    riskField: "readinessRisk",
    activeRules: ["Read-only"],
    blockingRules: [],
    warningRules: [],
    allowedActions: ["readiness check"],
    disallowedActions: ["write to production systems"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: false,
    canTriggerIntegrations: false,
    nextAgentIds: [],
    fallbackAgentId: "production_asset_intake",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["checklist complete"],
    retryPolicy: "not applicable",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Production Bridge — mirrors Campaign Heartbeat signals.",
  },
  {
    agentId: "transcript_summary_bridge",
    displayName: "Transcript Summary Agent",
    shortDescription: "Planned helper to turn transcript summaries into copy hints (reference-only, not connected).",
    workflowOrder: 19,
    category: "production_bridge",
    enabled: false,
    systemPrompt: "Never exfiltrate secrets; summarize only approved cache fields.",
    taskPromptTemplate: "Produce a short copy-facing summary from transcriptSummary text.",
    styleGuidance: "Concise marketing bullets.",
    requiredContextSources: ["cached transcript summary"],
    exampleReferences: ["library/planned-transcript-pull"],
    preferredProvider: "demo",
    preferredModel: "demo-transcript-bridge",
    temperature: 0.2,
    maxTokens: 600,
    structuredOutputRequired: true,
    inputSchema: { transcriptSummary: "string" },
    outputSchema: { bullets: ["string"] },
    requiredInputs: ["transcriptSummary"],
    optionalInputs: [],
    requiredOutputs: ["bullets"],
    escalationMarkers: [],
    confidenceField: "summaryConfidence",
    riskField: "summaryRisk",
    activeRules: ["Reference-only"],
    blockingRules: [],
    warningRules: [],
    allowedActions: ["summarize"],
    disallowedActions: ["push to library automatically"],
    humanApprovalRequired: true,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: [],
    fallbackAgentId: "production_asset_intake",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["human review"],
    retryPolicy: "not applicable",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Production Bridge — future Library link.",
  },
  {
    agentId: "shorts_availability_checker",
    displayName: "Shorts Availability Checker",
    shortDescription: "Planned checker for related shorts/reels readiness from cached counts (dry-run).",
    workflowOrder: 20,
    category: "production_bridge",
    enabled: false,
    systemPrompt: "Compare shortsCount vs readyShortsCount and surface rollout risk.",
    taskPromptTemplate: "Return a one-paragraph operator note.",
    styleGuidance: "Plain language.",
    requiredContextSources: ["production bridge cache"],
    exampleReferences: ["rollout/shorts-readiness"],
    preferredProvider: "demo",
    preferredModel: "demo-shorts-check",
    temperature: 0,
    maxTokens: 400,
    structuredOutputRequired: true,
    inputSchema: { productionAsset: "object" },
    outputSchema: { note: "string" },
    requiredInputs: ["productionAsset"],
    optionalInputs: [],
    requiredOutputs: ["note"],
    escalationMarkers: [],
    confidenceField: "shortsConfidence",
    riskField: "shortsRisk",
    activeRules: ["Read-only"],
    blockingRules: [],
    warningRules: [],
    allowedActions: ["compare counts"],
    disallowedActions: ["assign production tasks"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: false,
    canTriggerIntegrations: false,
    nextAgentIds: [],
    fallbackAgentId: "asset_readiness_checker",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["note emitted"],
    retryPolicy: "not applicable",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Production Bridge — shorts readiness.",
  },
  {
    agentId: "production_to_campaign_mapper",
    displayName: "Production-to-Campaign Mapper",
    shortDescription: "Maps cached production fields into launch packet snapshot fields (manual trigger only).",
    workflowOrder: 21,
    category: "production_bridge",
    enabled: false,
    systemPrompt: "Describe the mapping between a cached asset and a Weekly Launch Packet without performing writes.",
    taskPromptTemplate: "List fields to copy into the campaign record.",
    styleGuidance: "Table-like text.",
    requiredContextSources: ["production asset", "campaign"],
    exampleReferences: ["campaigns/snapshot-mapping"],
    preferredProvider: "demo",
    preferredModel: "demo-mapper",
    temperature: 0,
    maxTokens: 500,
    structuredOutputRequired: true,
    inputSchema: { productionAsset: "object", campaign: "object" },
    outputSchema: { fields: ["string"] },
    requiredInputs: ["productionAsset", "campaign"],
    optionalInputs: [],
    requiredOutputs: ["fields"],
    escalationMarkers: [],
    confidenceField: "mapConfidence",
    riskField: "mapRisk",
    activeRules: ["No external writes"],
    blockingRules: [],
    warningRules: [],
    allowedActions: ["describe mapping"],
    disallowedActions: ["mutate production hub"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: false,
    canTriggerIntegrations: false,
    nextAgentIds: [],
    fallbackAgentId: "production_asset_intake",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["mapping described"],
    retryPolicy: "not applicable",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Production Bridge — mirrors linkAssetToCampaign intent.",
  },
  {
    agentId: "response_classifier",
    displayName: "Response Classifier",
    shortDescription: "Classifies HelpDesk replies and matches them to weekly launch campaigns; recommends manual triage only.",
    workflowOrder: 14,
    category: "copy_intelligence",
    enabled: true,
    systemPrompt: "Classify inbound replies, match them to campaigns, and recommend a safe manual action.",
    taskPromptTemplate: "Return intent, urgency, sentiment, matched campaign, and recommended action.",
    styleGuidance: "Be concise and prioritize operator triage.",
    requiredContextSources: ["HelpDesk replies", "campaign records", "learning library"],
    exampleReferences: ["responses/weekly-launch-inbound"],
    preferredProvider: "openai",
    preferredModel: "gpt-4.1-mini",
    temperature: 0.2,
    maxTokens: 1300,
    structuredOutputRequired: true,
    inputSchema: { inboundReply: "object", activeCampaigns: ["object"] },
    outputSchema: { intent: "string", urgency: "string", sentiment: "string", matchedCampaign: "string", recommendedAction: "string" },
    requiredInputs: ["inboundReply", "activeCampaigns"],
    optionalInputs: ["learningInsights"],
    requiredOutputs: ["intent", "urgency", "sentiment", "matchedCampaign"],
    escalationMarkers: ["high urgency reply", "complaint", "unmatched lead"],
    confidenceField: "matchConfidence",
    riskField: "responseRisk",
    activeRules: ["Never auto-send reply", "Always emit confidence"],
    blockingRules: [],
    warningRules: ["Low match confidence"],
    allowedActions: ["classify reply", "recommend manual action"],
    disallowedActions: ["send reply", "modify CRM"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["performance_reporter"],
    fallbackAgentId: "learning_agent",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["reply classification emitted"],
    retryPolicy: "retry once with additional campaign context",
    maxRetries: 1,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Copy Intelligence — reply triage (no auto-send).",
  },
  {
    agentId: "performance_reporter",
    displayName: "Performance Reporter",
    shortDescription: "Summarizes demo/manual performance slices after send windows (illustrative, not a live warehouse).",
    workflowOrder: 15,
    category: "performance_intelligence",
    groupId: "performance_intelligence",
    enabled: true,
    systemPrompt: "Summarize campaign outcomes, winners, losers, and reply insights after send.",
    taskPromptTemplate: "Return a performance summary, key metrics, and notable outcomes.",
    styleGuidance: "Use operator-friendly telemetry language.",
    requiredContextSources: ["performance snapshots", "reply classifications", "campaign metadata"],
    exampleReferences: ["performance/weekly-launch-demo-summary"],
    preferredProvider: "demo",
    preferredModel: "demo-performance-reporter",
    temperature: 0.1,
    maxTokens: 1200,
    structuredOutputRequired: true,
    inputSchema: { performanceSnapshot: "object", responses: ["object"], campaign: "object" },
    outputSchema: { summary: "string", winners: ["string"], losers: ["string"], replyInsights: ["string"] },
    requiredInputs: ["performanceSnapshot", "campaign"],
    optionalInputs: ["responses"],
    requiredOutputs: ["summary", "winners", "losers"],
    escalationMarkers: ["metric anomaly", "performance regression"],
    confidenceField: "reportConfidence",
    riskField: "reportRisk",
    activeRules: ["Tie observations to data", "Keep language concise"],
    blockingRules: [],
    warningRules: ["Insufficient sample size"],
    allowedActions: ["summarize performance", "flag anomalies"],
    disallowedActions: ["change campaign state"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: ["learning_agent"],
    fallbackAgentId: "learning_agent",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["report emitted"],
    retryPolicy: "retry after metric refresh",
    maxRetries: 1,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Performance Intelligence — demo rollup node.",
  },
  {
    agentId: "learning_agent",
    displayName: "Learning Loop Agent",
    shortDescription: "Turns edits, replies, and campaign results into reusable learning candidates for the library.",
    workflowOrder: 16,
    category: "learning_loop",
    enabled: true,
    systemPrompt: "Convert review edits, replies, and campaign outcomes into reusable learning candidates.",
    taskPromptTemplate: "Return candidate insights, suggested approvals, and future rule recommendations.",
    styleGuidance: "Keep insights actionable and concise.",
    requiredContextSources: ["Bari edits", "Blue decisions", "performance reports", "reply intelligence"],
    exampleReferences: ["learning/weekly-launch-patterns"],
    preferredProvider: "openai",
    preferredModel: "gpt-4.1-mini",
    temperature: 0.3,
    maxTokens: 1600,
    structuredOutputRequired: true,
    inputSchema: { performanceReport: "object", reviewNotes: ["object"], replySignals: ["object"] },
    outputSchema: { learningCandidates: ["string"], suggestedRules: ["string"], futureGuidance: ["string"] },
    requiredInputs: ["performanceReport"],
    optionalInputs: ["reviewNotes", "replySignals"],
    requiredOutputs: ["learningCandidates"],
    escalationMarkers: ["conflicting guidance", "low confidence learning"],
    confidenceField: "learningConfidence",
    riskField: "learningRisk",
    activeRules: ["Only produce candidate learnings", "Keep humans in approval loop"],
    blockingRules: [],
    warningRules: ["Low confidence learning"],
    allowedActions: ["propose learnings", "suggest future rules"],
    disallowedActions: ["auto-approve learning"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds: [],
    fallbackAgentId: "performance_reporter",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["candidate insights emitted"],
    retryPolicy: "no automatic retry",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: "Learning Loop — candidate insights only (human approval to promote).",
  },
  ...copyIntelligenceAgentSeeds,
  ...trendIntelligenceAgentSeeds,
  ...performanceIntelligenceAgentSeeds,
  ...platformConnectorIntelligenceAgentSeeds,
];

export const defaultAgentConfigs: AgentConfigRecord[] = agentSeeds.map((seed) => ({
  agentId: seed.agentId,
  displayName: seed.displayName,
  shortDescription: seed.shortDescription,
  workflowOrder: seed.workflowOrder,
  category: seed.category,
  groupId: seed.groupId,
  agentRole: seed.agentRole,
  inputSources: seed.inputSources,
  outputTargets: seed.outputTargets,
  safetyMode: seed.safetyMode,
  isCore: seed.isCore,
  enabled: seed.enabled,
  systemPrompt: seed.systemPrompt,
  taskPromptTemplate: seed.taskPromptTemplate,
  styleGuidance: seed.styleGuidance,
  requiredContextSources: seed.requiredContextSources,
  exampleReferences: seed.exampleReferences,
  preferredProvider: seed.preferredProvider,
  preferredModel: seed.preferredModel,
  temperature: seed.temperature,
  maxTokens: seed.maxTokens,
  structuredOutputRequired: seed.structuredOutputRequired,
  inputSchemaJson: prettyJson(seed.inputSchema),
  outputSchemaJson: prettyJson(seed.outputSchema),
  requiredInputs: seed.requiredInputs,
  optionalInputs: seed.optionalInputs,
  requiredOutputs: seed.requiredOutputs,
  escalationMarkers: seed.escalationMarkers,
  confidenceField: seed.confidenceField,
  riskField: seed.riskField,
  activeRules: seed.activeRules,
  blockingRules: seed.blockingRules,
  warningRules: seed.warningRules,
  allowedActions: seed.allowedActions,
  disallowedActions: seed.disallowedActions,
  humanApprovalRequired: seed.humanApprovalRequired,
  canCreateApprovalItems: seed.canCreateApprovalItems,
  canModifyCopy: seed.canModifyCopy,
  canReadLibraries: seed.canReadLibraries,
  canTriggerIntegrations: seed.canTriggerIntegrations,
  nextAgentIds: seed.nextAgentIds,
  fallbackAgentId: seed.fallbackAgentId,
  blockedRoute: seed.blockedRoute,
  humanPauseRoute: seed.humanPauseRoute,
  handoffConditions: seed.handoffConditions,
  retryPolicy: seed.retryPolicy,
  maxRetries: seed.maxRetries,
  configVersion: seed.configVersion,
  lastEditedBy: seed.lastEditedBy,
  lastEditedAt: now,
  notes: seed.notes,
}));

const demoCopyPipelineRun = buildCopyPipelineDryRunOutput({
  campaign: {
    campaignId: "camp_reactivation_may",
    name: "Weekly Launch — Virtual Event Cost Shift",
    goal: "Drive coordinated weekly launch readiness",
    campaignAngle: "Virtual events can improve net profit vs in-person when travel/hotel/logistics are heavy.",
    primaryAudience: "Speakers and creators evaluating event format ROI",
    primaryCta: "Save your seat / book strategy call",
    sourceProductionAssetTitle: "Are Virtual Events Still a Thing?",
    sourceProductionAssetId: "prod_asset_2026_05_virtual_events_still_a_thing",
    relatedShortsNotes: "Shorts: 1/3 ready",
  },
  productionAsset: {
    title: "Are Virtual Events Still a Thing?",
    transcriptSummary: "Discusses hybrid ROI and audience fatigue.",
    transcriptStatus: "available",
    thumbnailStatus: "ready",
    shortsCount: 3,
    readyShortsCount: 1,
    notes: "Reels in progress with Brandon.",
  },
  libraryItems: [
    { recordId: "lib_demo_voice", name: "Sage tone primer", type: "voice_rules", status: "approved", bucket: "voice_style" },
    { recordId: "lib_swipe", name: "Swipe example", type: "swipe", status: "active", bucket: "swipe_file" },
  ],
});

export const defaultAgentRuntimeStates: AgentRuntimeStateRecord[] = [
  { agentId: "campaign_intake", status: "complete", isRunning: false, lastStartedAt: now - 1000 * 60 * 45, lastFinishedAt: now - 1000 * 60 * 44, lastRunId: "run-campaign-intake-001", lastOutputSummary: "Weekly launch brief normalized for downstream copy agents.", updatedAt: now - 1000 * 60 * 44 },
  { agentId: "strategist", status: "ready", isRunning: false, lastStartedAt: now - 1000 * 60 * 40, lastFinishedAt: now - 1000 * 60 * 39, lastRunId: "run-strategist-001", lastOutputSummary: "Campaign angle + success metric captured for the launch packet.", updatedAt: now - 1000 * 60 * 39 },
  { agentId: "audience_agent", status: "running", isRunning: true, currentTaskLabel: "Scouting segment + hook context", currentTaskDetail: "Comparing weekly-launch audience fit, exclusions, and short-form angles (demo heuristics).", lastStartedAt: now - 1000 * 60 * 3, lastRunId: "run-audience-002", lastOutputSummary: "Previous segment fit score: 0.88", updatedAt: now - 1000 * 45 },
  { agentId: "offer_agent", status: "ready", isRunning: false, lastStartedAt: now - 1000 * 60 * 37, lastFinishedAt: now - 1000 * 60 * 36, lastRunId: "run-offer-001", lastOutputSummary: "Free SAGE Strategy Call remains the approved offer for this packet.", updatedAt: now - 1000 * 60 * 36 },
  { agentId: "copywriter", status: "running", isRunning: true, currentTaskLabel: "Drafting hooks + body", currentTaskDetail: "Generating subject, preview, and body variants from the heartbeat brief.", lastStartedAt: now - 1000 * 90, lastRunId: "run-copywriter-003", lastOutputSummary: "Two hook-forward subject directions generated.", updatedAt: now - 1000 * 30 },
  { agentId: "bari_voice_agent", status: "human_pause", isRunning: false, currentTaskLabel: "Waiting on Bari review", currentTaskDetail: "Founder-voice pass paused for Bari notes (escalation, not every send).", lastStartedAt: now - 1000 * 60 * 30, lastFinishedAt: now - 1000 * 60 * 28, lastRunId: "run-bari-voice-001", lastOutputSummary: "Voice confidence 74%; review requested.", updatedAt: now - 1000 * 60 * 28 },
  { agentId: "brand_rules_checker", status: "pending", isRunning: false, currentTaskLabel: "Queued after Bari voice", currentTaskDetail: "Will enforce SAGE capitalization and sign-off rules after voice approval.", updatedAt: now - 1000 * 60 * 10 },
  { agentId: "compliance_guard", status: "blocked", isRunning: false, currentTaskLabel: "Awaiting safer wording", currentTaskDetail: "High-risk guarantee language blocks automatic progression.", lastError: "Transformation claim flagged for Blue review.", lastRunId: "run-compliance-002", updatedAt: now - 1000 * 60 * 8 },
  { agentId: "skeptic", status: "ready", isRunning: false, lastOutputSummary: "No recent critique yet for this packet.", updatedAt: now - 1000 * 60 * 7 },
  { agentId: "performance_agent", status: "idle", isRunning: false, updatedAt: now - 1000 * 60 * 6 },
  { agentId: "approval_router", status: "ready", isRunning: false, lastOutputSummary: "Bari / Blue / internal routes prepared from prior checks (sparse Blue use).", updatedAt: now - 1000 * 60 * 5 },
  { agentId: "human_approval", status: "pending", isRunning: false, currentTaskLabel: "Awaiting approval items", currentTaskDetail: "Waiting for Approval Router to emit authoritative human gates.", updatedAt: now - 1000 * 60 * 4 },
  { agentId: "keap_zapier_prep", status: "idle", isRunning: false, updatedAt: now - 1000 * 60 * 3 },
  { agentId: "response_classifier", status: "ready", isRunning: false, lastOutputSummary: "Latest reply matched to Weekly Launch — Virtual Event Cost Shift.", updatedAt: now - 1000 * 60 * 2 },
  { agentId: "performance_reporter", status: "idle", isRunning: false, updatedAt: now - 1000 * 60 },
  { agentId: "learning_agent", status: "ready", isRunning: false, lastOutputSummary: "Cost-comparison hooks remain a candidate learning for Performance Intelligence notes.", updatedAt: now },
];

export const defaultAgentRuns: AgentRunRecord[] = [
  {
    runId: "run-copy-pipeline-dry-001",
    campaignId: "camp_reactivation_may",
    agentId: "copy_pipeline",
    status: "complete",
    groupId: "copy_intelligence",
    runType: "copy_pipeline",
    safetyMode: "draft_only",
    appliedToCampaign: false,
    reviewRequired: true,
    inputSnapshot: prettyJson(demoCopyPipelineRun.inputMeta),
    outputSummary:
      "Generated draft packet for YouTube copy, Emailmarketing.com brief, Brandon creative brief, and social rollout captions. No external send/post action was taken.",
    outputJson: prettyJson(demoCopyPipelineRun.body),
    startedAt: now - 1000 * 120,
    finishedAt: now - 1000 * 119,
  },
  {
    runId: "run-copywriter-003",
    campaignId: "camp_reactivation_may",
    agentId: "copywriter",
    status: "running",
    inputSnapshot: "Weekly launch brief + virtual-event cost-shift audience + Free SAGE Strategy Call",
    outputSummary: "Generating subject and body variants.",
    outputJson: prettyJson({ stage: "drafting", variants: 2 }),
    startedAt: now - 1000 * 90,
  },
  {
    runId: "run-bari-voice-001",
    campaignId: "camp_reactivation_may",
    agentId: "bari_voice_agent",
    status: "human_pause",
    inputSnapshot: "Initial copywriter draft",
    outputSummary: "Voice confidence 74%, awaiting Bari review.",
    outputJson: prettyJson({ signoff: "You can do this — Bari", confidence: 0.74 }),
    startedAt: now - 1000 * 60 * 30,
    finishedAt: now - 1000 * 60 * 28,
  },
  {
    runId: "run-compliance-002",
    campaignId: "camp_webinar_june",
    agentId: "compliance_guard",
    status: "blocked",
    inputSnapshot: "September registration warmup invitation copy",
    outputSummary: "Blocked on guarantee-style wording.",
    outputJson: prettyJson({ flags: ["transformation claim"], riskLevel: "red" }),
    startedAt: now - 1000 * 60 * 11,
    finishedAt: now - 1000 * 60 * 8,
    error: "High-risk claim requires Blue review.",
  },
  {
    runId: "run-response-classifier-001",
    campaignId: "camp_reactivation_may",
    agentId: "response_classifier",
    status: "complete",
    inputSnapshot: "Lead reply asking if SAGE is beginner-friendly",
    outputSummary: "Interested with question; medium urgency.",
    outputJson: prettyJson({ intent: "interested_with_question", urgency: "medium", sentiment: "positive" }),
    startedAt: now - 1000 * 60 * 20,
    finishedAt: now - 1000 * 60 * 19,
  },
];

export function getDefaultAgentConfig(agentId: string) {
  return defaultAgentConfigs.find((config) => config.agentId === agentId);
}

export function getDefaultAgentRuntimeState(agentId: string) {
  return defaultAgentRuntimeStates.find((state) => state.agentId === agentId);
}

export function getAgentExecutionConfig(agentId: string) {
  return getDefaultAgentConfig(agentId);
}

export function buildAgentRuntimeContext(agentId: string) {
  return {
    config: getDefaultAgentConfig(agentId),
    runtime: getDefaultAgentRuntimeState(agentId),
    recentRuns: defaultAgentRuns.filter((run) => run.agentId === agentId),
  };
}

export function updateAgentRuntimeStatus(
  agentId: string,
  patch: Partial<AgentRuntimeStateRecord>,
) {
  const base = getDefaultAgentRuntimeState(agentId);
  if (!base) return null;
  return {
    ...base,
    ...patch,
    agentId,
    updatedAt: Date.now(),
  };
}
