/**
 * Campaign Heartbeat — deterministic scheduler/checker (Section 3).
 * Reads Weekly Launch Packet fields only; no external calls.
 */

import type { Campaign } from "@/lib/domain";

export type HeartbeatCheckType = "daily" | "friday_readiness" | "manual" | "campaign_detail_check";

export type HeartbeatRunStatus = "clear" | "needs_attention" | "at_risk" | "blocked" | "no_active_campaign";

export type HeartbeatRuleDay = "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "weekend";

export type HeartbeatTaskRisk = "low" | "medium" | "high" | "blocked";

export type HeartbeatTaskSpec = {
  dedupeKey: string;
  title: string;
  context: string;
  category: string;
  taskCategory: string;
  ownerLabel: string;
  ownerType: string;
  externalDependency?: string;
  destinationRoute: string;
  hbRisk: HeartbeatTaskRisk;
  autoGenerated: true;
  generatedBy: "campaign_heartbeat";
};

export type ApprovalSnapshot = {
  linkedCampaignId?: string;
  owner: "bari" | "blue" | "internal";
  status: string;
  type: string;
};

export type ProductionBridgeAssetHeartbeat = {
  productionAssetId: string;
  assetType?: string;
  status?: string;
  readinessStatus?: string;
  transcriptStatus?: string;
  thumbnailStatus?: string;
  shortsCount?: number;
  readyShortsCount?: number;
  lastSyncedAt?: number;
};

export type HeartbeatEvaluationInput = {
  campaigns: Campaign[];
  approvals: ApprovalSnapshot[];
  checkType: HeartbeatCheckType;
  /** Public campaign id — when set, heartbeat targets this row (campaign detail check). */
  explicitCampaignId?: string;
  /** Calendar date for dedupe + display, YYYY-MM-DD (local or override). */
  checkDate: string;
  nowMs: number;
  /** Cached Production Bridge rows (optional). */
  productionAssets?: ProductionBridgeAssetHeartbeat[];
};

export type HeartbeatEvaluationResult = {
  checkId: string;
  campaignId: string | null;
  campaignConvexId?: string;
  campaignName: string;
  checkDate: string;
  weekday: string;
  checkType: HeartbeatCheckType;
  status: HeartbeatRunStatus;
  currentCheckpoint: string;
  summary: string;
  completedItems: string[];
  missingItems: string[];
  riskItems: string[];
  blockerItems: string[];
  recommendedActions: string[];
  taskSpecs: HeartbeatTaskSpec[];
  readinessStatusBefore?: string;
  readinessStatusAfter: string | null;
  readinessReasons: string[];
  campaignHeartbeatStatus: "clear" | "needs_attention" | "at_risk" | "blocked" | "no_check";
  additionalLaunchPacketsNote?: string;
};

const KIND_ALLOW = new Set([
  "",
  "weekly_content_launch",
  "weekly_launch",
  "event_campaign",
  "email_campaign",
  "social_campaign",
  "ad_campaign",
  "content_repurpose",
  "manual_campaign",
]);

const LAUNCH_ALLOW = new Set([
  "",
  "youtube_full_video",
  "mixed_campaign",
  "shorts_rollout",
  "email_push",
  "social_rollout",
  "registration_push",
]);

const HANDOFF_READY = new Set(["ready_to_send", "sent", "confirmed"]);

const TERMINAL_READINESS = new Set(["complete", "launched"]);

const NOT_STARTED = new Set(["", "not_started", "not_requested", "not_selected"]);

function nz(s?: string) {
  return (s ?? "").trim();
}

function hasText(s?: string) {
  return nz(s).length > 0;
}

function hasSourceAsset(c: Campaign) {
  return hasText(c.sourceProductionAssetId) || hasText(c.sourceProductionAssetTitle) || hasText(c.sourceProductionAssetUrl);
}

function calendarWeekdayLower(d: Date): string {
  const days = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"] as const;
  return days[d.getDay()];
}

function formatCheckDate(d: Date) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

export function resolveCheckDate(nowMs: number, currentDateOverride?: string) {
  if (currentDateOverride && /^\d{4}-\d{2}-\d{2}$/.test(currentDateOverride)) {
    return currentDateOverride;
  }
  return formatCheckDate(new Date(nowMs));
}

export function selectActiveLaunchCampaign(campaigns: Campaign[], checkDate: string): Campaign | null {
  const candidates = campaigns.filter((c) => {
    if (c.archived || c.status === "archived") return false;
    if (TERMINAL_READINESS.has(nz(c.readinessStatus))) return false;
    const kind = nz(c.campaignKind);
    const lt = nz(c.launchType);
    if (kind && !KIND_ALLOW.has(kind)) return false;
    if (lt && !LAUNCH_ALLOW.has(lt)) return false;
    const pub = nz(c.publishDate);
    if (pub && pub < checkDate) return false;
    return true;
  });
  candidates.sort((a, b) => {
    const pa = nz(a.publishDate) || "9999-12-31";
    const pb = nz(b.publishDate) || "9999-12-31";
    if (pa !== pb) return pa.localeCompare(pb);
    return a.sortOrder - b.sortOrder;
  });
  return candidates[0] ?? null;
}

function countAdditionalActive(campaigns: Campaign[], primary: Campaign | null, checkDate: string) {
  if (!primary) return 0;
  return campaigns.filter((c) => {
    if (c.id === primary.id) return false;
    if (c.archived || c.status === "archived") return false;
    if (TERMINAL_READINESS.has(nz(c.readinessStatus))) return false;
    const kind = nz(c.campaignKind);
    const lt = nz(c.launchType);
    if (kind && !KIND_ALLOW.has(kind)) return false;
    if (lt && !LAUNCH_ALLOW.has(lt)) return false;
    const pub = nz(c.publishDate);
    if (pub && pub < checkDate) return false;
    return true;
  }).length;
}

function resolveRuleDay(weekday: string, checkType: HeartbeatCheckType): HeartbeatRuleDay {
  if (checkType === "friday_readiness") return "friday";
  if (weekday === "saturday" || weekday === "sunday") return "weekend";
  return weekday as HeartbeatRuleDay;
}

function checkpointLabel(day: HeartbeatRuleDay): string {
  switch (day) {
    case "monday":
      return "Monday selection and strategy";
    case "tuesday":
      return "Tuesday packet drafting";
    case "wednesday":
      return "Wednesday scheduling and handoffs";
    case "thursday":
      return "Thursday follow-up and finalization";
    case "friday":
      return "Friday readiness confirmation";
    default:
      return "Weekend monitoring";
  }
}

function isApprovalPending(s: string) {
  return s === "pending" || s === "changes_requested";
}

function pendingApprovalsForCampaign(approvals: ApprovalSnapshot[], campaignId: string) {
  return approvals.filter((a) => a.linkedCampaignId === campaignId && isApprovalPending(a.status));
}

function socialRolloutDrafted(c: Campaign) {
  const sc = nz(c.socialCopyStatus);
  if (sc && !NOT_STARTED.has(sc)) return true;
  return hasText(c.rolloutNotes) || hasText(c.metaCaption) || hasText(c.instagramCaption);
}

function rolloutCadenceDrafted(c: Campaign) {
  const rc = nz(c.rolloutCadenceStatus);
  return rc.length > 0 && !NOT_STARTED.has(rc);
}

function shortsTracked(c: Campaign) {
  const s = nz(c.shortsStatus);
  return ["requested", "in_progress", "first_draft_received", "revisions_needed", "ready", "scheduled", "published"].includes(s);
}

function mapHbRiskToPriority(r: HeartbeatTaskRisk): "green" | "amber" | "red" | "blue" | "gray" {
  if (r === "blocked" || r === "high") return "red";
  if (r === "medium") return "amber";
  return "green";
}

export function mapHeartbeatRiskToTaskPriority(r: HeartbeatTaskRisk): "green" | "amber" | "red" | "blue" | "gray" {
  return mapHbRiskToPriority(r);
}

export function destinationModeForHeartbeatRoute(route: string): "campaign" | "review" | "library" | "intelligence" | "operations" {
  if (route.startsWith("/reviews")) return "review";
  if (route.startsWith("/libraries")) return "library";
  if (route.startsWith("/intelligence")) return "intelligence";
  if (route.startsWith("/operations")) return "operations";
  return "campaign";
}

function taskDedupe(campaignId: string | "none", checkDate: string, dayKey: string, slug: string) {
  return `heartbeat:${campaignId}:${checkDate}:${dayKey}:${slug}`;
}

export function stableTaskIdFromDedupe(dedupeKey: string) {
  const safe = dedupeKey.replace(/[^a-zA-Z0-9_-]/g, "_");
  return `hb_${safe.slice(0, 180)}`;
}

function pushTask(
  list: HeartbeatTaskSpec[],
  spec: Omit<HeartbeatTaskSpec, "autoGenerated" | "generatedBy">,
) {
  list.push({ ...spec, autoGenerated: true, generatedBy: "campaign_heartbeat" });
}

function evaluateWeekend(c: Campaign, checkDate: string, tasks: HeartbeatTaskSpec[], completed: string[]) {
  const readiness = nz(c.readinessStatus);
  const bl = c.blockers ?? [];
  const urgent = readiness === "blocked" || bl.length > 0;
  if (urgent) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "weekend", "blocked_review"),
      title: "Review blocked launch packet before Monday",
      context: "Weekend checkpoint: a blocked packet should be reviewed so Monday prep is not surprised.",
      category: "Readiness",
      taskCategory: "readiness",
      ownerLabel: "Brett",
      ownerType: "internal_user",
      destinationRoute: `/campaigns/${c.id}#packet-blockers`,
      hbRisk: "high",
    });
  } else {
    completed.push("Weekend: no urgent blocked-launch task required.");
  }
}

function hasYoutubeStyleLaunch(c: Campaign) {
  const lt = nz(c.launchType);
  const kind = nz(c.campaignKind);
  return lt === "youtube_full_video" || kind.includes("weekly");
}

function buildProductionAssetMap(rows: ProductionBridgeAssetHeartbeat[] | undefined) {
  const map = new Map<string, ProductionBridgeAssetHeartbeat>();
  for (const row of rows ?? []) {
    map.set(row.productionAssetId, row);
  }
  return map;
}

function applyProductionBridgeLayer(
  c: Campaign,
  assetMap: Map<string, ProductionBridgeAssetHeartbeat>,
  risk: string[],
  blockers: string[],
  tasks: HeartbeatTaskSpec[],
  checkDate: string,
  nowMs: number,
) {
  if (!hasSourceAsset(c)) return;

  const assetId = nz(c.sourceProductionAssetId);
  const cached = assetId ? assetMap.get(assetId) : undefined;

  if (assetId && !cached) {
    risk.push("Production Bridge cache has no matching asset; launch packet snapshot fields are still used.");
  }

  const effType = cached?.assetType;
  const effStatus = cached?.status ?? "";
  const effReadiness = cached?.readinessStatus ?? "";
  const effTranscript = nz(cached?.transcriptStatus ?? c.transcriptStatus);
  const effThumb = nz(cached?.thumbnailStatus ?? c.thumbnailStatus);
  const shortsTotal = cached?.shortsCount;
  const shortsReady = cached?.readyShortsCount ?? 0;

  if (effReadiness === "blocked" || effStatus === "blocked") {
    blockers.push("Linked production asset is blocked.");
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "pbridge", "asset_blocked"),
      title: "Resolve blocked source asset",
      context: "The linked Production Bridge asset is marked blocked. Production Hub remains authoritative — unblock or swap the source asset reference.",
      category: "Production",
      taskCategory: "production",
      ownerLabel: "Brett",
      ownerType: "internal_user",
      destinationRoute: `/campaigns/${c.id}#packet-source`,
      hbRisk: "blocked",
    });
  }

  if (hasYoutubeStyleLaunch(c) && cached && effType && effType !== "full_video") {
    risk.push("Linked Production Bridge asset is not a full video — confirm the correct master for this launch.");
  }

  const readinessOk = ["ready_for_campaign", "ready_for_publish"].includes(effReadiness);
  if (cached && effReadiness && !readinessOk && effReadiness !== "unknown" && effReadiness !== "blocked") {
    risk.push("Linked production asset is not marked ready for campaign use.");
  }

  if (hasYoutubeStyleLaunch(c)) {
    if (effTranscript && !["not_required", "approved", "imported", "available"].includes(effTranscript)) {
      risk.push("Transcript is missing or not ready yet, which may slow copy generation.");
    }
    if (effThumb && !["not_required", "approved", "ready"].includes(effThumb)) {
      risk.push("Thumbnail is missing, draft, or not approved.");
    }
  }

  if (typeof shortsTotal === "number" && shortsTotal > 0 && shortsReady === 0) {
    risk.push("No related shorts/reels are marked ready yet.");
  }

  const last = cached?.lastSyncedAt;
  if (typeof last === "number") {
    const ageMs = nowMs - last;
    if (ageMs > 14 * 24 * 60 * 60 * 1000) {
      risk.push("Production Bridge reference may be stale (last sync over 14 days ago).");
    }
  }
}

function evaluateMonday(c: Campaign, checkDate: string, tasks: HeartbeatTaskSpec[], missing: string[], completed: string[]) {
  if (!hasSourceAsset(c)) missing.push("Source asset is not selected or entered.");
  if (!hasText(c.publishDate)) missing.push("Publish date is not set.");
  if (!hasText(c.campaignAngle)) missing.push("Campaign angle is not defined.");
  if (!hasText(c.primaryAudience)) missing.push("Primary audience is not defined.");
  if (!hasText(c.primaryCta)) missing.push("Primary CTA is not defined.");

  if (hasSourceAsset(c)) completed.push("Source asset reference is present.");
  if (hasText(c.publishDate)) completed.push("Publish date is set.");
  if (hasText(c.campaignAngle)) completed.push("Campaign angle is defined.");

  if (!hasSourceAsset(c)) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "monday", "select_source_asset"),
      title: "Select or enter the source asset",
      context: "The launch packet needs a source video or asset before copy, handoffs, and rollout planning can be completed.",
      category: "Planning",
      taskCategory: "planning",
      ownerLabel: "Brett",
      ownerType: "internal_user",
      destinationRoute: `/campaigns/${c.id}#packet-source`,
      hbRisk: "medium",
    });
  }
  if (!hasText(c.campaignAngle) || !hasText(c.primaryAudience) || !hasText(c.primaryCta)) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "monday", "angle_audience_cta"),
      title: "Define the campaign angle, audience, and CTA",
      context: "The launch packet needs a clear angle, audience, and CTA before copy and handoffs can be finalized.",
      category: "Planning",
      taskCategory: "planning",
      ownerLabel: "Brett",
      ownerType: "internal_user",
      destinationRoute: `/campaigns/${c.id}#packet-overview`,
      hbRisk: "medium",
    });
  }
  if (!hasText(c.youtubeTitle) && !hasText(c.emailBriefBody)) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "monday", "start_packet_copy"),
      title: "Start first-pass launch packet copy",
      context: "Drafting YouTube copy and briefs early keeps Tuesday/Wednesday handoffs realistic.",
      category: "Copy",
      taskCategory: "copy",
      ownerLabel: "Brett",
      ownerType: "internal_user",
      destinationRoute: `/campaigns/${c.id}#packet-youtube`,
      hbRisk: "low",
    });
  }
}

function evaluateTuesday(c: Campaign, checkDate: string, tasks: HeartbeatTaskSpec[], missing: string[], completed: string[]) {
  if (!hasText(c.youtubeTitle) || !hasText(c.youtubeDescription)) missing.push("YouTube copy is not drafted.");
  if (!hasText(c.emailBriefBody)) missing.push("Emailmarketing.com brief is not drafted.");
  if (!hasText(c.creativeBriefBody)) missing.push("Creative handoff brief is not drafted.");
  if (!socialRolloutDrafted(c)) missing.push("Social rollout copy is not drafted.");
  if (!rolloutCadenceDrafted(c)) missing.push("Rollout cadence is not drafted.");

  if (hasText(c.youtubeTitle) && hasText(c.youtubeDescription)) completed.push("YouTube title and description are drafted.");

  if (!hasText(c.youtubeTitle) || !hasText(c.youtubeDescription)) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "tuesday", "youtube_copy"),
      title: "Draft the YouTube title and description",
      context: "The full-video release needs YouTube copy before the video can be scheduled and used as the email CTA.",
      category: "Copy",
      taskCategory: "copy",
      ownerLabel: "Brett",
      ownerType: "internal_user",
      destinationRoute: `/campaigns/${c.id}#packet-youtube`,
      hbRisk: "medium",
    });
  }
  if (!hasText(c.emailBriefBody)) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "tuesday", "email_brief"),
      title: "Draft the Emailmarketing.com brief",
      context: "Emailmarketing.com needs the campaign angle, CTA, and scheduled video link direction to build the promotional email sequence.",
      category: "Handoff",
      taskCategory: "handoff",
      ownerLabel: "Brett",
      ownerType: "internal_user",
      externalDependency: "Emailmarketing.com",
      destinationRoute: `/campaigns/${c.id}#packet-email`,
      hbRisk: "medium",
    });
  }
  if (!hasText(c.creativeBriefBody)) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "tuesday", "creative_brief"),
      title: "Draft the creative handoff brief",
      context: "The creative owner needs reel/short-form direction early enough to prepare supporting content before launch week.",
      category: "Handoff",
      taskCategory: "handoff",
      ownerLabel: "Brett",
      ownerType: "internal_user",
      externalDependency: "Brandon",
      destinationRoute: `/campaigns/${c.id}#packet-creative`,
      hbRisk: "medium",
    });
  }
  if (!socialRolloutDrafted(c) || !rolloutCadenceDrafted(c)) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "tuesday", "social_rollout"),
      title: "Finalize social captions and rollout cadence",
      context: "The supporting posts, reels captions, and platform cadence should be drafted before mid-week handoffs.",
      category: "Social",
      taskCategory: "social",
      ownerLabel: "Kelsey",
      ownerType: "internal_user",
      destinationRoute: `/campaigns/${c.id}#packet-social`,
      hbRisk: "medium",
    });
  }
}

function evaluateWednesday(c: Campaign, checkDate: string, tasks: HeartbeatTaskSpec[], missing: string[], completed: string[]) {
  if (!hasText(c.youtubeScheduledUrl)) missing.push("Scheduled YouTube link is missing.");
  const eb = nz(c.emailBriefStatus);
  if (!HANDOFF_READY.has(eb)) missing.push("Emailmarketing.com brief is not ready or sent.");
  const cb = nz(c.creativeBriefStatus);
  if (!HANDOFF_READY.has(cb)) missing.push("Creative brief is not ready or sent.");
  if (!hasText(c.creativeOwner)) missing.push("Creative owner is not assigned.");
  if (!shortsTracked(c)) missing.push("Shorts/reels have not been requested or tracked.");

  if (hasText(c.youtubeScheduledUrl)) completed.push("Scheduled YouTube link is captured.");
  if (HANDOFF_READY.has(eb)) completed.push("Email brief is ready, sent, or confirmed.");

  if (!hasText(c.youtubeScheduledUrl)) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "wednesday", "youtube_scheduled_link"),
      title: "Schedule the YouTube video and capture the link",
      context: "The scheduled YouTube link is needed for the Emailmarketing.com CTA and launch handoffs.",
      category: "Scheduling",
      taskCategory: "scheduling",
      ownerLabel: "Brett",
      ownerType: "internal_user",
      destinationRoute: `/campaigns/${c.id}#packet-youtube`,
      hbRisk: "high",
    });
  }
  if (!HANDOFF_READY.has(eb)) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "wednesday", "email_handoff_send"),
      title: "Send the scheduled link and brief to Emailmarketing.com",
      context: "The email team needs the scheduled YouTube link and campaign brief before they can prepare the promotional emails.",
      category: "Handoff",
      taskCategory: "handoff",
      ownerLabel: "Brett",
      ownerType: "internal_user",
      externalDependency: "Emailmarketing.com",
      destinationRoute: `/campaigns/${c.id}#packet-email`,
      hbRisk: "high",
    });
  }
  if (!HANDOFF_READY.has(cb)) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "wednesday", "creative_handoff_send"),
      title: "Send the creative brief",
      context: "The creative owner needs the selected video and short-form direction early enough to produce reels/shorts for the rollout.",
      category: "Handoff",
      taskCategory: "handoff",
      ownerLabel: "Brett",
      ownerType: "internal_user",
      externalDependency: "Brandon",
      destinationRoute: `/campaigns/${c.id}#packet-creative`,
      hbRisk: "high",
    });
  }
  if (!shortsTracked(c)) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "wednesday", "shorts_tracked"),
      title: "Confirm shorts/reels are requested and tracked",
      context: "Short-form deliverables should be requested with a clear status so Thursday/Friday readiness is honest.",
      category: "Production",
      taskCategory: "production",
      ownerLabel: "Kelsey",
      ownerType: "internal_user",
      externalDependency: "Brandon",
      destinationRoute: `/campaigns/${c.id}#packet-creative`,
      hbRisk: "medium",
    });
  }
}

function evaluateThursday(
  c: Campaign,
  checkDate: string,
  tasks: HeartbeatTaskSpec[],
  missing: string[],
  risk: string[],
  approvals: ApprovalSnapshot[],
) {
  const eb = nz(c.emailBriefStatus);
  const cb = nz(c.creativeBriefStatus);
  if (eb === "drafted" || eb === "ready_to_send") risk.push("Emailmarketing.com handoff may not be confirmed.");
  if (cb === "drafted" || cb === "ready_to_send") risk.push("Creative handoff may not be confirmed.");
  if (nz(c.shortsStatus) === "requested") risk.push("Shorts/reels status needs follow-up.");
  const sc = nz(c.socialCopyStatus);
  if (!sc || NOT_STARTED.has(sc) || sc === "draft_needed") missing.push("Social copy is not ready for rollout.");
  const rc = nz(c.rolloutCadenceStatus);
  if (!rc || NOT_STARTED.has(rc)) missing.push("Rollout cadence is missing.");
  const bl = c.blockers ?? [];
  if (bl.length) risk.push("Launch packet has listed blockers.");

  if (!["sent", "confirmed"].includes(eb)) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "thursday", "confirm_email_handoff"),
      title: "Confirm Emailmarketing.com has the brief and CTA link",
      context: "Mid-week follow-up reduces Friday surprises for the email sequence.",
      category: "Follow-up",
      taskCategory: "follow_up",
      ownerLabel: "Kelsey",
      ownerType: "internal_user",
      externalDependency: "Emailmarketing.com",
      destinationRoute: `/campaigns/${c.id}#packet-email`,
      hbRisk: "medium",
    });
  }
  if (!["sent", "confirmed"].includes(cb)) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "thursday", "confirm_creative_timeline"),
      title: "Confirm creative timeline",
      context: "Ensure the creative owner has acknowledged the brief and timeline for reels/shorts.",
      category: "Follow-up",
      taskCategory: "follow_up",
      ownerLabel: "Kelsey",
      ownerType: "internal_user",
      externalDependency: "Brandon",
      destinationRoute: `/campaigns/${c.id}#packet-creative`,
      hbRisk: "medium",
    });
  }
  if (!["drafted", "needs_review", "ready", "scheduled", "published"].includes(sc)) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "thursday", "social_finalize"),
      title: "Finalize social captions and rollout cadence",
      context: "Supporting posts and cadence should be ready or in review before Friday readiness.",
      category: "Social",
      taskCategory: "social",
      ownerLabel: "Kelsey",
      ownerType: "internal_user",
      destinationRoute: `/campaigns/${c.id}#packet-social`,
      hbRisk: "medium",
    });
  }
  pushTask(tasks, {
    dedupeKey: taskDedupe(c.id, checkDate, "thursday", "review_blockers"),
    title: "Review blockers before Friday readiness",
    context: "Clear or escalate blockers so Friday sign-off reflects reality.",
    category: "Readiness",
    taskCategory: "readiness",
    ownerLabel: "Internal",
    ownerType: "internal_user",
    destinationRoute: `/campaigns/${c.id}#packet-blockers`,
    hbRisk: bl.length ? "high" : "medium",
  });

  const pend = pendingApprovalsForCampaign(approvals, c.id);
  const internalPending = pend.filter((p) => p.owner === "internal");
  if (internalPending.length) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "thursday", "internal_approval_queue"),
      title: "Clear internal review items",
      context: "Internal approvals are still pending for this launch packet.",
      category: "Approval",
      taskCategory: "approval",
      ownerLabel: "Internal",
      ownerType: "internal_user",
      destinationRoute: "/reviews/internal",
      hbRisk: "medium",
    });
  }
}

function socialReadyFriday(c: Campaign) {
  const sc = nz(c.socialCopyStatus);
  return sc === "ready" || sc === "scheduled" || sc === "published";
}

function rolloutReadyFriday(c: Campaign) {
  const rc = nz(c.rolloutCadenceStatus);
  return rc === "approved" || rc === "scheduled" || rc === "active" || rc === "complete";
}

function shortsOkFriday(c: Campaign) {
  const s = nz(c.shortsStatus);
  return (
    ["ready", "scheduled", "published", "in_progress", "first_draft_received"].includes(s) ||
    (s === "revisions_needed" && hasText(c.relatedShortsNotes))
  );
}

function evaluateFriday(
  c: Campaign,
  checkDate: string,
  tasks: HeartbeatTaskSpec[],
  missing: string[],
  blockers: string[],
  completed: string[],
  approvals: ApprovalSnapshot[],
) {
  if (!hasSourceAsset(c)) missing.push("Source asset is not selected or entered.");
  if (!hasText(c.publishDate)) missing.push("Publish date is not set.");
  if (!hasText(c.youtubeScheduledUrl)) blockers.push("Launch cannot be marked ready because scheduled YouTube link is missing.");
  const eb = nz(c.emailBriefStatus);
  if (!["sent", "confirmed"].includes(eb)) blockers.push("Email handoff is not complete.");
  const cb = nz(c.creativeBriefStatus);
  if (!["sent", "confirmed"].includes(cb)) blockers.push("Creative handoff is not complete.");
  if (!socialReadyFriday(c)) missing.push("Social copy is not ready.");
  if (!rolloutReadyFriday(c)) missing.push("Rollout cadence is not ready.");
  if (!shortsOkFriday(c)) missing.push("Shorts/reels are not ready or clearly tracked.");
  const pend = pendingApprovalsForCampaign(approvals, c.id);
  if (pend.length) missing.push("Required approvals are still pending.");
  const bl = c.blockers ?? [];
  if (bl.length) blockers.push("Launch packet has unresolved blockers.");

  const hasGaps = missing.length > 0 || blockers.length > 0 || pend.length > 0;
  if (!hasGaps) {
    completed.push("Friday readiness: core checklist passed for scheduled link, handoffs, social, and approvals.");
    return;
  }

  pushTask(tasks, {
    dedupeKey: taskDedupe(c.id, checkDate, "friday", "readiness_review"),
    title: "Complete Friday launch readiness review",
    context: "Confirm that next week’s launch packet has the scheduled video link, email handoff, creative handoff, social rollout, and blockers accounted for.",
    category: "Readiness",
    taskCategory: "readiness",
    ownerLabel: "Internal",
    ownerType: "internal_user",
    destinationRoute: `/campaigns/${c.id}#packet-blockers`,
    hbRisk: "high",
  });
  if (bl.length || blockers.length) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "friday", "resolve_blockers"),
      title: "Resolve launch packet blockers",
      context: "This launch packet has blockers that may prevent it from being ready for the next release window.",
      category: "Readiness",
      taskCategory: "readiness",
      ownerLabel: "Brett",
      ownerType: "internal_user",
      destinationRoute: `/campaigns/${c.id}#packet-blockers`,
      hbRisk: "blocked",
    });
  }
  pushTask(tasks, {
    dedupeKey: taskDedupe(c.id, checkDate, "friday", "confirm_ready_next_week"),
    title: "Confirm launch packet is ready for next week",
    context: "Friday sign-off: scheduled link, handoffs, social, and approvals are either complete or consciously accepted.",
    category: "Readiness",
    taskCategory: "readiness",
    ownerLabel: "Brett",
    ownerType: "internal_user",
    destinationRoute: `/campaigns/${c.id}#packet-overview`,
    hbRisk: "medium",
  });

  const bariItems = pend.filter((p) => p.owner === "bari");
  const blueItems = pend.filter((p) => p.owner === "blue");

  if (bariItems.length) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "friday", "bari_founder_voice"),
      title: "Founder voice review (Bari)",
      context: "A founder-voice approval is pending or a blocker explicitly calls for Bari.",
      category: "Approval",
      taskCategory: "approval",
      ownerLabel: "Bari",
      ownerType: "reviewer",
      destinationRoute: "/reviews/bari",
      hbRisk: "high",
    });
  }
  if (blueItems.length) {
    pushTask(tasks, {
      dedupeKey: taskDedupe(c.id, checkDate, "friday", "blue_strategy"),
      title: "Strategy / claims review (Blue)",
      context: "A strategy or claims approval is pending or a blocker explicitly calls for Blue.",
      category: "Approval",
      taskCategory: "approval",
      ownerLabel: "Blue",
      ownerType: "reviewer",
      destinationRoute: "/reviews/blue",
      hbRisk: "high",
    });
  }
}

function noActiveCampaignEvaluation(checkDate: string, checkType: HeartbeatCheckType): HeartbeatEvaluationResult {
  const checkId = `heartbeat_${checkDate}_${Math.random().toString(36).slice(2, 10)}`;
  const taskSpecs: HeartbeatTaskSpec[] = [
    {
      dedupeKey: taskDedupe("none", checkDate, "none", "create_launch_packet"),
      title: "Create or select the next Weekly Launch Packet",
      context: "The Campaign Heartbeat could not find an active upcoming launch packet to check.",
      category: "Planning",
      taskCategory: "planning",
      ownerLabel: "Brett",
      ownerType: "internal_user",
      destinationRoute: "/campaigns/new",
      hbRisk: "medium",
      autoGenerated: true,
      generatedBy: "campaign_heartbeat",
    },
  ];
  return {
    checkId,
    campaignId: null,
    campaignName: "—",
    checkDate,
    weekday: calendarWeekdayLower(new Date(`${checkDate}T12:00:00`)),
    checkType,
    status: "no_active_campaign",
    currentCheckpoint: "No active launch packet",
    summary: "No active launch packet found. Create or select the next Weekly Launch Packet so the heartbeat can track daily readiness.",
    completedItems: [],
    missingItems: ["No qualifying upcoming launch packet in scope."],
    riskItems: [],
    blockerItems: [],
    recommendedActions: ["Create a Weekly Launch Packet with a future publish date.", "Open Campaigns and confirm campaign kind and launch type."],
    taskSpecs,
    readinessStatusBefore: undefined,
    readinessStatusAfter: null,
    readinessReasons: [],
    campaignHeartbeatStatus: "no_check",
  };
}

function deriveAggregateStatus(params: {
  missing: string[];
  risk: string[];
  blockers: string[];
  hasCampaign: boolean;
}): HeartbeatRunStatus {
  if (!params.hasCampaign) return "no_active_campaign";
  if (params.blockers.length) return "blocked";
  const highRisk = params.missing.some((m) => /scheduled YouTube|handoff is not complete|cannot be marked ready/i.test(m));
  if (highRisk && params.missing.length) return "at_risk";
  if (params.missing.length > 2) return "at_risk";
  if (params.missing.length || params.risk.length) return "needs_attention";
  return "clear";
}

function deriveCampaignHeartbeatStatus(status: HeartbeatRunStatus): HeartbeatEvaluationResult["campaignHeartbeatStatus"] {
  if (status === "no_active_campaign") return "no_check";
  if (status === "clear") return "clear";
  if (status === "blocked") return "blocked";
  if (status === "at_risk") return "at_risk";
  return "needs_attention";
}

function deriveReadinessAfter(c: Campaign, status: HeartbeatRunStatus, blockers: string[], missing: string[]): string | null {
  const cur = nz(c.readinessStatus);
  if (cur === "launched" || cur === "complete") return null;
  if (cur === "archived") return null;
  if (status === "no_active_campaign") return null;
  if (status === "blocked") {
    if (cur === "blocked") return null;
    return "blocked";
  }
  if (status === "at_risk" || status === "needs_attention") {
    if (cur === "blocked") return null;
    if (["ready", "launched", "complete"].includes(cur)) return null;
    return "at_risk";
  }
  if (status === "clear") {
    if (cur === "blocked") return null;
    if (blockers.length === 0 && missing.length === 0) return "ready";
  }
  return null;
}

function buildSummary(
  status: HeartbeatRunStatus,
  day: HeartbeatRuleDay,
  c: Campaign | null,
  missing: string[],
  blockers: string[],
) {
  const ck = checkpointLabel(day);
  if (status === "no_active_campaign") {
    return "No active launch packet found. Create or select the next Weekly Launch Packet so the heartbeat can track daily readiness.";
  }
  if (status === "clear") return `Launch prep is on track for ${ck}. The active launch packet (${c?.name}) has the expected pieces for this stage.`;
  if (status === "blocked")
    return `${ck}: this launch packet is blocked — ${blockers[0] ?? missing[0] ?? "review blockers and handoffs"}.`;
  if (status === "at_risk")
    return `${ck}: this launch packet is at risk — ${missing.slice(0, 2).join("; ") || "review missing fields"}.`;
  return `${ck}: this launch packet needs attention — ${missing[0] ?? "complete outstanding checklist items"}.`;
}

export function runHeartbeatEvaluation(input: HeartbeatEvaluationInput): HeartbeatEvaluationResult {
  const { campaigns, approvals, checkType, explicitCampaignId, checkDate, nowMs, productionAssets } = input;
  const weekday = calendarWeekdayLower(new Date(nowMs));
  const ruleDay = resolveRuleDay(weekday, checkType);
  const assetMap = buildProductionAssetMap(productionAssets);

  let primary: Campaign | null = null;
  if (explicitCampaignId) {
    primary = campaigns.find((c) => c.id === explicitCampaignId) ?? null;
    if (!primary) {
      const checkId = `heartbeat_${checkDate}_${Math.random().toString(36).slice(2, 10)}`;
      return {
        checkId,
        campaignId: explicitCampaignId,
        campaignName: "Not found",
        checkDate,
        weekday: calendarWeekdayLower(new Date(nowMs)),
        checkType,
        status: "no_active_campaign",
        currentCheckpoint: "Campaign detail check",
        summary: "Campaign Heartbeat could not find that launch packet in the current workspace.",
        completedItems: [],
        missingItems: ["Campaign record not found for this id."],
        riskItems: [],
        blockerItems: [],
        recommendedActions: ["Return to Campaigns and pick an existing Weekly Launch Packet."],
        taskSpecs: [],
        readinessStatusBefore: undefined,
        readinessStatusAfter: null,
        readinessReasons: [],
        campaignHeartbeatStatus: "no_check",
      };
    }
  } else {
    primary = selectActiveLaunchCampaign(campaigns, checkDate);
  }

  if (!primary) {
    return noActiveCampaignEvaluation(checkDate, checkType);
  }

  const additional = countAdditionalActive(campaigns, primary, checkDate);
  const additionalNote =
    additional > 0
      ? `${additional} additional upcoming launch packet(s) exist; only the nearest publish date is checked in this run.`
      : undefined;

  const missing: string[] = [];
  const risk: string[] = [];
  const blockers: string[] = [];
  const completed: string[] = [];
  const tasks: HeartbeatTaskSpec[] = [];

  if (ruleDay === "weekend") {
    const readiness = nz(primary.readinessStatus);
    const bl = primary.blockers ?? [];
    if (readiness === "blocked" || bl.length > 0) {
      risk.push("Launch packet may still need attention before Monday.");
    }
    evaluateWeekend(primary, checkDate, tasks, completed);
  } else if (ruleDay === "monday") {
    evaluateMonday(primary, checkDate, tasks, missing, completed);
  } else if (ruleDay === "tuesday") {
    evaluateTuesday(primary, checkDate, tasks, missing, completed);
  } else if (ruleDay === "wednesday") {
    evaluateWednesday(primary, checkDate, tasks, missing, completed);
  } else if (ruleDay === "thursday") {
    evaluateThursday(primary, checkDate, tasks, missing, risk, approvals);
  } else if (ruleDay === "friday") {
    evaluateFriday(primary, checkDate, tasks, missing, blockers, completed, approvals);
  }

  applyProductionBridgeLayer(primary, assetMap, risk, blockers, tasks, checkDate, nowMs);

  const status = deriveAggregateStatus({ missing, risk, blockers, hasCampaign: true });
  const readinessBefore = nz(primary.readinessStatus);
  const readinessAfter = deriveReadinessAfter(primary, status, blockers, missing);
  const readinessReasons = [...missing, ...blockers].slice(0, 8);
  const summary = buildSummary(status, ruleDay, primary, missing, blockers);
  const checkId = `heartbeat_${checkDate}_${Math.random().toString(36).slice(2, 10)}`;

  const recommendedActions = [
    ...tasks.slice(0, 6).map((t) => t.title),
    ...(additionalNote ? [additionalNote] : []),
  ];

  return {
    checkId,
    campaignId: primary.id,
    campaignName: primary.name,
    checkDate,
    weekday,
    checkType,
    status,
    currentCheckpoint: checkpointLabel(ruleDay),
    summary: additionalNote ? `${summary} ${additionalNote}` : summary,
    completedItems: completed,
    missingItems: missing,
    riskItems: risk,
    blockerItems: blockers,
    recommendedActions,
    taskSpecs: tasks,
    readinessStatusBefore: readinessBefore || undefined,
    readinessStatusAfter: readinessAfter,
    readinessReasons,
    campaignHeartbeatStatus: deriveCampaignHeartbeatStatus(status),
    additionalLaunchPacketsNote: additionalNote,
  };
}

export function convexRowToApprovalSnapshot(row: {
  linkedCampaignId?: string;
  owner: "bari" | "blue" | "internal";
  status: string;
  type: string;
}): ApprovalSnapshot {
  return {
    linkedCampaignId: row.linkedCampaignId,
    owner: row.owner,
    status: row.status,
    type: row.type,
  };
}
