import type { AgentConfigSeed } from "./agent-config";

function ci(
  agentId: string,
  displayName: string,
  shortDescription: string,
  workflowOrder: number,
  safetyMode: string,
  agentRole: string,
  inputSources: string[],
  outputTargets: string[],
  nextAgentIds: string[],
): AgentConfigSeed {
  return {
    agentId,
    displayName,
    shortDescription,
    workflowOrder,
    category: "copy_intelligence",
    groupId: "copy_intelligence",
    safetyMode,
    agentRole,
    inputSources,
    outputTargets,
    isCore: true,
    enabled: true,
    systemPrompt: `${displayName} — Section 6 Copy Intelligence stack. Human-controlled; no auto-send, post, or publish.`,
    taskPromptTemplate: "Consume structured campaign and context inputs; emit draft-only artifacts and review notes.",
    styleGuidance: "Operator-readable; label uncertainty; never present drafts as approved.",
    requiredContextSources: ["Weekly Launch Packet fields", "operator intent"],
    exampleReferences: ["intelligence/copy-intelligence"],
    preferredProvider: "demo",
    preferredModel: "copy-intelligence-dry-run",
    temperature: 0.1,
    maxTokens: 2000,
    structuredOutputRequired: true,
    inputSchema: { campaign: "object", context: "object" },
    outputSchema: { drafts: "object", notes: ["string"], safetyMode: "string" },
    requiredInputs: ["campaign"],
    optionalInputs: ["libraryContext", "productionAsset"],
    requiredOutputs: ["notes"],
    escalationMarkers: ["missing critical fields", "high-risk claim"],
    confidenceField: "layerConfidence",
    riskField: "layerRisk",
    activeRules: ["Draft-only outputs", "Human approval before external use"],
    blockingRules: ["No live sends or posts"],
    warningRules: ["Model provider may be offline — dry-run fallback"],
    allowedActions: ["analyze", "draft", "suggest", "flag risk"],
    disallowedActions: ["send email", "post social", "schedule youtube", "auto-approve"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds,
    fallbackAgentId: "human_approval",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["layer output emitted"],
    retryPolicy: "manual retry after operator edits",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: `Copy Intelligence — ${agentRole}.`,
  };
}

/** Section 6 — canonical copy pipeline agent IDs (plus orchestrator). */
export const copyIntelligenceAgentSeeds: AgentConfigSeed[] = [
  ci("copy_intake_agent", "Copy Intake Agent", "Structured copy brief from launch packet and source context.", 22, "read_only", "intake", ["campaign", "source asset"], ["copy_brief"], ["context_retrieval_agent"]),
  ci(
    "context_retrieval_agent",
    "Context Retrieval Agent",
    "Finds Library voice, audience, CTA, compliance, playbooks, learnings; labels trust levels.",
    23,
    "read_only",
    "context",
    ["campaign angle", "audience", "library"],
    ["context_pack"],
    ["angle_strategy_agent"],
  ),
  ci("angle_strategy_agent", "Angle Strategy Agent", "Strengthens campaign angle, pain point, promise framing; sparse Blue escalation.", 24, "draft_only", "angle", ["copy_brief", "context_pack"], ["angle_strategy"], ["hook_agent"]),
  ci("hook_agent", "Hook Agent (Hook Lab)", "Hooks for YouTube, email, social, reels with risk notes.", 25, "draft_only", "hooks", ["angle_strategy", "playbooks"], ["hooks"], ["voice_matching_agent"]),
  ci("voice_matching_agent", "Voice Matching Agent", "Sage tone and Bari/founder fit; Bari escalation only when warranted.", 26, "draft_only", "voice", ["drafts", "voice library"], ["voice_notes"], ["offer_cta_agent"]),
  ci("offer_cta_agent", "Offer / CTA Agent", "CTA clarity, alternatives, placement, friction notes.", 27, "draft_only", "cta", ["drafts", "offer library"], ["cta_notes"], ["structure_agent"]),
  ci("structure_agent", "Structure Agent", "Platform-specific outlines for YouTube, email, creative, social.", 28, "draft_only", "structure", ["hooks", "cta_notes"], ["structure_notes"], ["draft_generation_agent"]),
  ci("draft_generation_agent", "Draft Generation Agent", "First-pass drafts for selected channels; never auto-writes campaigns.", 29, "draft_only", "draft", ["structure_notes", "context_pack"], ["draft_blocks"], ["claims_compliance_agent"]),
  ci("claims_compliance_agent", "Claims / Compliance Agent", "Risky claims, promises, escalation to Blue/Bari/internal.", 30, "review_assist", "compliance", ["draft_blocks", "compliance library"], ["compliance_notes"], ["rewrite_strengthening_agent"]),
  ci("rewrite_strengthening_agent", "Rewrite / Strengthening Agent", "Clarity, specificity, punch; preserves meaning.", 31, "draft_only", "rewrite", ["draft_blocks", "voice_notes", "compliance_notes"], ["rewritten_drafts"], ["final_assembly_agent"]),
  ci("final_assembly_agent", "Final Assembly Agent", "Packages best parts for human review; suggests campaign patches only.", 32, "draft_only", "assembly", ["rewritten_drafts"], ["final_package", "suggestedCampaignPatches"], ["human_review_routing_agent"]),
  ci(
    "human_review_routing_agent",
    "Human Review Routing Agent",
    "Internal vs Blue vs Bari recommendations with reasons — no default bottlenecks.",
    33,
    "review_assist",
    "routing",
    ["final_package", "compliance_notes"],
    ["review_recommendations"],
    ["learning_feedback_agent"],
  ),
  ci(
    "learning_feedback_agent",
    "Learning Feedback Agent",
    "Learning candidates from edits/outcomes — not auto-approved in Library.",
    34,
    "learning_candidate",
    "learning",
    ["final_package", "human edits"],
    ["learning_candidates"],
    [],
  ),
  {
    ...ci(
      "copy_pipeline",
      "Copy Pipeline (orchestrator)",
      "Coordinates a full copy dry run across the stack; logs a single agentRun.",
      35,
      "draft_only",
      "orchestrator",
      ["full packet", "library", "production bridge"],
      ["pipeline_run_log"],
      [],
    ),
    nextAgentIds: ["copy_intake_agent"],
    notes: "Copy Intelligence — dry-run orchestrator; no external model required.",
  },
];
