/**
 * Section 10 — Meta Connector exploration: Convex integration rows (planned / read-only future).
 * Seeded via `integrations.seedDefaultIntegrationRecordsIfEmpty` and `seedMetaIntegrationRecordsIfMissing`.
 */

import type { IntegrationConnection } from "@/lib/domain";

const now = "2026-05-13T10:00:00.000Z";

/** Env key names only — presence checked locally; no Meta API calls in this pass. */
const META_APP_KEYS = [
  "META_APP_ID",
  "META_APP_SECRET",
  "META_ACCESS_TOKEN",
  "META_BUSINESS_ID",
  "META_AD_ACCOUNT_ID",
  "META_PAGE_ID",
  "META_INSTAGRAM_BUSINESS_ACCOUNT_ID",
];

export const metaIntegrationConnections: IntegrationConnection[] = [
  {
    id: "meta_platform",
    name: "Meta / Facebook / Instagram",
    provider: "meta",
    category: "meta_social",
    purpose: "Future connector for Meta-owned social surfaces, including Facebook and Instagram performance and content insight workflows.",
    description:
      "Planned read-only analytics for organic and paid surfaces. Manual snapshots and demo data are supported today; live connector is not enabled.",
    status: "not_configured",
    statusLabel: "Planned / not connected",
    envKeys: META_APP_KEYS,
    configuredEnvVars: [],
    missingEnvVars: [...META_APP_KEYS],
    fallback: "Manual performance snapshots and trend signals only",
    lastCheckResult: "No live Meta connection — dry-run posture only.",
    setupNotes:
      "Future: Meta App ID, server-side secret, access token status, Business ID, Page ID, Instagram Business Account ID, and approved read scopes. Publishing scopes are not requested in this phase.",
    setupInstructions:
      "When a read-only connector ships, configure env keys in Operations only after security review. Do not expose secrets in the console UI.",
    healthSummary: "Manual / planned — no posting or account changes enabled.",
    connectorMode: "read_only_future",
    safetyLevel: "no_write_actions",
    plannedCapabilities: ["Performance insights", "Organic content analysis", "Trend signals", "Campaign comparison", "Social rollout learning"],
    disabledCapabilities: ["Posting", "Comment automation", "DM automation", "Account changes"],
    relatedWorkflows: "Performance Intelligence, Trend Intelligence, Social Rollout, Operations",
    requiredScopes: "Read insights scope (future), Page/Instagram read scope (future) — not granted in this pass.",
    configuredScopes: "None — connector not implemented.",
    enabled: true,
    sortOrder: 20,
    createdAt: now,
    updatedAt: now,
    notes: "Disabled: posting, comment automation, DM automation, account changes.",
  },
  {
    id: "meta_ads",
    name: "Meta Ads",
    provider: "meta",
    category: "meta_social",
    purpose: "Future read-only ads intelligence for creative, audience, placement, and campaign performance.",
    description:
      "Planned ads read layer for CPC, CPR, spend, and creative comparison. No ad creation, budget edits, or publishing in this build.",
    status: "not_configured",
    statusLabel: "Planned / read-only future",
    envKeys: META_APP_KEYS,
    configuredEnvVars: [],
    missingEnvVars: [...META_APP_KEYS],
    fallback: "Enter Meta Ads metrics manually in Performance Intelligence",
    lastCheckResult: "Not connected — use manual snapshots labeled demo or manual.",
    setupNotes: "Future: Ads read scope (placeholder wording until implementation). Write actions remain disabled.",
    setupInstructions: "Map ad account and campaigns in a later pass after OAuth and scope approval.",
    healthSummary: "No write actions — budgets, audiences, and campaigns cannot be changed from Outreach Console.",
    connectorMode: "read_only_future",
    safetyLevel: "no_write_actions",
    plannedCapabilities: ["Paid performance snapshots", "CPC / CPR views", "Creative comparison", "Placement patterns", "Recommendation drafting (text only)"],
    disabledCapabilities: ["Budget changes", "Campaign creation", "Campaign edits", "Ad publishing", "Audience mutation"],
    relatedWorkflows: "Performance Intelligence, Copy Intelligence (reviewed context), Operations",
    requiredScopes: "Ads read scope (future) — placeholder only.",
    configuredScopes: "None — connector not implemented.",
    enabled: true,
    sortOrder: 21,
    createdAt: now,
    updatedAt: now,
    notes: "Disabled: budget changes, campaign creation/edits, ad publishing, audience mutation.",
  },
  {
    id: "instagram",
    name: "Instagram (insights)",
    provider: "meta",
    category: "meta_social",
    purpose: "Future Instagram performance and content insights (reels, feed, saves, comments) without auto-post.",
    description: "Read-only future connector; today use manual or demo snapshots in Performance Intelligence.",
    status: "not_configured",
    statusLabel: "Manual data only",
    envKeys: ["META_INSTAGRAM_BUSINESS_ACCOUNT_ID", "META_ACCESS_TOKEN"],
    configuredEnvVars: [],
    missingEnvVars: ["META_INSTAGRAM_BUSINESS_ACCOUNT_ID", "META_ACCESS_TOKEN"],
    fallback: "Manual Instagram metrics in Performance Intelligence",
    lastCheckResult: "No Instagram API — exploratory card only.",
    setupNotes: "Instagram publishing automation is out of scope for Section 10.",
    setupInstructions: "Link business account when read-only connector is approved.",
    healthSummary: "Publishing disabled; insights entry is manual.",
    connectorMode: "manual",
    safetyLevel: "read_only",
    plannedCapabilities: ["Reels and feed metrics", "Saves and comments tracking", "Future read-only sync"],
    disabledCapabilities: ["Auto-post", "Scheduled Instagram publishing"],
    relatedWorkflows: "Performance Intelligence, Trend Intelligence, Campaign Social Rollout",
    requiredScopes: "Instagram business read (future) — not active.",
    configuredScopes: "None.",
    enabled: true,
    sortOrder: 22,
    createdAt: now,
    updatedAt: now,
    notes: "Planned workflows: Performance Intelligence, Trend Intelligence, Social Rollout learning.",
  },
  {
    id: "facebook",
    name: "Facebook (insights)",
    provider: "meta",
    category: "meta_social",
    purpose: "Future Facebook Page insights and engagement patterns for weekly launch learning.",
    description: "Manual or demo snapshots only until a read-only connector exists.",
    status: "not_configured",
    statusLabel: "Manual data only",
    envKeys: ["META_PAGE_ID", "META_ACCESS_TOKEN"],
    configuredEnvVars: [],
    missingEnvVars: ["META_PAGE_ID", "META_ACCESS_TOKEN"],
    fallback: "Manual Facebook metrics in Performance Intelligence",
    lastCheckResult: "No Facebook API configured.",
    setupNotes: "Question posts and engagement prompts can be tracked as manual trend signals.",
    setupInstructions: "Future: page read scope when approved.",
    healthSummary: "No auto-post from Outreach Console.",
    connectorMode: "manual",
    safetyLevel: "read_only",
    plannedCapabilities: ["Page insights", "Engagement question patterns", "Comment volume tracking"],
    disabledCapabilities: ["Page setting changes", "Boosted post automation"],
    relatedWorkflows: "Trend Intelligence, Performance Intelligence, Social Rollout",
    requiredScopes: "Page read (future) — not active.",
    configuredScopes: "None.",
    enabled: true,
    sortOrder: 23,
    createdAt: now,
    updatedAt: now,
    notes: "Related: Campaign Social Rollout, Trend Intelligence, Copy Intelligence context (reviewed signals only).",
  },
  {
    id: "meta_connector_mcp",
    name: "Meta Connector / MCP",
    provider: "meta",
    category: "meta_social",
    purpose: "Future connector layer for AI-assisted Meta data access and analysis where supported.",
    description:
      "Exploration / not connected. Intended to pull insights into Performance and Trend Intelligence and support Copy Intelligence with reviewed patterns — never auto-write to Meta.",
    status: "not_configured",
    statusLabel: "Exploration / not connected",
    envKeys: [],
    configuredEnvVars: [],
    missingEnvVars: [],
    fallback: "Dry-run readiness checks and manual data only",
    lastCheckResult: "No MCP or Meta API calls are made from this pass.",
    setupNotes: "Run “Meta connector readiness (dry-run)” from Operations — validates posture only.",
    setupInstructions: "Write actions require a separate approval-gated implementation.",
    healthSummary: "Read/analyze first; any active write behavior stays disabled.",
    connectorMode: "dry_run",
    safetyLevel: "no_write_actions",
    plannedCapabilities: ["Readiness summaries", "Dry-run mapping to Intelligence surfaces"],
    disabledCapabilities: ["Any active write behavior", "Live MCP bridge without approval"],
    relatedWorkflows: "Operations readiness check, Performance Intelligence, Trend Intelligence, Copy Intelligence",
    requiredScopes: "TBD when MCP design is approved.",
    configuredScopes: "None.",
    enabled: true,
    sortOrder: 24,
    createdAt: now,
    updatedAt: now,
    notes: "Safety: read_only / dry_run / planned — no active_write_enabled.",
  },
];
