import type { AgentConfigSeed } from "./agent-config";

function pi(
  agentId: string,
  displayName: string,
  shortDescription: string,
  workflowOrder: number,
  safetyMode: string,
  agentRole: string,
  inputSources: string[],
  outputTargets: string[],
  nextAgentIds: string[],
): AgentConfigSeed {
  return {
    agentId,
    displayName,
    shortDescription,
    workflowOrder,
    category: "performance_intelligence",
    groupId: "performance_intelligence",
    safetyMode,
    agentRole,
    inputSources,
    outputTargets,
    isCore: true,
    enabled: true,
    systemPrompt: `${displayName} — Section 8 Performance Intelligence. Manual and read-only planned; no auto-spend, no auto-post, no live writes.`,
    taskPromptTemplate: "Analyze metrics evidence only; label uncertainty; never imply live warehouse data without source proof.",
    styleGuidance: "Operational, calm, evidence-first; distinguish demo/manual/import/future sync.",
    requiredContextSources: ["performance snapshots", "campaign context when linked"],
    exampleReferences: ["intelligence/performance"],
    preferredProvider: "demo",
    preferredModel: "performance-intelligence-dry-run",
    temperature: 0.15,
    maxTokens: 2200,
    structuredOutputRequired: true,
    inputSchema: { snapshots: "array", filters: "object" },
    outputSchema: { summary: "string", warnings: "array", safetyMode: "string" },
    requiredInputs: ["operator-approved metrics context"],
    optionalInputs: ["campaign", "library", "trends", "production assets"],
    requiredOutputs: ["notes"],
    escalationMarkers: ["incomplete metrics", "stale data", "unsupported attribution claim"],
    confidenceField: "evidenceStrength",
    riskField: "dataQualityRisk",
    activeRules: ["Human approval for learnings", "Label sourceSystem and sourceMode on every output"],
    blockingRules: ["No ad budget changes", "No auto-post", "No auto-send", "No auto-approve learnings"],
    warningRules: ["Connectors listed in Operations are placeholders until configured read-only"],
    allowedActions: ["read", "summarize", "compare", "draft review text", "propose learning candidates"],
    disallowedActions: ["modify campaigns automatically", "call external analytics APIs without explicit connector"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds,
    fallbackAgentId: "human_approval",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["structured output emitted or dry-run aborted with warnings"],
    retryPolicy: "manual retry",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: `Performance Intelligence — ${agentRole}.`,
  };
}

export const performanceIntelligenceAgentSeeds: AgentConfigSeed[] = [
  pi("metrics_pull_agent", "Metrics Pull Agent", "Future read-only connector layer for pulling metrics from platforms (planned).", 410, "planned", "pull", ["platform", "date range", "content URLs"], ["raw metric snapshot"], ["metrics_normalization_agent"]),
  pi(
    "metrics_normalization_agent",
    "Metrics Normalization Agent",
    "Maps platform-native metrics into the shared performance snapshot shape (dry-run).",
    411,
    "dry_run",
    "normalize",
    ["raw metrics", "platform schema hints"],
    ["normalized snapshot draft", "missing fields"],
    ["dashboard_writer_agent"],
  ),
  pi(
    "dashboard_writer_agent",
    "Dashboard Writer Agent",
    "Turns metrics into readable dashboard summaries and operator-facing explanations.",
    412,
    "draft_only",
    "dashboard",
    ["snapshots", "filters"],
    ["summary", "wins", "misses"],
    ["campaign_comparison_agent"],
  ),
  pi(
    "campaign_comparison_agent",
    "Campaign Comparison Agent",
    "Compares weekly launch packets using evidence-backed aggregates.",
    413,
    "analysis_only",
    "compare",
    ["multiple campaigns", "snapshots"],
    ["comparison notes", "strongest/weakest signals"],
    ["pattern_analysis_agent"],
  ),
  pi(
    "pattern_analysis_agent",
    "Pattern Analysis Agent",
    "Surfaces patterns across hooks, topics, CTAs, platforms, and content types.",
    414,
    "analysis_only",
    "patterns",
    ["snapshots", "labels", "library metadata"],
    ["pattern summary", "hypotheses", "evidence strength"],
    ["recommendation_agent"],
  ),
  pi(
    "recommendation_agent",
    "Recommendation Agent",
    "Suggests what to repeat, test, stop, or prioritize — recommendation only.",
    415,
    "recommendation_only",
    "recommend",
    ["pattern analysis", "campaign goals"],
    ["recommendations", "next tests"],
    ["learning_capture_agent"],
  ),
  pi(
    "learning_capture_agent",
    "Learning Capture Agent",
    "Turns performance evidence into learning candidates — never auto-approves.",
    416,
    "learning_candidate",
    "learning",
    ["review output", "human notes"],
    ["learning candidates"],
    ["performance_qa_agent"],
  ),
  pi("performance_qa_agent", "Performance QA Agent", "Flags incomplete, stale, or inconsistent metrics before decisions.", 417, "read_only", "qa", ["snapshots", "sources"], ["warnings", "duplicate hints"], []),
];
