import type { AgentConfigSeed } from "./agent-config";

function pci(
  agentId: string,
  displayName: string,
  shortDescription: string,
  workflowOrder: number,
  safetyMode: string,
  agentRole: string,
  inputSources: string[],
  outputTargets: string[],
  nextAgentIds: string[],
): AgentConfigSeed {
  return {
    agentId,
    displayName,
    shortDescription,
    workflowOrder,
    category: "platform_connector_intelligence",
    groupId: "platform_connector_intelligence",
    safetyMode,
    agentRole,
    inputSources,
    outputTargets,
    isCore: true,
    enabled: true,
    systemPrompt: `${displayName} — Section 10 Platform Connector Intelligence. Meta and social connectors are planned; no live API or write actions in this pass.`,
    taskPromptTemplate: "Produce dry-run or analysis outputs only; label all data as manual, demo, or planned.",
    styleGuidance: "Never imply live Meta connection; never recommend unapproved writes.",
    requiredContextSources: ["integration records", "operator context"],
    exampleReferences: ["operations/integrations", "intelligence/performance"],
    preferredProvider: "demo",
    preferredModel: "platform-connector-dry-run",
    temperature: 0.15,
    maxTokens: 1600,
    structuredOutputRequired: true,
    inputSchema: { integration: "object", snapshots: "object?" },
    outputSchema: { summary: "string", notes: ["string"], warnings: ["string"] },
    requiredInputs: ["integration"],
    optionalInputs: ["snapshots", "trends"],
    requiredOutputs: ["summary"],
    escalationMarkers: ["write action requested", "missing approval path"],
    confidenceField: "connectorConfidence",
    riskField: "connectorRisk",
    activeRules: ["Dry-run unless explicitly approved read-only connector exists", "No token or secret echo"],
    blockingRules: ["No Meta posting", "No ad or budget mutations", "No OAuth from this agent"],
    warningRules: ["Demo/manual data must stay labeled"],
    allowedActions: ["summarize readiness", "map metrics", "draft recommendations as text"],
    disallowedActions: ["call Meta API", "mutate campaigns", "upload creatives"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds,
    fallbackAgentId: "meta_safety_guard_agent",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["structured output emitted"],
    retryPolicy: "manual",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed_section10",
    notes: `Platform Connector Intelligence — ${agentRole}.`,
  };
}

export const platformConnectorIntelligenceAgentSeeds: AgentConfigSeed[] = [
  pci("meta_readiness_checker", "Meta Readiness Checker", "Dry-run checklist for Meta-related integration posture and missing setup items.", 450, "dry_run", "readiness", ["integration rows", "env key names"], ["readiness_summary"], ["meta_metrics_mapper"]),
  pci("meta_metrics_mapper", "Meta Metrics Mapper", "Maps future Meta metrics fields into performance snapshot shape (documentation-only).", 451, "planned", "mapper", ["snapshot schema", "future raw insights"], ["normalized_fields", "mapping_gaps"], ["meta_creative_pattern_agent"]),
  pci("meta_creative_pattern_agent", "Meta Creative Pattern Agent", "Surfaces creative / hook / CTA patterns from labeled performance data (analysis only).", 452, "analysis_only", "patterns", ["snapshots", "labels"], ["pattern_notes", "test_ideas"], ["meta_trend_signal_agent"]),
  pci("meta_trend_signal_agent", "Meta Trend Signal Agent", "Drafts trend candidates from Meta/Instagram observations — human review required.", 453, "review_assist", "trends", ["trend table", "manual notes"], ["trend_candidates"], ["meta_performance_summary_agent"]),
  pci("meta_performance_summary_agent", "Meta Performance Summary Agent", "Summarizes Meta/Facebook/Instagram slices for campaigns (no live pull).", 454, "analysis_only", "summary", ["snapshots", "campaign"], ["wins", "misses", "warnings"], ["meta_recommendation_draft_agent"]),
  pci("meta_recommendation_draft_agent", "Meta Recommendation Draft Agent", "Drafts next-test recommendations as text — not actions.", 455, "recommendation_only", "recommend", ["summary", "goals"], ["recommendation_drafts"], ["meta_safety_guard_agent"]),
  pci("meta_safety_guard_agent", "Meta Safety Guard Agent", "Blocks proposed Meta write paths unless a future approval-gated flow exists.", 456, "guardrail", "safety", ["proposed action", "integration mode"], ["allow_deny", "safety_notes"], []),
];
