import { campaigns, integrations, responses } from "@/lib/data/demo-data";
import type { TodayTaskRecord } from "@/lib/domain";

function destinationModeForRoute(route: string): TodayTaskRecord["destinationMode"] {
  if (route.startsWith("/reviews")) return "review";
  if (route.startsWith("/libraries")) return "library";
  if (route.startsWith("/intelligence")) return "intelligence";
  if (route.startsWith("/operations")) return "operations";
  return "campaign";
}

export function buildDefaultTodayTasks(now = Date.now()): TodayTaskRecord[] {
  const firstResponse = responses[0];
  const firstCampaign = campaigns[0];
  const firstIntegrationIssue = integrations.find((integration) => integration.status === "manual_mode" || integration.status === "missing_credentials" || integration.status === "error");

  const tasks: Omit<TodayTaskRecord, "destinationMode" | "updatedAt">[] = [
    {
      taskId: "task-mon-source-video",
      title: "Monday — Select next week’s source asset for the launch packet",
      context: "Campaign Heartbeat: lock the long-form asset with Brett / Kelsey.",
      category: "Heartbeat",
      priority: "green",
      sourceRoute: "/dashboard",
      sourceLabel: "Home",
      createdAt: now - 1000 * 60 * 120,
      status: "current",
      sortOrder: 1,
    },
    {
      taskId: "task-mon-angle-promise",
      title: "Monday — Review launch angle and promise language (internal)",
      context: firstCampaign?.name ?? "Weekly launch packet",
      category: "Copy",
      priority: "green",
      sourceRoute: "/campaigns",
      sourceLabel: "Campaigns / launch packet",
      createdAt: now - 1000 * 60 * 118,
      status: "current",
      sortOrder: 2,
    },
    {
      taskId: "task-mon-copy-packet",
      title: "Monday — Run Copy Intelligence dry-run for weekly packet",
      context: "Human-controlled; draft-only until approvals. No auto-send.",
      category: "Copy",
      priority: "amber",
      sourceRoute: "/intelligence/langgraph",
      sourceLabel: "Copy Intelligence",
      createdAt: now - 1000 * 60 * 115,
      status: "current",
      sortOrder: 3,
    },
    {
      taskId: "task-tue-youtube-link",
      title: "Tuesday — Finalize scheduled YouTube link in launch packet",
      context: "Publishing stays human-triggered; capture URL in packet notes.",
      category: "Production",
      priority: "amber",
      sourceRoute: "/campaigns",
      sourceLabel: "Campaigns / launch packet",
      createdAt: now - 1000 * 60 * 100,
      status: "current",
      sortOrder: 4,
    },
    {
      taskId: "task-tue-email-handoff",
      title: "Tuesday — Confirm Emailmarketing.com handoff checklist",
      context: "Manual coordination; no auto-send from the console.",
      category: "Handoff",
      priority: "amber",
      sourceRoute: "/campaigns",
      sourceLabel: "Campaigns / email handoff",
      createdAt: now - 1000 * 60 * 95,
      status: "current",
      sortOrder: 5,
    },
    {
      taskId: "task-tue-brandon-brief",
      title: "Tuesday — Send creative brief to Brandon (shorts / reels)",
      context: "Creative handoff — follow-up needed until Brandon confirms.",
      category: "Production",
      priority: "amber",
      sourceRoute: "/campaigns",
      sourceLabel: "Campaigns / creative handoff",
      createdAt: now - 1000 * 60 * 90,
      status: "current",
      sortOrder: 6,
    },
    {
      taskId: "task-tue-social-copy",
      title: "Tuesday — Draft social rollout captions",
      context: "Social rollout prep — no auto-post.",
      category: "Social",
      priority: "green",
      sourceRoute: "/campaigns",
      sourceLabel: "Campaigns / social rollout",
      createdAt: now - 1000 * 60 * 88,
      status: "current",
      sortOrder: 7,
    },
    {
      taskId: "task-wed-handoffs",
      title: "Wednesday — Validate weekly launch handoff (Emailmarketing.com + Brandon)",
      context: "Confirm in thread or tracker — not an automated API send.",
      category: "Handoff",
      priority: "red",
      sourceRoute: "/dashboard",
      sourceLabel: "Home",
      createdAt: now - 1000 * 60 * 72,
      status: "current",
      sortOrder: 8,
    },
    {
      taskId: "task-thu-readiness-review",
      title: "Thursday — Complete Friday launch readiness review prep",
      context: "Check scheduled link, email, creative, and social lines in the packet.",
      category: "Readiness",
      priority: "amber",
      sourceRoute: "/reviews/internal",
      sourceLabel: "Reviews / internal",
      createdAt: now - 1000 * 60 * 50,
      status: "current",
      sortOrder: 9,
    },
    {
      taskId: "task-thu-blue-escalation",
      title: "Thursday — Blue: strategic / claims review (escalation only)",
      context: "Weekly launch — only when risk is flagged.",
      category: "Review",
      priority: "blue",
      sourceRoute: "/reviews/blue",
      sourceLabel: "Reviews / Blue",
      createdAt: now - 1000 * 60 * 48,
      status: "current",
      sortOrder: 10,
    },
    {
      taskId: "task-fri-packet-readiness",
      title: "Friday — Confirm launch packet readiness before send window",
      context: "Campaign Heartbeat summary and internal sign-off.",
      category: "Readiness",
      priority: "amber",
      sourceRoute: "/reviews/internal",
      sourceLabel: "Reviews / internal",
      createdAt: now - 1000 * 60 * 35,
      status: "current",
      sortOrder: 11,
    },
    {
      taskId: "task-bari-founder-voice",
      title: "Friday — Bari: founder-voice pass on weekly email (if queued)",
      context: `${firstCampaign?.name ?? "Weekly launch"} — escalation gate when required.`,
      category: "Review",
      priority: "amber",
      sourceRoute: "/reviews/bari",
      sourceLabel: "Reviews / Bari",
      createdAt: now - 1000 * 60 * 32,
      status: "current",
      sortOrder: 12,
    },
    {
      taskId: "task-response-intelligence",
      title: "Review response from interested attendee (draft reply)",
      context: firstResponse?.summary ?? "Registration or weekly launch context — draft only.",
      category: "Responses",
      priority: "amber",
      sourceRoute: "/intelligence/responses",
      sourceLabel: "Response Intelligence",
      createdAt: now - 1000 * 60 * 28,
      status: "current",
      sortOrder: 13,
    },
    {
      taskId: "task-integrations",
      title: "Operations — integration posture check (read-only / manual)",
      context: firstIntegrationIssue ? `${firstIntegrationIssue.name} still manual or not configured.` : "Hermes and other bridges stay gated until you connect them.",
      category: "Readiness",
      priority: "amber",
      sourceRoute: "/operations/integrations",
      sourceLabel: "Operations",
      createdAt: now - 1000 * 60 * 22,
      status: "current",
      sortOrder: 14,
    },
    {
      taskId: "task-performance-intel",
      title: "Performance Intelligence — add snapshot for last launch",
      context: "Demo data until read-only connectors ship.",
      category: "Performance",
      priority: "green",
      sourceRoute: "/intelligence/performance",
      sourceLabel: "Performance Intelligence",
      createdAt: now - 1000 * 60 * 15,
      status: "current",
      sortOrder: 15,
    },
    {
      taskId: "task-library-learning",
      title: "Content Library — review campaign learning candidate",
      context: "Capture approved learnings for the next weekly launch.",
      category: "Readiness",
      priority: "green",
      sourceRoute: "/libraries/learning",
      sourceLabel: "Content Library",
      createdAt: now - 1000 * 60 * 12,
      status: "current",
      sortOrder: 16,
    },
  ];

  return tasks.map((task) => ({
    ...task,
    destinationMode: destinationModeForRoute(task.sourceRoute),
    updatedAt: task.createdAt,
  }));
}
