import { campaigns, integrations, responses } from "@/lib/data/demo-data";
import type { TodayTaskRecord } from "@/lib/domain";

function destinationModeForRoute(route: string): TodayTaskRecord["destinationMode"] {
  if (route.startsWith("/reviews")) return "review";
  if (route.startsWith("/libraries")) return "library";
  if (route.startsWith("/intelligence")) return "intelligence";
  if (route.startsWith("/operations")) return "operations";
  return "campaign";
}

export function buildDefaultTodayTasks(now = Date.now()): TodayTaskRecord[] {
  const firstResponse = responses[0];
  const firstCampaign = campaigns[0];
  const firstIntegrationIssue = integrations.find((integration) => integration.status === "manual_mode" || integration.status === "missing_credentials" || integration.status === "error");

  const tasks: Omit<TodayTaskRecord, "destinationMode" | "updatedAt">[] = [
    {
      taskId: "task-mon-source-video",
      title: "Monday — Select next week’s source video (Brett / Kelsey)",
      context: "Campaign Heartbeat: lock the long-form asset for the weekly launch packet.",
      category: "Heartbeat",
      priority: "green",
      sourceRoute: "/dashboard",
      sourceLabel: "Home / Today",
      createdAt: now - 1000 * 60 * 120,
      status: "current",
      sortOrder: 1,
    },
    {
      taskId: "task-mon-angle-cta",
      title: "Monday — Define campaign angle + primary CTA (internal)",
      context: firstCampaign?.name ?? "Weekly launch packet",
      category: "Copy",
      priority: "green",
      sourceRoute: "/campaigns",
      sourceLabel: "Campaigns",
      createdAt: now - 1000 * 60 * 118,
      status: "current",
      sortOrder: 2,
    },
    {
      taskId: "task-mon-copy-packet",
      title: "Monday — Generate first-pass copy packet (Copy Intelligence dry-run)",
      context: "LangGraph / agents — human approval still required before any send.",
      category: "Copy",
      priority: "amber",
      sourceRoute: "/intelligence/langgraph",
      sourceLabel: "Intelligence / LangGraph Map",
      createdAt: now - 1000 * 60 * 115,
      status: "current",
      sortOrder: 3,
    },
    {
      taskId: "task-tue-youtube-copy",
      title: "Tuesday — Finalize YouTube title + description draft",
      context: firstCampaign?.name ?? "Weekly launch",
      category: "Production",
      priority: "amber",
      sourceRoute: "/campaigns",
      sourceLabel: "Campaigns",
      createdAt: now - 1000 * 60 * 100,
      status: "current",
      sortOrder: 4,
    },
    {
      taskId: "task-tue-email-brief",
      title: "Tuesday — Draft Emailmarketing.com brief (manual send later)",
      context: "Email handoff — no auto-send from console.",
      category: "Handoff",
      priority: "amber",
      sourceRoute: "/operations/keap",
      sourceLabel: "Operations / Keap Sync",
      createdAt: now - 1000 * 60 * 95,
      status: "current",
      sortOrder: 5,
    },
    {
      taskId: "task-tue-brandon-brief",
      title: "Tuesday — Draft Brandon creative / shorts brief",
      context: "Creative handoff — Brandon produces cuts; OC tracks status only.",
      category: "Production",
      priority: "amber",
      sourceRoute: "/campaigns",
      sourceLabel: "Campaigns",
      createdAt: now - 1000 * 60 * 90,
      status: "current",
      sortOrder: 6,
    },
    {
      taskId: "task-tue-social-copy",
      title: "Tuesday — Draft social rollout copy (Reels / Shorts captions)",
      context: "Social rollout prep — no auto-post.",
      category: "Social",
      priority: "green",
      sourceRoute: "/campaigns",
      sourceLabel: "Campaigns",
      createdAt: now - 1000 * 60 * 88,
      status: "current",
      sortOrder: 7,
    },
    {
      taskId: "task-wed-schedule-youtube",
      title: "Wednesday — Schedule next week’s YouTube premiere (manual)",
      context: "Publishing is human-triggered; capture scheduled URL in packet notes.",
      category: "Production",
      priority: "amber",
      sourceRoute: "/dashboard",
      sourceLabel: "Home / Today",
      createdAt: now - 1000 * 60 * 72,
      status: "current",
      sortOrder: 8,
    },
    {
      taskId: "task-wed-handoffs",
      title: "Wednesday — Send brief + scheduled link to Emailmarketing.com; send creative brief to Brandon",
      context: "Parallel handoffs — confirm in thread, not auto API.",
      category: "Handoff",
      priority: "red",
      sourceRoute: "/operations/integrations",
      sourceLabel: "Operations / Integrations",
      createdAt: now - 1000 * 60 * 68,
      status: "current",
      sortOrder: 9,
    },
    {
      taskId: "task-thu-confirmations",
      title: "Thursday — Check Emailmarketing.com confirmation + Brandon creative status",
      context: "Readiness + external follow-ups — manual checks.",
      category: "Readiness",
      priority: "amber",
      sourceRoute: "/dashboard",
      sourceLabel: "Home / Today",
      createdAt: now - 1000 * 60 * 50,
      status: "current",
      sortOrder: 10,
    },
    {
      taskId: "task-thu-blue-escalation",
      title: "Thursday — Blue: review one strategic claim only if risk flagged (escalation)",
      context: "Weekly Launch / September warmup — not every task waits on Blue.",
      category: "Review",
      priority: "blue",
      sourceRoute: "/reviews/blue",
      sourceLabel: "Reviews / Blue Review",
      createdAt: now - 1000 * 60 * 48,
      status: "current",
      sortOrder: 11,
    },
    {
      taskId: "task-fri-packet-readiness",
      title: "Friday — Confirm launch packet readiness (YouTube link, email, creative, social)",
      context: "Internal readiness queue — Campaign Heartbeat summary.",
      category: "Readiness",
      priority: "amber",
      sourceRoute: "/reviews/internal",
      sourceLabel: "Reviews / Internal Approvals",
      createdAt: now - 1000 * 60 * 35,
      status: "current",
      sortOrder: 12,
    },
    {
      taskId: "task-bari-founder-voice",
      title: "Friday — Bari: quick founder-voice pass on weekly email (escalation)",
      context: `${firstCampaign?.name ?? "Weekly launch"} — one founder-voice gate, not a universal blocker.`,
      category: "Review",
      priority: "amber",
      sourceRoute: "/reviews/bari",
      sourceLabel: "Reviews / Bari Copy Review",
      createdAt: now - 1000 * 60 * 32,
      status: "current",
      sortOrder: 13,
    },
    {
      taskId: "task-response-intelligence",
      title: "Reply triage — interested lead on weekly launch (Response Intelligence)",
      context: firstResponse?.summary ?? "Inbound reply matched to weekly launch campaign.",
      category: "Performance",
      priority: "amber",
      sourceRoute: "/intelligence/responses",
      sourceLabel: "Intelligence / Response Intelligence",
      createdAt: now - 1000 * 60 * 28,
      status: "current",
      sortOrder: 14,
    },
    {
      taskId: "task-integrations",
      title: "Integration safety check — credentials + manual mode (Kelsey)",
      context: firstIntegrationIssue ? `${firstIntegrationIssue.name} still manual/read-only.` : "Several bridges remain planned or manual until connected.",
      category: "Readiness",
      priority: "amber",
      sourceRoute: "/operations/integrations",
      sourceLabel: "Operations / Integrations",
      createdAt: now - 1000 * 60 * 22,
      status: "current",
      sortOrder: 15,
    },
    {
      taskId: "task-performance-intel",
      title: "Performance Intelligence — review demo hook comparison notes",
      context: "Demo metrics only — not live analytics warehouse.",
      category: "Performance",
      priority: "green",
      sourceRoute: "/intelligence/performance",
      sourceLabel: "Intelligence / Performance Intelligence",
      createdAt: now - 1000 * 60 * 15,
      status: "current",
      sortOrder: 16,
    },
  ];

  return tasks.map((task) => ({
    ...task,
    destinationMode: destinationModeForRoute(task.sourceRoute),
    updatedAt: task.createdAt,
  }));
}
