import type { AgentConfigSeed } from "./agent-config";

function ti(
  agentId: string,
  displayName: string,
  shortDescription: string,
  workflowOrder: number,
  safetyMode: string,
  agentRole: string,
  inputSources: string[],
  outputTargets: string[],
  nextAgentIds: string[],
): AgentConfigSeed {
  return {
    agentId,
    displayName,
    shortDescription,
    workflowOrder,
    category: "trend_intelligence",
    groupId: "trend_intelligence",
    safetyMode,
    agentRole,
    inputSources,
    outputTargets,
    isCore: true,
    enabled: true,
    systemPrompt: `${displayName} — Section 7 Trend Intelligence. Human-controlled research layer; no auto-post, no live scraping by default.`,
    taskPromptTemplate: "Evaluate trends for brand, audience, platform fit; emit structured signals and adaptation notes only.",
    styleGuidance: "Label outside examples as inspiration_only; never imply Sage owns third-party creative.",
    requiredContextSources: ["operator notes", "campaign context when linked"],
    exampleReferences: ["intelligence/trends"],
    preferredProvider: "demo",
    preferredModel: "trend-intelligence-dry-run",
    temperature: 0.2,
    maxTokens: 1800,
    structuredOutputRequired: true,
    inputSchema: { trendSignal: "object", context: "object" },
    outputSchema: { signals: "array", notes: ["string"], safetyMode: "string" },
    requiredInputs: ["trend context"],
    optionalInputs: ["library", "campaign", "playbooks"],
    requiredOutputs: ["notes"],
    escalationMarkers: ["off-brand trend", "high risk meme", "stale timeliness"],
    confidenceField: "trendConfidence",
    riskField: "trendRisk",
    activeRules: ["Manual or planned sources only unless connector approved", "Approved means safe to adapt, not copy"],
    blockingRules: ["No auto-post", "No live platform writes", "No scraping private data"],
    warningRules: ["Connectors in Operations are placeholders until configured"],
    allowedActions: ["record", "score", "suggest adaptation", "link campaign", "flag risk"],
    disallowedActions: ["post social", "send to Brandon automatically", "auto-approve trends"],
    humanApprovalRequired: false,
    canCreateApprovalItems: false,
    canModifyCopy: false,
    canReadLibraries: true,
    canTriggerIntegrations: false,
    nextAgentIds,
    fallbackAgentId: "human_approval",
    blockedRoute: "human_approval",
    humanPauseRoute: "human_approval",
    handoffConditions: ["trend signal recorded or dry-run summary emitted"],
    retryPolicy: "manual retry",
    maxRetries: 0,
    configVersion: 1,
    lastEditedBy: "system_seed",
    notes: `Trend Intelligence — ${agentRole}.`,
  };
}

export const trendIntelligenceAgentSeeds: AgentConfigSeed[] = [
  ti("trend_scout_agent", "Trend Scout Agent", "Records or discovers trend signals from manual research or future connectors.", 300, "dry_run", "scout", ["platform", "topic", "links"], ["candidate_signals"], ["trend_fit_agent"]),
  ti(
    "trend_fit_agent",
    "Trend Fit Agent",
    "Scores brand, audience, and campaign relevance; use/avoid recommendation.",
    301,
    "review_assist",
    "fit",
    ["trend signal", "voice rules", "audience intel"],
    ["fit_scores", "fit_notes"],
    ["content_adaptation_agent"],
  ),
  ti(
    "content_adaptation_agent",
    "Content Adaptation Agent",
    "Turns trends into reel, meme, caption, and creative-brief directions (draft only).",
    302,
    "draft_only",
    "adaptation",
    ["trend signal", "campaign angle", "CTA"],
    ["adaptation_ideas", "hooks", "captions"],
    ["trend_risk_agent"],
  ),
  ti("trend_risk_agent", "Trend Risk Agent", "Flags gimmick, stale, misleading, or compliance-sensitive trend usage.", 303, "review_assist", "risk", ["trend signal", "compliance rules"], ["risk_notes", "risk_score"], ["platform_pattern_agent"]),
  ti(
    "platform_pattern_agent",
    "Platform Pattern Agent",
    "Summarizes repeatable platform patterns as playbook candidates.",
    304,
    "learning_candidate",
    "patterns",
    ["multiple signals", "playbooks"],
    ["pattern_summary", "playbook_candidate"],
    ["trend_to_campaign_mapper"],
  ),
  ti(
    "trend_to_campaign_mapper",
    "Trend-to-Campaign Mapper",
    "Suggests which Weekly Launch Packets could use a trend and why.",
    305,
    "review_assist",
    "mapper",
    ["active campaigns", "trend signals"],
    ["related_campaign_suggestions"],
    ["trend_learning_agent"],
  ),
  ti(
    "trend_learning_agent",
    "Trend Learning Agent",
    "Produces learning / playbook candidates after use — human approval required.",
    306,
    "learning_candidate",
    "learning",
    ["used trends", "performance notes"],
    ["learning_candidates"],
    [],
  ),
];
